### ISSUE TITLE
inconsistent preprocessor use of KOKKOS_ENABLE_PROFILING

### ISSUE THREAD

**Issue by ambrad** [kokkos/kokkos#1028]
It appears the installation process puts the line

#define KOKKOS_ENABLE_PROFILING

in the KokkosCore_config.h file, but then the headers use #if instead of #if defined or #ifdef in a couple of spots, such as here:

./Kokkos_Parallel_Reduce.hpp:1019:  #if (KOKKOS_ENABLE_PROFILING)
./Kokkos_Parallel_Reduce.hpp:1045:  #if (KOKKOS_ENABLE_PROFILING)

Causes a compile error with Intel 16. Thanks.

**Comment by nmhamster** [comment]
@ambrad @crtrott - when I originally wrote the code I used `#define KOKKOS_ENABLE_PROFILING`. This was changed later as part of a unified drive but I thought we were now going back to the original defines. Argh.

**Comment by dsunder** [comment]
So the previous fix only touched code that has been ifdef out since Feb 2017.  After talking with @ambrad we determined the problem is twofold.  

1.  Seacas is distributing its own version of Kokkos which conflicts with other versions
2. The intel-16 branch of the code Andrew is using has not been updated to use same version of Kokkos that the intel-17 branch is using.

**Comment by ambrad** [comment]
Just point 2 was the problem; it was thought that both installations had been updated, but only the 17 one was. Point 1 is being worked on independently, and for now we can build seacas with its Kokkos turned off.
