### ISSUE TITLE
Experimental::md_parallel_for bug

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#1057]
This is a placeholder for a bug that was noticed but not fully tracked down. The kernel snippet below will induce a segfault in the convertex BoxLib code when it is switched from `Kokkos::parallel_for` to `Kokkos::Experimental::md_parallel_for`:
```cpp
    ViewFab<T> fab = this->view_fab;
    T _val = val;

    Kokkos::parallel_for(mdpolicy<4>({lo[0], lo[1], lo[2], ns}, {hi[0]+1, hi[1]+1, hi[2]+1, ns+num}, {cb[0], cb[1], cb[2], num}), 
    KOKKOS_LAMBDA(const int i, const int j, const int k, const int n){
        fab(i,j,k,n) = _val;
    });
```
This complicates #1056, because `md_parallel_for` is both faster and more buggy.

**Comment by ndellingwood** [comment]
@ibaned thanks for reporting. I had intended to deprecate and later remove the `md_parallel_*` code after adding the `Parallel{For,Reduce}` specializations to use the `parallel_*` API in Kokkos, and fixed some bugs while working on that, but because of the performance difference you noticed #1056  will hold off on deprecating until determining whether best path forward to preserving performance can be achieved with use of the existing `parallel_*` API, or if we should consider keeping `md_parallel_*` and fixing the bugs there.

**Comment by ndellingwood** [comment]
PR #1102 has fix for this
