### ISSUE TITLE
Which headers are safe for users to include?

### ISSUE THREAD

**Issue by vbrunini** [kokkos/kokkos#1148]
In the interest of minimizing build times tools like https://include-what-you-use.org are very useful for removing unnecessary include files, but they will commonly suggest that I replace #include "Kokkos_Core.hpp" with individual #include "Kokkos_View.hpp" and/or #include "Kokkos_Macros.hpp". Is this something that is safe for code using Kokkos to do, or will this potentially lead to breakage when Kokkos is updated?

More generally, I know some headers like those in the impl/ directory are obviously private but is there a policy on which headers are public and safe to include in user code? Would you be open to adding IWYU pragmas (https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUPragmas.md) to private headers so that tools can be aware of whatever the usage guidelines are?

**Comment by hcedwar** [comment]
Due to the compiler and target architecture detection macros and associated partial specializations we require `#include <Kokkos_Core.hpp>`.  For managing components we put _tend to be public API_ in the `src` directories and _private stuff_ in the `src/impl` directories.

FYI: A major effort for Oct'17 - Sept'18 is to slow down new feature R&D and focus on improving runtime performance, code hygiene, and build times. Incorporating (restoring from our early days) **IWYU** best practices is a good goal.
