### ISSUE TITLE
KOKKOS_ALIGN and KOKKOS_ALIGN_PTR disappeared in master

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#1203]
See Nalu issue https://github.com/NaluCFD/Nalu/issues/21#issuecomment-340462271 .  It looks like the `KOKKOS_ALIGN` and `KOKKOS_ALIGN_PTR` macros have disappeared from Kokkos master (at least the version snapshotted into Trilinos).

Temporary replacement for `KOKKOS_ALIGN_PTR` appears to be `KOKKOS_IMPL_ALIGN_PTR`, but `IMPL` in the name strongly suggests that users aren't supposed to use this macro.

Questions:
  1. Could Kokkos bring back the original macro for backwards compatibility?
  2. If not, are users supposed to use the new macro names, or are they only for internal Kokkos use?

**Comment by ibaned** [comment]
@hcedwar

**Comment by hcedwar** [comment]
@mhoemmen 
There were redundant memory alignment macros that were consolidated / cleaned up.
The `KOKKOS_IMPL_ALIGN_PTR(size)` is accessible to users and since we need it internally is highly likely to be around.
The `IMPL` indicates that this is not within the promised-stable public interface; it's renaming is part of our effort to be more careful about naming things since names convey intent.  The original macro was never intended to carry the stability promise.

**Comment by mhoemmen** [comment]
@hcedwar Thanks for the info -- I forwarded this on to the Nalu developers.

**Comment by spdomin** [comment]
@mhoemmen, many thanks:) NaluCFD is the place to provide us with such information in the future as the spdomin location has been deprecated.
