### ISSUE TITLE
Kokkos::View extent() gives 1 for uninitialized dimensions

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#1263]
Kokkos::View `extent()` is giving `1` for dimensions > rank instead of `0`. For example, if I have a view of rank 1, `view.extent(6)` returns 1, not 0. As far as I can tell, this doesn't match http://en.cppreference.com/w/cpp/types/extent. For example:

```c++
  Kokkos::View<int*> k;
  printf("test 1 extent(0) = %i, extent(6) = %i\n",k.extent(0),k.extent(6));

  Kokkos::View<int*> k2("test",1234);
  printf("test 2 extent(0) = %i, extent(6) = %i\n",k2.extent(0),k2.extent(6));
```

Gives:

```
test 1 extent(0) = 0, extent(6) = 1
test 2 extent(0) = 1234, extent(6) = 1
```

**Comment by ibaned** [comment]
I believe this is on purpose, and has something to do with `DynRankView`. @hcedwar might have more info.

**Comment by stanmoore1** [comment]
The `view.dimension_6()` also gives the same behavior as `view.extent(6)` in the example above.

**Comment by ndellingwood** [comment]
This is on purpose, not just for DynRankView but was needed for Intrepid2 (I think prior to creation of DynRankView).

**Comment by stanmoore1** [comment]
It just seems a little ironic to "deprecate all `dimension` functions in favor of ISO/C++ vocabulary `extent`" (see comment here: https://github.com/kokkos/kokkos/blob/master/core/src/Kokkos_View.hpp#L523) but then not follow the ISO/C++ behavior of `extent`...

**Comment by crtrott** [comment]
I think we may need to have another discussion with the Intrepid developers. We also ran into the issue again that someone forgot a * on his view class typedef, and thus got wrong runtime behavior, but not a crash.

**Comment by kyungjoo-kim** [comment]
This is because we want to maintain a single implementation for the same math equations. For a simple example, consider ``A = alpha X``, where alpha is scalar, A and X can be either a vector or a matrix. Then, when the extra dimension gives 1, we can write a single function for two cases by considering that A(i) is essentially same as A(i,0) with the second dimension 1. I believe that this feature exist before intrepid involves and Kokkos supports additional arguments in ``operato()(int i, Args... Prop)``.  I also think that this feature is widely used in many applications and guess that we have some troubles when we disable this behavior.

**Comment by stanmoore1** [comment]
So why not have two functions, one that gives 1 for uninitialized dimensions and another that gives 0, and call the one that gives 0 `extent` so it matches c++.

**Comment by ibaned** [comment]
`extent` may be new enough that we can still change its behavior

**Comment by kyungjoo-kim** [comment]
Question. Does it mean that ``extent`` may behave differently from ``dimension`` method ?

**Comment by ibaned** [comment]
@kyungjoo-kim we need to discuss this as part of a larger discussion on Intrepid2. There are issues in Kokkos (this one, #1036) where the answer is "we do something weird because Intrepid2 wants it". I think some re-design of Intrepid2 would allow Kokkos to present the correct interface to the rest of its users, and it would also make Intrepid2 faster.

**Comment by kyungjoo-kim** [comment]
@ibaned 

The reason that the feature first introduced is not because Intrepid2 wants it. The feature exists before Intrepid2 exploits it. When I redesign Intrepid2, the feature I request is that subview allows extra Kokkos::ALL. If the view rank is smaller than the dimension of the specified range, it ignores the extra range argument. For instance, 
```
View<double**> A("A", m, n);
auto a = subview(A, 1, ALL(), ALL(); // this is okay
for (int i=0;i<a.dimension_0();++i) // iterate upto n
  for (int j=0;j<a.dimension_1();++j)  // iterate upto 1
    do_matrix_operation_with a(i,j); 
```
So, rolling back the interface that returns 0 extent when a user requests a dimension higher than the view rank may cause more broad issue (this is not limited to Trilinos but also other applications outside). 

Conceptually, a ``View A(m,n,1,1,1)`` is same as ``View A(m,n)``. it has the same span. Thus, I think that there is no logical problem in providing those extra unit dimensions.
 
Performancewise, having extra dimension arguments does not hurt performance as view mapping interface reduces the number of dimension arguments upto the rank size and it computes data location using the reduced dimension arguements.  

If C++ extent wants to return 0 for extra dimensions, it is okay and Intrepid2 does not use extent. However, it is necessary to keep the dimension method to return 1 for extra dimension ranks.

**Comment by ndellingwood** [comment]
> When I redesign Intrepid2, the feature I request is that subview allows extra Kokkos::ALL

This was for the `DynRankView`, but I don't think a static `View` supports this behavior.

**Comment by kyungjoo-kim** [comment]
@ndellingwood You are right. Static view wants to match the same number of arguments as the rank.
```
template< class D, class ... P , class ... Args >                                                             
KOKKOS_INLINE_FUNCTION                                                                                        
typename Kokkos::Impl::ViewMapping                                                                            
  < void /* deduce subview type from source view traits */                                                    
  , ViewTraits< D , P... >                                                                                    
  , Args ...                                                                                                  
  >::type                                                                                                     
subview( const View< D, P... > & src , Args ... args )                                                        
{                                                                                                             
  static_assert( View< D , P... >::Rank == sizeof...(Args) ,                                                  
    "subview requires one argument for each source View rank" );                                              
                                                                                                              
  return typename                                                                                             
    Kokkos::Impl::ViewMapping                                                                                 
      < void /* deduce subview type from source view traits */                                                
      , ViewTraits< D , P ... >                                                                               
      , Args ... >::type( src , args ... );                                                                   
} 
```

**Comment by ibaned** [comment]
This is causing serious difficulties with our ability to do basic sanity checking on API usage (#1263 and #1036). We should meet to discuss the trade-offs of this design.

**Comment by ibaned** [comment]
@kyungjoo-kim thats okay, I'm setting up a meeting for Wednesday, I think we should have more people there.

**Comment by ibaned** [comment]
At our meeting we decided not to alter `extent`, but we will be changing `operator()` and constructors to check the number of arguments.
