### ISSUE TITLE
Kokkos should include contribution acknowledgements for non-core developers

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#1300]
When a non-core developer contributes to an open source code, it is good practice to somehow acknowledge this contribution. For example, see http://lammps.sandia.gov/authors.html and https://github.com/lammps/lammps/blob/master/src/KOKKOS/pair_table_kokkos.cpp#L15. Yes there are the git commit logs, but I doubt normal users ever look at these. Acknowledging contributions from non-core developers encourages more contributions, which will benefit Kokkos in the long run.

**Comment by stanmoore1** [comment]
It would also be good to acknowledge users (by name/affiliation) who find and report bugs in Kokkos. For example in LAMMPS, see http://lammps.sandia.gov/bug.html:
`Bug fix to pair_style morse/smooth/linear to make it continuous at the cutoff. Thanks to Jian Luo (Corning).`
. This could be recorded in CHANGELOG.md when a new master promotion happens.

**Comment by crtrott** [comment]
Regarding the author list I think this https://github.com/kokkos/kokkos/graphs/contributors should do the job. I don't think that there is a more visible place than that, since there is no Kokkos webpage and our github presence is the main thing. If somebody wants to know who contributed I feel that is the first place they would look for github project. Recording reporters of bugs in the CHANGELOG is a good idea, though this thing is pretty much automatically generated now. Maybe we can change the title of a reported bug to include the reporter.

**Comment by stanmoore1** [comment]
@crtrott that is a good point about the author list, I hadn't considered that.

**Comment by ibaned** [comment]
I'm going to assume the GitHub contributor list is our answer for now. Please comment otherwise.
