### ISSUE TITLE
No kokkos-hwloc module with sems-intel module

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#1323]
Got this while running `test_all_sandia --spot-check` on `kokkos-dev`:
```
Loading module sems-env
Loading module kokkos-env
Loading module sems-intel/17.0.1
Loading module kokkos-hwloc/1.10.1/base
	ERROR loading module kokkos-hwloc/1.10.1/base
	Module points to path  /projects/sems/install/rhel6-x86_64/kokkos/tpl/hwloc/1.10.1/intel/17.0.1/base  which does not exist
	You may need to load the appropriate compilers before loading this module
  FAILED intel-17.0.1-OpenMP-release
```

**Comment by ndellingwood** [comment]
I put in a PR for a similar issue in kokkos/kokkos-kernels#207. In that case, for the sems-env, I switched the adding modules to the BASE_MODULE_LIST so that hwloc came before the sems compiler. @crtrott is this the right thing to do, or is this a module issue? If this is the right thing I'll put in a duplicate PR to Kokkos.

**Comment by ndellingwood** [comment]
@ibaned it looks like you already fixed this (1/5/2018) by moving hwloc before the sems-compiler in the BASE_MODULE_LIST variable.

**Comment by ibaned** [comment]
Thanks @ndellingwood ! I remember something like this...
