### ISSUE TITLE
OpenMP, target_link_libraries and CMake

### ISSUE THREAD

**Issue by pkestene** [kokkos/kokkos#1405]
@ibaned 
In a recent modification (commit  e0f7be1) I noticed the way kokkos libraries link is specified in cmake/kokkos_build.cmake has changed, but I think it introduced a problem : openmp linking flags are missing.

Indeed, in the previous version of the file, KOKKOS_LD_FLAGS was used in the TARGET_LINK_LIBRARIES for kokkos library
but it is replaced by a foreach loop over KOKKOS_TPL_LIBRARY_NAMES to specify the link, but this variable missed the oenmp linking flag.

This can be cross-checked just by build example/cmake_build (by the way, could this simple example be part of your CI test ?)

One solution could be to just add variable KOKKOS_INTERNAL_OPENMP_FLAG to enrich the target_link_libraries of kokkos libs in cmake/kokkos_build.cmake

**Comment by crtrott** [comment]
Good catch thanks.

**Comment by ibaned** [comment]
Yea, I did that because I don't want `-lfoo` flags in `target_link_libraries`, that is actual libraries should be handled via `find_library`. However `KOKKOS_LD_FLAGS` has other stuff mixed in there like `-fopenmp` and `-arch=sm_XX` for CUDA. I guess I'll add another variable to separate out non-library flags from flags. Also... I think CMake always adds the `CXX_FLAGS` to the link command, so maybe these should actually be added to the target's `COMPILE_FLAGS` property and not the link libraries.

**Comment by pkestene** [comment]
I tried to provided a fix, I hope you don't mind.
It does not involve COMPILE_FLAGS, I just created an extra KOKKOS_LINK_FLAGS variables, that is passed to target_link_libraries, because it's easy to have these flags transitively transfered to the actual application executable linking.
