### ISSUE TITLE
kokkos profiling capability for task-dag. 

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#1407]
Hello,

I know that there are missing parts in profiling for task-dags. Would you please add/complete the profiling capability for task-dag ?

**Comment by ibaned** [comment]
This needs to be made more precise. its not clear what capability is needed.

**Comment by kyungjoo-kim** [comment]
overhead (task queueing and dequeueing) measurement against total effective work load (time consumed by task functor operators).

**Comment by ibaned** [comment]
Hmm... that sounds difficult to measure (without introducing more overhead). Do you have a method in mind for measuring overhead?

**Comment by nmhamster** [comment]
We need to think a little about this because the profiling hooks may introduce quite significant overhead if we leave them compiled in all the time.

**Comment by nmhamster** [comment]
Would sampling some tasks be sufficient (assumes you are firing many similar tasks)?

**Comment by ibaned** [comment]
I get the sense that in @kyungjoo-kim 's application, tasks have widely varying amounts of work. In theory though a large enough sample, appropriately chosen with uniform random distribution, should represent the whole, but its unclear if this will yield information accurate enough to be useful.

Just be concrete about what I think is being proposed: for each sampled task, time it from start to finish (note that even start-to-finish is tricky, because tasks can wait for others and respawn themselves). Then come up with some notion of total "core"-seconds spent on the whole DAG, and subtract the extrapolated "user work" time derived from sampling?

**Comment by ndellingwood** [comment]
Adding @dhollman in case this may relate to work he's done with the tasking backend.

**Comment by DavidPoliakoff** [comment]
@kyungjoo-kim , this is interesting. I'll try to bring this up with the team again. I'm not in principle opposed to Profiling support for task-dags, though I think the discussion from when you first brought this up raises valid concerns, the obvious implementations I have for this would perturb execution to the point of uselessness

**Comment by crtrott** [comment]
I don't think its possible to do that in a meaningful manner. Enabling full profiling via callbacks or time measurements will increase the overhead of the task scheduler significantly while simultaneously changing its instructon/miss cache behavior significantly and thus not give you meaningful information. Sampling tools are likely the best bet.
