### ISSUE TITLE
Race condition in Views of Views

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#1530]
I found a race condition when using views of views, see https://github.com/kokkos/kokkos-tools/issues/34. It shows up as a write data race condition in Intel Inspector and is caused by two threads writing to `Kokkos_SharedAlloc.cpp:224` without proper synchronization. Can this be fixed? If views of views are considered unsupported this should be clarified with errors in the code and updating the documentation.

**Comment by ibaned** [comment]
1. I think that race condition is a false positive, Intel Inspector can't fully reason about the linked list algorithm and its guarantees. That bit of code is thread-safe.

2. In Kokkos develop, this code is disabled unless `KOKKOS_DEBUG` is on, because it doesn't serve much purpose other than being a point of contention.

3. Views that directly or indirectly contain Views are still supported, but with the requirement that users force deallocation in serial. This is done by coding a serial for loop over the host-side copies of these views and assigning them to default-constructed Views, something like:

```cpp
for (int i = 0; i < n; ++i) {
  k_LR.h_view(i).d_Y = decltype(k_LR.h_view(i).d_Y)();
}
```

This forces the deallocations to take place in serial which is better for application performance and avoids race conditions in external tools like the profiling tool.

**Comment by stanmoore1** [comment]
@ibaned can you explain your second point? I'm not following. Are you saying that this code has been changed in the develop vs master branch?

**Comment by ibaned** [comment]
Yea, that particular piece of code is keeping track of a linked list of all allocations. We don't really need to do that, its only useful to show users "leaked" allocations at the end of a Kokkos program, so we've `#ifdef`'ed it out if `KOKKOS_DEBUG` is off. The code inside that `#ifdef` hasn't changed though, and should be correct and thread-safe in both master and develop.

**Comment by stanmoore1** [comment]
I just checked and deallocating the views of views in serial prevents the race condition on the profiling tools.

**Comment by ibaned** [comment]
I just documented this in the Wiki

**Comment by stanmoore1** [comment]
@ibaned thanks!
