### ISSUE TITLE
Incorporating Makefile.kokkos into codebase that uses cmake

### ISSUE THREAD

**Issue by dholladay00** [kokkos/kokkos#155]
I am attempting to incorporate kokkos into an existing codebase that uses cmake as its build system. It is probably my lack of cmake knowledge, but I cannot find a way to specify to cmake to include the Makefile.kokkos into the makefile that it generates. Am I missing something there? 

Are there codes (I feel trilinos might be an exception here) that use kokkos and cmake? If so, how did they deal with this?

I could make a .cmake file that would be the equivalent, but I am guessing that there is a better way to do this. This method has disadvantages besides being tedious, namely that changes to the Makefile.kokkos would not automatically propagate to the .cmake file.

**Comment by crtrott** [comment]
There is unfortunately not raw cmake support from our side at the moment. The Makefile.kokkos is meant mostly for gnu make based build systems, and our cmake files are indeed the ones from Trilinos which use Tribits. There are two options here: 

(i) Install kokkos as a library and include it as any other TPL. The downside of that is you need to make sure the options match (i.e. OpenMP is enabled in both, compilers are the same etc.), the upside is that it should be fairly straight forward to do. 
(ii) Write your own cmake files. Mostly they need to replicate what the Makefile.kokkos does, i.e. you need to include the right source files depending on the options you enable and you need to generate the KokkosCore_config.h file which reflect those options. Again if you know cmake well this shouldn't be particularly hard and there might be people who have done that. The downside is that the integration process of Kokkos is more complicated since you need to replace our cmake files all the time, and you don't get new options automatically.
(iii) Help us modify the existing CMake files to work with both tribits and standalone. This option might be the most attractive long term, but probably also requires the most work. Mostly this entails to write some functions which replicate functionality from tribits but they must detect whether or not it operates in a tribits environment or not. 

Let me know what you think.

**Comment by wohlbier** [comment]
It seems like another option is to make our project a TriBITS project. I've looked at TriBITS some and it seems reasonable for our fairly simple project structure. What do you think Christian?

**Comment by nmhamster** [comment]
I /really/ would like to be functional with "standard" tools that are simple and easy to use. Kokkos operates outside of Trilinos in many cases. Please can we ensure we continue to support people who use it this way.

S



Si Hammond

Scalable Computer Architectures
Center for Computing Research
Sandia National Laboratories, NM, USA
[Sent from Good, please excuse typos]
________________________________

**Comment by crtrott** [comment]
Si this is not a question of continue to support, right now we do not have inbuild plain CMake files. And yes making your project a tribits project would be an option, in which case it simply would work as is (i.e. you snapshot kokkos into your project and make it a package. 

With regards to plain CMake files, so far it was not important enough for anybody to put it high on our priority list, while easy integration into Trilinos is. That doesn't mean we wouldn't like to see interoperability though.

**Comment by wohlbier** [comment]
Thanks for the comments guys. I think for now we are going to treat it as a TPL and maintain the needed installations, which should only be 2 for now, I think. The TriBITS option seems attractive at first, but when I think of the app codes that will use our library I see headaches down the road. It took over a year for our main targeted app code to accept plain CMake projects, and I'm not keen to throw TriBITS on top of that.

**Comment by nmhamster** [comment]
Christian, I think we should work on the general CMake support over TriBITS don't you think? Won't that make it more useful to a wider group of users?

**Comment by crtrott** [comment]
Totally. Did you just volunteer ? ;-)

**Comment by nmhamster** [comment]
If it means we get to reach more users yes. You know my general feelings on CMake and the Trilinos build system but I can't see Kokkos independent of Trilinos working unless we do this. If you let me use auto tools it would be done by now ;-).

**Comment by crtrott** [comment]
Would auto tools work in a cmake project, and would it work with Trilinos? 
We talked about this with Ross and Brent before, in principal it should be possible to write hybrid CMake files which work both within Trilinos (i.e. tribits) and with plain cmake. We just didn't have it high enough on our priority list yet.

**Comment by nmhamster** [comment]
No auto tools wouldn't, plus I think in principle the Trilinos folks are against auto tools after the nastiness it resulting in previous years. The real push here is for plain CMake and that's what we should do first. I'll put it into the to-do queue after all the atomics stuff :-)!

**Comment by crtrott** [comment]
I made this an official Feature Request, and put it for now into the backlog. We might add it to the preGTC Milestone. Maybe Jim Foucar could also help/do this.

**Comment by jgfouca** [comment]
Assigned myself.

**Comment by crtrott** [comment]
Great, than I just add that to GTC 2016 milestone.

**Comment by mhoemmen** [comment]
Si, if it helps, I have no strong feelings about the GNU Autotools.  Then again, I haven't worked much with them.  I just need Kokkos to work with TriBITS so that it works in Trilinos, and Christian needs it to work with plain Makefiles for LAMMPS.  I'm totally OK with Kokkos supporting other build systems.

**Comment by rppawlo** [comment]
We have a few codes in CASL that support both raw cmake and TriBITS builds.  If you are interested, I can put you in contact with those teams to see how they did it.

**Comment by dholladay00** [comment]
I noticed that recent commit made mention of standalone cmake scripts. Is standalone cmake support coming in the near future, or was that commit unrelated to this issue? 

I naively attempted an out of source build (`cmake ..` + `ccmake .`) but got errors.

**Comment by dholladay00** [comment]
I have been working on this off and on and I have something that works with caveats. 

- if you want use the CUDA backend, you need to run cmake: `CXX=/path/to/nvcc_wrapper cmake /path/to/kokkos`
- I have not tried to build from Trilinos, but everything is blocked with a `IF(NOT KOKKOS_HAS_TRILINOS)`, so it has a chance of working. 
  - Some changes were made to tribits.cmake due to issues with interface libraries if I recall (thanks to @KineticTheory) so that be an issue when it comes to tribits interop. 
- It's hacky, but if someone who knows more about tribits is willing to help, I bet it wouldn't take long clean it up and make it better. 
- Tests, examples, other things don't build by default, that could due to an option that is not visible from ccmake (which is how I was selecting options)
- It does not build `libkokkos.a` but rather `libkokkos[core,algorithms,containers,etc].a`, not sure what combination of those is the equivalent to `libkokkos.a`

If anyone else is also working on this, it might be wise to combine knowledge rather than have 2 independent efforts going.

**Comment by bartlettroscoe** [comment]
I offered to put together a transparent CMake build for Kokkos over a year ago but was told that there was no interest in doing so.  If people are interested in doing so in a way that is maintainable, I can provide a solution in a few hours that fully supports all TriBITS Core features including:

1. building and installing libs
2. building and running all examples and tests with ctest
3. Automatically generating and installing KokkosConfig.cmake and Makefile.export.Kokkos files (and the files for Kokkos subpackages).
4. Selecting what subset (i.e. subpackages) of Kokkos to enable, build, test, and install.

I have already done this for Teuchos (with the future application of snaphsotting Teuchos out of Trilinos as its own CMake repo) and this is what many other projects that use TriBITS use (mostly in CASL).

This would either require users to download and TriBITS first and then point to it when configuring Kokkos, or you could just snapshot tribits/core/ into Kokkos.

If you snapshot tribits/core you allow the simple process:

```
$ git clone https://github.com/kokkos/kokkos.git
$ cd kokkos/
$ mkdir BUILD
$ cd BUILD/
$ cmake -DCMAKE_INSTALL_PREFIX=<prefix> ..
$ make -j16 install
```

This could either build tests and examples by default or not.  The choice is up to Kokkos developers.

Snaphotting tribits/core/ would increase the size of the kokkos source tree from 7.8M to 9.0M but that would eliminate maintenance costs of supporting a native CMake build for Kokkos.

If you are interested in this, let me know.  It is not a lot of work and it will be maximally maintainable and something that I can help support.

**Comment by dholladay00** [comment]
I am definitely interested. For my case (can't speak for others), that increase in size would not be an issue (it's definitely preferable over making Trilinos a project dependency). 

I also know that other work was done along these lines through #284. I am not sure how compatible these 2 routes are. Either way, the choice is up to the Kokkos team.

**Comment by bartlettroscoe** [comment]
> I am definitely interested. For my case (can't speak for others), that increase in size would not be an issue (it's definitely preferable over making Trilinos a project dependency).

Just need to be given the okay and I will get it done.

> I also know that other work was done along these lines through #284. I am not sure how compatible these 2 routes are. Either way, the choice is up to the Kokkos team.

I had never seen #284 but I would say to just revert all of that once there is a clean stand-alone TriBITS build of Kokkos.  Why maintain two CMake build systems?

**Comment by bartlettroscoe** [comment]
Sorry, meant to add this comment to this Issue ticket, not PR #339.

I just heard in the Kokkos meeting today that the driver for this was to pull Kokkos into a larger CMake project using `add_subdirectory(kokkos)`.   If you want to build Kokkos direclty under a larger CMake project, I would **not** recommend trying to just use `add_subdirectory(kokkos)`.  Kitware used to recommend that approach for combining projects but in practice that turns out to be very difficult to maintain.  All it takes is just a minor difference in the way that that two CMake projects use CMake and then all of the sudden, they are incompatible.  For example, that is what we tried to do for years with Trilinos and Dakota using the TriKota package.  That became very difficult to maintain so we stopped doing that.  That is one reason why TriBITS came into existence in the first place; to provide a framework to ensure that different projects used CMake in a consistent way so the could be built separately or together.

So in recent years, Kitware has been pushing CMake ExternalProject as a way to pull together different CMake projects into a larger CMake project (which Kitware calls a "Super Build").  See:

http://www.kitware.com/media/html/BuildingExternalProjectsWithCMake2.8.html
https://cmake.org/cmake/help/v3.0/module/ExternalProject.html

But if all you want to do is to build Kokkos under a larger CMake project, I would just create custom targets to configure and build Kokkos as an independent CMake project and then just suck in the KokkosConfig.cmake file that gets generated by the Kokkos CMake build.  That is exactly what we do now to build Dakota (that does not use TriBITS) under the CASL VERA project (that uses TriBITS).  That has eliminated the problems trying to keep the `add_subdirectory(Dakota)` approach working.  We could even provide some support in TriBITS for that use case to make it easy and pretty seamless if there was interest.

I can provide a larger example of how to do this if interested.  It is not quite slick as a single CMake project for supporting co-development, but it gets the job done seamlessly for people who just want to configure, build and install your parent CMake project.  And most importantly, this approach it is maintainable!  That would be option-2 after using TriBITS for everything (which provides the most semeless co-development build system).

**Comment by dholladay00** [comment]
The goal for me is definitely to incorporate Kokkos as an external cmake project. This would allow me to build Kokkos with different compilers, optimization levels and backends based the project build type rather than having to prebuild every combination.

Thus, the goal for me is to be able to build Kokkos as an external project and base the kokkos build options from the build options of my project. I do not have a strong opinion of how this is achieved and I would be willing to help in whatever way that I can, but maintainability and simplicity are high on my list.

Building as an external project could probably be done using the generate makefile script, but I think it would be more straightforward and easier to do if it built with cmake. 

I think my confusion was 2-fold.
1. It was recommended to not use the currently embedded cmake, but rather use Makefile.kokkos
2. Doing a simple out of source cmake build would fail to even configure, much less build.

**Comment by pfultz2** [comment]
> I had never seen #284 but I would say to just revert all of that once there is a clean stand-alone TriBITS build of Kokkos. Why maintain two CMake build systems?

Actually, #284 is not a entire separate build system. It just provide a lightweight standalone implementation of the tribits cmake functions. There was no changes to main cmake files except to include the `tribits.cmake` file for when it is standalone. 

Most of the functionality was taken directly from tribits but was trimmed down by removing functionality not used by kokkos, and utilizing more builtin cmake functionality. It was an initial implementation of standalone cmake and so there is still room for improvement.

One area where it does diverge from tribits is bringing in the TPL dependencies. There is a separate directory called `deps` that search for the TPL dependencies. They are almost identical to whats in the `tpl` directory except they do not produce a fatal error. A fatal error seems impossible to recover from(which is needed for optional dependencies). It would be nice if these two folders could converge.

**Comment by bartlettroscoe** [comment]
> Actually, #284 is not a entire separate build system. It just provide a lightweight standalone implementation of the tribits cmake functions. There was no changes to main cmake files except to include the tribits.cmake file for when it is standalone.

Right, of course.  But TriBITS Core is not really a build system either.  It is just a architecture/framework for managing (large) componentized CMake-based packages and projects.   And for that matter, CMake is not really a build system either.  CMake is technically just a meta-build system since CMake does not compile a single line of source code.  CMake is just a meta-language or DSL for expressing a build of software that is translated into the real underling "generated" build system files; i.e. Makefiles, or Ninja files, or NMake files, or Visual Studio project files, or Eclipse project files, (soon to be) Google basel files, etc.

> Most of the functionality was taken directly from tribits but was trimmed down by removing functionality not used by kokkos, and utilizing more builtin cmake functionality. It was an initial implementation of standalone cmake and so there is still room for improvement.

Right, but now you have a maintenance problem.  Now someone has to maintain tribits.cmake and everything that goes with that.  Why would you want to do that?  That is like saying you are going to re-implement parts of Kokkos for only your specific use cases.  Why would you do that?  Or like saying that you don't need all of the functionality of the Linux OS so you will duplicate only the functionality that you currently need.  Why would you do that?

> One area where it does diverge from tribits is bringing in the TPL dependencies. There is a separate directory called deps that search for the TPL dependencies. They are almost identical to whats in the tpl directory except they do not produce a fatal error. A fatal error seems impossible to recover from(which is needed for optional dependencies). It would be nice if these two folders could converge.

What do you mean by this?  Note that TriBITS supports the concept of "tentative" TPL enables where if it can't find the TPL, then the TPL gets disabled.  See [https://tribits.org/doc/TribitsDevelopersGuide.html#how-to-tentatively-enable-a-tpl How to tentatively enabled a TPL].  Is that what you mean?

In the next comment, I will describe what use case that a true stand-alone TriBiTS build of Kokkos would provide (that this tribits.cmake module does not).

**Comment by bartlettroscoe** [comment]
Responding to @dholladay00 from [above comment](https://github.com/kokkos/kokkos/issues/155#issuecomment-229428423):

> Thus, the goal for me is to be able to build Kokkos as an external project and base the kokkos build options from the build options of my project. I do not have a strong opinion of how this is achieved and I would be willing to help in whatever way that I can, but maintainability and simplicity are high on my list.

What you are suggesting is possible and I can provide some details on how you can do this.  But all things considered, that may not be the best option/approach.

Instead, let me suggest an inverted dependency where you build and (optionally) install Kokkos as its own CMake project first and then have your downstream CMake project use `find_package(Kokkos)` to pull in all of the necessary info about Kokkos through the KokkosConfig.cmake file that TriBITS automatically generates.  That is the way that Kitware intends `<Package>Config.cmake` files to work and that CMake ExternalProject drives things and how [Google Catkin](http://wiki.ros.org/catkin/conceptual_overview) works, etc.  (I don't know anyone who is an expert in CMake who would recommend using `add_subdirectory(<external_project>)` these days to pull in an external project to build your project.  The only reason that TriBITS gets away with this is because it enforces consistency across independent CMake-based projects/packages.)

An example of the KokkosConfig.cmake file that gets generated by TriBITS in the build directory (which allows you to skip an install and just point into the build tree) is shown [here](https://github.com/kokkos/kokkos/files/340334/KokkosConfig.cmake.txt).  As you can see, you can grab the libraries, the include dirs, the compilers, the compiler flags, the include dirs and libs for the TPLs, etc.    

To demonstrate, assuming you organize your source and build directories like:

```
<base-project>/  # local git repo for your project
    kokkos/     # cloned from github
   BUILD/       # Build dir for your project
       kokkos /  # build dir for Kokkos
```

you could do your configure/build/test of your project like:

```
# Configure/build/test Kokkos
$ cd <base-project>/BUILD/kokkos/
$ cmake [optional configure args for Kokkos] ../../kokkos
$ make -j16
$ ctest -j16  # if you want to run the native Kokkos tests

# Configure/build/test your project
$ cd ..
$ cmake -DCMAKE_PREFIX_PATH=kokkos ..
$ make -j16
$ ctest -j16  # run your project's tests
```

Above, you don't need to specify any compilers, compiler options, etc. for your downstream project because they get pulled out of the KokkosConfig.cmake file.

What I describe above is **exactly** the way that Albany uses and piggy-backs off of the TriBITS/CMake build of Trilinos (see [here](https://github.com/gahansen/Albany/wiki/Simple-Albany-Configuration)).  But the big difference is that you don't need to 50+ enables/disables because Kokkos is the only thing that can be enabled.  (But if you wanted only a subset of Kokkos, you could ask for just that, e.g. `-DKokkos_ENABLE_Kokkos="" -DKokkos_ENABLE_KokkosCore=ON`.)

Note that you could also install Kokkos and then point to the installed KokkosConfig.cmake file if you would like.  It is up to you.

Is that an acceptable development workflow?  If it is, that is what a clean TriBITS/CMake build of Kokkos allows you do to (with very little extra to be maintained).

The only software that I know of that allows you to compose a large CMake project out of independent pieces in a scalable way is TriBITS.  Trilinos itself and CASL VERA are proof of this.  The next closest thing to TriBITS that I know of is [VTK modules](http://www.vtk.org/Wiki/VTK/Module_Development) but that system don't support optional dependencies or many other use cases supported by TriBITS.

But note that if someone really wants to support a stripped-down tribits.cmake module, then Kokkos could support that as well along with a true stand-alone TriBITS CMake build.  You would just need a single CMake cache variable and an extra if() statement in kokkos/CMakeLists.txt to switch back and forth.  Someone would just have to decide what the default CMake build for stand-alone Kokkos would be (i.e. true TriBITS with compatible behavior with the Trilinos-based configure/build of Kokkos or mock TriBITS through the stripped down tribits.cmake module).  If you decide to keep tribits.cmake, then it should be called something like TriBITSLite.cmake or something to distinguish it from true TriBItS.

Let me know if anyone has questions about any of this.  Otherwise, there is not much more to say about this topic.

**Comment by pfultz2** [comment]
> Right, but now you have a maintenance problem. Now someone has to maintain tribits.cmake and everything that goes with that. Why would you want to do that? That is like saying you are going to re-implement parts of Kokkos for only your specific use cases. Why would you do that? Or like saying that you don't need all of the functionality of the Linux OS so you will duplicate only the functionality that you currently need. Why would you do that?

Or like saying that glibc is too heavyweight so I will use musl or UClibc instead. However, I agree with your point. I think the best option would be to separate trilinos into separate package so the components can be installed individually, and then kokkos could just write `find_package(tribits)` at the top. I tried something like that at first by installing trilinos without kokkos and then trying to build kokkos, but it didn't work as the tribits components are never installed with trilinos.

> What do you mean by this? Note that TriBITS supports the concept of "tentative" TPL enables where if it can't find the TPL, then the TPL gets disabled. See [https://tribits.org/doc/TribitsDevelopersGuide.html#how-to-tentatively-enable-a-tpl How to tentatively enabled a TPL]. Is that what you mean?

So it seems I wrote it to treat each tpl as tentative in kokkos even though it doesn't call `TRIBITS_TPL_TENTATIVELY_ENABLE`.  Otherwise, the user would have to explicitly enable each optional dependency. Perhaps that is how it is in trilinos, but that is not how the makefiles seem to work, which is probably why I chose that. To avoid the duplication of the `deps` directory, it might be better to follow trilinos and make optional dependencies explicit instead.

**Comment by bartlettroscoe** [comment]
Responding to @pfultz2 from [above comment](https://github.com/kokkos/kokkos/issues/155#issuecomment-229518899):

> Or like saying that glibc is too heavyweight so I will use musl or UClibc instead. However, I agree with your point.

I think the point is that if glibc blows up or does not work for your platform, or fails in some other way, or just does not do what you want, then it is nice to have an alternative.  I agree with that.  But in general, you don't create an alternative until you find yourself between a rock and a hard place.  Otherwise, why would you bother?  What is "the rock" and what is "the hard place" in the analogy with Kokkos and TriBITS at the current time?

> I think the best option would be to separate trilinos into separate package so the components can be installed individually, and then kokkos could just write find_package(tribits) at the top. I tried something like that at first by installing trilinos without kokkos and then trying to build kokkos, but it didn't work as the tribits components are never installed with trilinos.

Actually, starting with Trilinos 12.6, TriBITS does actually get installed as part of Trilinos by default.  See an example of how this gets used in [xSDKTrilinos](https://github.com/trilinos/xSDKTrilinos/blob/master/CMakeLists.txt#L64) (which can be built as a Trilinos package or as an independent CMake project downstream from PETSc and Trilinos, which is required for the [xSDK](http://installxsdk.readthedocs.io/en/latest/README/index.html)).

As for (optionally) building Trilinos in pieces, various use cases like that and more will be supported in TriBITS in an upcoming refactoring (see TriBITSPub/TriBITS#63 and the google doc it links to).

**Comment by dholladay00** [comment]
Responding to @bartlettroscoe from [above comment](https://github.com/kokkos/kokkos/issues/155#issuecomment-229518475):

It sounds like you are saying to put Kokkos in my repository, perhaps even as a submodule. This sounds okay to me. If I want a particular build of my project (for example: intel 16.0.1, Cuda backend, with cublas lapack/blas, max optimization), would I have to go make a build of kokkos with those options or would the kokkos libs be built within my project build (inheriting the same properties)?

**Comment by bartlettroscoe** [comment]
Responding to @dholladay00:
> It sounds like you are saying to put Kokkos in my repository, perhaps even as a submodule. This sounds okay to me.

You don't have to mess with git submodules.  Just do this:

```
$ cd <base-project>/
$ git clone git@github.com:kokkos/kokkos.git
$ cat /kokkos/ >> .git/info/exclude
```
Then you can push and pull to each repo independently.  Do whatever you want with the placement of your source trees (I just gave an example so I could shown concrete commands).  That has no impact on how you build.

> If I want a particular build of my project (for example: intel 16.0.1, Cuda backend, with cublas lapack/blas, max optimization), would I have to go make a build of kokkos with those options?

Yes. 

What is proposed [above](https://github.com/kokkos/kokkos/issues/155#issuecomment-229518475) is to specify "intel 16.0.1, Cuda backend, with cublas lapack/blas, max optimization", etc. for the configure of Kokkos and then suck in all of that info automatically when you configure your downstream project when it pulls in KokkosConfig.cmake.  You don't need to specify that twice.

> would the kokkos libs be built within my project build (inheriting the same properties)?

No.

But while that is possible, it is more complex and has other disadvantages.  Using TriBITS for your outer project would allow you to do to that seamlessly.  (But until there is more tutorial material and user proofing of TriBITS, I would not recommend that to external projects at this time.)

Make sense?  If not, perhaps we should take talk over the phone or Skype really quick or something.

**Comment by dholladay00** [comment]
That makes sense, though a telecon might not be a bad idea is it is still not fully clear how this is preferable to making Kokkos an external cmake project.

**Comment by bartlettroscoe** [comment]
>  [...] it is still not fully clear how this is preferable to making Kokkos an external cmake project.

Specifically what does "making Kokkos an external cmake project" mean?  Does it mean `add_subdirectory(kokkos)`?  If that is what you mean, please see the long paragraph in the [above comment](https://github.com/kokkos/kokkos/issues/155#issuecomment-229419436) starting with "I just heard in the Kokkos meeting today that the driver for this was to pull Kokkos into a larger CMake project using add_subdirectory(kokkos)."  Otherwise, all of the pros and cos for these various approaches are given above.

> a telecon might not be a bad idea

I think such a telecon likely needs to involve the key Kokkos developers and @pfultz2 to discuss the issues.

**Comment by dholladay00** [comment]
It means `ExternalProject_Add(Kokkos CMAKE_ARGS "build specific Kokkos args ...")` such that the "build specific Kokkos args ..." can be based upon the cmake arguments used to build my stuff. For example, we have a KOKKOS_BACKEND variable that needs to be specified such that if we want the CUDA backend, we know to use cublas for the linear algebra lib rather than mkl or lapack. But that could extend to other things such as optimization level, debug, compiler type, etc.

**Comment by bartlettroscoe** [comment]
> It means `ExternalProject_Add(Kokkos CMAKE_ARGS "build specific Kokkos args ...")` such that the "build specific Kokkos args ..." can be based upon the cmake arguments used to build my stuff. 

Thanks for clarifying.  If that setup works for you and you are happy with that, then that is just fine.  But note that as Kokkos adds now configure options, you will need to add those same configure options to your output project and then pass them through to the Kokkos configure.  The advantage of configuring Kokkos first and then pulling in KokkosConfig.cmake is that will remove the need to forward these configure options on the Kokkos configure.

Using true TriBITS for Kokkos should support that use case just fine since you are treating Kokkos as an independent CMake build.  Would you project like to be pulling in KokkosConfig.cmake after the configure of Kokkos is completed?  If you Kokkos uses true TriBITS for its CMake build, that file will get created automatically so you can do:

```
ExternalProject_Add(Kokkos CMAKE_ARGS "build specific Kokkos args ...") 
find_package(Kokkos REQUIRED ...)
```

then your project can read the include dirs and libs out of `Kokkos_INCLUDE_DIRS` and `Kokkos_LIBRARIES` and the extra CXX flags from `Kokkos_CXX_FLAGS` (which will include how to enable C++11 support for your compiler).

So if no one is trying to do `add_subdirectory(kokkos)` there is there any remaining technical reason not to snapshot TriBITS Core (1.2M in size) into Kokkos and then use that for the CMake build of Kokkos?  It just means less to maintain for everyone's sake.

**Comment by dholladay00** [comment]
> then your project can read the include dirs and libs out of `Kokkos_INCLUDE_DIRS` and `Kokkos_LIBRARIES` and the extra CXX flags from `Kokkos_CXX_FLAGS` (which will include how to enable C++11 support for your compiler)

That could have further benefits as I would be able to pull in architecture specific optimization flags that Kokkos uses, which is a benefit all on its own. 

> So if no one is trying to do `add_subdirectory(kokkos)` there is there any remaining technical reason not to snapshot TriBITS Core (1.2M in size) into Kokkos and then use that for the CMake build of Kokkos? It just means less to maintain for everyone's sake.

@crtrott, care to weigh in on this, or perhaps a telecon as was suggested [above](https://github.com/kokkos/kokkos/issues/155#issuecomment-229767165) might be the way to go.

**Comment by hcedwar** [comment]
Need a better solution than patching together CMake and make files.
