### ISSUE TITLE
Polymorphic Classes causing invalid memory access when compiling for Cuda

### ISSUE THREAD

**Issue by shellshocked2003** [kokkos/kokkos#1591]
I using a polymorphic class that I've turned into a functor to use with MDRangePolicy, but I'm running into issues when I execute the application on the GPU.

> what():  cudaDeviceSynchronize() error( cudaErrorIllegalAddress): an illegal memory access was encountered

`cuda-memcheck` traces this back to `KokkosExp_Cuda_IterateTile_Refactor.hpp:209` and
and `KokkosExp_Cuda_IterateTile_Refactor.hpp:272`. In both cases, it's the call to the overloaded `operator()` that's causing the problem.

So, I'm wondering whether it's possible to use polymorphic classes that call Kokkos parallel operations?

**Comment by ibaned** [comment]
If the class is polymorphic, it likely has a virtual destructor, which CUDA will attempt to call at the end of the parallel operation, but since the object that was copied has the host-side `vtable`, this will fail. In general, try not t ouse polymorphic classes as functors because it is difficult. If there is no other way, then I can describe in more detail how to get a CUDA `vtable` set up properly.

**Comment by crtrott** [comment]
Btw. this is a restriction of CUDA itself not Kokkos in general.

**Comment by shellshocked2003** [comment]
@crtrott Got it, thanks. I was hoping Kokkos might take care of this behind the scenes.

@ibaned If you don't mind, some guidance on setting up a CUDA `vtable` would be very helpful. I don't see a sensible way to get round the polymorphism.

**Comment by mhoemmen** [comment]
@shellshocked2003 short answer is "instantiate the object on device only" then the vtable will be on device

slightly longer answer: use cudaMalloc to allocate sizeof(Thing) space, then placement new the object into that space on device.  you then become responsible for invoking the destructor explicitly & calling cudaFree on the memory.

**Comment by ibaned** [comment]
@shellshocked2003 as @mhoemmen said, the trick is to call the constructor of the object from inside the CUDA kernel (code that runs inside the parallel region). Since memory can't be allocated inside the CUDA kernel, you need a two-part approach where CUDA memory is first allocated outside the kernel, and then placement new
```cpp
new (ptr) Thing(/*constructor args...*/);
```
is called inside the kernel.
Since memory can't be deallocated inside the kernel, you call the destructor of the `Thing` from inside the kernel:
```cpp
ptr->~Thing();
```
And then deallocate the memory after the kernel.

**Comment by crtrott** [comment]
Considering the increasing number of people asking for this, I think we may want to think about providing some helper functions. One of the problems is that you can't just assign a host constructed thing to a device constructed thing since that would overwrite the vtable. 

To work around that we would probably need some "init" function as requirement on the objects. I was thinking of something like 
```c++
template<class T_parent, class T, class ExecSpace>
T_parent* create_virtual_object();

template<class T_parent, class T, class ExecSpace>
void destroy_virtual_object(T_parent* ptr);
```

**Comment by mhoemmen** [comment]
@crtrott Could it be possible to automate this, since C++ has `std::is_polymorphic`?  The issue is that Kokkos::View's constructor would then have to be more like std::vector's constructor and promise to emplace-construct everything....

**Comment by stanmoore1** [comment]
>Considering the increasing number of people asking for this, I think we may want to think about providing some helper functions. 

Yes, please. Working around this is a huge pain for me.

**Comment by shellshocked2003** [comment]
Thanks @ibaned and @mhoemmen for the guidance. I will give that a go.

@crtrott Some helper functions would be great!

**Comment by crtrott** [comment]
Hm maybe we can do that. But technically you already get the right behavior if all you want is an array of objects of type T which inherits some stuff from T_parent which has a function foo. 

I.e.:
```c++
#include<Kokkos_Core.hpp>

struct T_parent {
  KOKKOS_INLINE_FUNCTION
  void foo(int i) {
     bar(i);
  }
  KOKKOS_INLINE_FUNCTION
  virtual void bar(int i) {
    printf("Bar parent%i\n",i);
  }
};

struct T:T_parent {
  KOKKOS_INLINE_FUNCTION
  void bar(int i) {
    printf("Bar child, %i\n",i);
  };
};

int main(int argc, char* argv[]) {
  Kokkos::initialize(argc,argv);
  {
     int N = (argc>1) ? atoi(argv[1]) : 10000;
     int M = (argc>2) ? atoi(argv[2]) : 10000;
     int R = (argc>3) ? atoi(argv[3]) : 10;

     Kokkos::View<T*> a("A",N);
     Kokkos::parallel_for("PrintLoop",N, KOKKOS_LAMBDA(const int& i) {
       a(i).foo(i);
     });
  }
  Kokkos::finalize();
}
```
This works as expected and prints out "Bar child, 0" etc. .
But you can't do deep_copy between a host and device version since that overwrites the vtable. 

I.e. this code fails with runtime access error:
```c++
#include<Kokkos_Core.hpp>

struct T_parent {
  KOKKOS_INLINE_FUNCTION
  void foo(int i) {
     bar(i);
  }
  KOKKOS_INLINE_FUNCTION
  virtual void bar(int i) {
    printf("Bar parent%i\n",i);
  }
};

struct T:T_parent {
  KOKKOS_INLINE_FUNCTION
  void bar(int i) {
    printf("Bar child, %i\n",i);
  };
};

int main(int argc, char* argv[]) {
  Kokkos::initialize(argc,argv);
  {
     int N = (argc>1) ? atoi(argv[1]) : 10000;
     int M = (argc>2) ? atoi(argv[2]) : 10000;
     int R = (argc>3) ? atoi(argv[3]) : 10;

     Kokkos::View<T*> a("A",N);
     Kokkos::View<T*>::HostMirror h_a = Kokkos::create_mirror_view(a);
     Kokkos::deep_copy(a,h_a);
     Kokkos::parallel_for("PrintLoop",N, KOKKOS_LAMBDA(const int& i) {
       a(i).foo(i);
     });
  }
  Kokkos::finalize();
}
```

**Comment by shellshocked2003** [comment]
I'm not trying to create an array of objects, but instead an object of type T that inherits some stuff from T_parent and has several `Kokkos::View`s as inherited members. The object has several methods that invoke parallel operations on these `View`s. The parallel operations use function tags to call the correct `operator()`.

I'm a bit unsure how the object construction within parallel regions would actually manifest during execution. Would each block then create an instance of the object? Is that essentially what happens when passing a functor to a parallel operation?

**Comment by shellshocked2003** [comment]
This is more like what I'm trying to do:

```c++
class ViewClass {
 public:
   ViewClass(const Eigen::VectorXi& inputs);

   virtual ~ViewClass();

   void initialize();
  
   KOKKOS_FUNCTION
   virtual void operator()(const int &x_index,
                           const int &y_index,
                           const int &z_index) const = 0;

   KOKKOS_FUNCTION
   virtual void do_something() const = 0;

  // PARALLEL DISPATCH OCCURS IN THIS FUNCTION
   virtual void some_loops() = 0;

 protected:
   int x_nodes_;
   int y_nodes_;
   int z_nodes_;
   Kokkos::View<double****, Kokkos::CudaUVMSpace> my_view_;
};

class AnotherClass : public ViewClass {
public:
  AnotherClass(const Eigen::VectorXi &input);

  virtual ~AnotherClass();
   
  KOKKOS_FUNCTION
  void operator()(const int &x_index, const int &y_index,
                  const int &z_index) const;

  KOKKOS_FUNCTION
  virtual void do_something() const;

  // PARALLEL DISPATCH OCCURS IN THIS FUNCTION
  void some_loops();
};
```

**Comment by shellshocked2003** [comment]
I managed to get things working without polymorphic classes for the sake of simplicity, though it's not ideal from a maintenance perspective. I understand it's a limitation for CUDA currently, but it would be very helpful if Kokkos could handle/assist with the interaction between polymorphic classes and CUDA to get round the `vtable` issue.

Appreciate your quick responses and help!
