### ISSUE TITLE
Cannot save middle variables in parallel_reduce

### ISSUE THREAD

**Issue by MyRespect** [kokkos/kokkos#1654]
I want to record the index value of kzpart, which is the index satisfied the condition in parallel_reduce operator.
But I cannot find a way to do that, can you help me ?

```c++
#include <iostream>
#include <Kokkos_Core.hpp>

using namespace std; 

struct SaveIndex{
	typedef int value_type[];
	typedef Kokkos::View<int*>::size_type size_type;

	Kokkos::View<double **> zpart_ ;
	Kokkos::View<double **> zpart0_ ;
	Kokkos::View<double*> kzpart_ ;

	size_type value_count;

	SaveIndex(Kokkos::View<double*>& kzpart, Kokkos::View<double **>& zpart, Kokkos::View<double **>& zpart0):
	kzpart_ (kzpart), zpart_ (zpart), zpart0_ (zpart0), value_count(zpart.extent(1)) {}

	KOKKOS_INLINE_FUNCTION 
	void operator() (const size_type m, value_type sum) const{

		double right = zpart_(3,m);
		double left = zpart0_(3,m);

		if (right * left > 0) {
			sum[0] += 1;
			kzpart_[sum[0]]=m;
		}
	}	
};

int main(int argc, char* argv[]){

	Kokkos::initialize(argc, argv);
	Kokkos::View<double*> kzpart ("kzpart", 100);
	Kokkos::View<double **> zpart ("zpart", 5, 10);
	Kokkos::View<double **> zpart0 ("zpart", 5, 10);

	for ( int j = 0; j < 5; ++j ) {
    	for ( int i = 0; i < 3; ++i ) {
      		zpart(j,i) = 0;
    	}
  	}

  	zpart(3,1) = -1;
	zpart(3,3) = 2;
	zpart(3,7) = -1;

	zpart0(3,1) = -1;
	zpart0(3,3) = 2;
	zpart0(3,7) = -1;

	SaveIndex cs (kzpart, zpart, zpart0);

	int sums[3]={0,0,0};

	Kokkos::parallel_reduce(zpart.extent(1), cs, sums);
	cout << "Index under condition sum is " << sums[0] << endl;
	for (int i = 0; i < sums[0]; i++)  {
		cout << "kzpart:  " << kzpart[i] << endl;
	}
  	Kokkos::finalize();
	return 0;
}
```

**Comment by mhoemmen** [comment]
@MyRespect Please use proper formatting to show code examples.  Use three backquotes to enclose multiple lines of source code.  For example:
```
c_plus_plus_function ();
std::vector<int> vecOfInts (42);
```

**Comment by crtrott** [comment]
And add "c++" after the three thingies, fixed it for both of you ;-).

@MyRespect I believe your issue is that sum contains only partial results. That means your index into kzpart will not be unique. In fact the way stuff gets mapped on GPUs I can guarantee you that at the point where you use "sum[0]" to index into kzpart it is always 1. So all your threads overwrite each others stuff. For what you want to do you either have to do a `parallel_scan` (which doesn't support the type of array reduction {i.e. int[3]} you are using, but could be done with a struct which contains a int[3]) or you need to use an atomic index counter. Does that help? If not someone can probably post fixed code for you.

**Comment by MyRespect** [comment]
Thank you all,  yes parallel_scan help me a lot.
