### ISSUE TITLE
Kokkos Tutorial 07/24/2018

### ISSUE THREAD

**Issue by ibaned** [kokkos/kokkos#1707]
https://docs.google.com/spreadsheets/d/1MuSBl4Uh21tH2t4ENhvsVaS6p728fDmEjBiWyPAomvE/edit#gid=0

**Comment by ibaned** [comment]
All attendees please add a row with your information to the above spreadsheet

**Comment by ibaned** [comment]
The spreadsheet should now be editable to anyone with the link

**Comment by ibaned** [comment]
Also, could all attendees please fill out the following survey:

https://goo.gl/forms/BmAQtGBVnG28P5PJ2

**Comment by ibaned** [comment]
Tutorial complete!

**Comment by ibaned** [comment]
I did, though, want to quickly record some things that users told us:
 - multiple GPUs per MPI rank would be great (we likely won't do this though)
 - CUDA streams would be great (we likely will do this)
 - profiling tools could target some common trace format such as Google Chrome
 - need to provide clear tutorial on using the nvprof interface to the profiling tools
 - DualView doesn't seem fundamentally useful to all projects, maybe leave it out (or later) in the tutorial
 - A big point of confusion was that hierarchical parallelism is not nested parallelism, all threads are running even the outermost lambda. make this clear in the tutorial.
 - Kokkos developers should know the details of backend implementations, especially CUDA. Several groups are comparing Kokkos to handwritten CUDA and they want to know exactly what the Kokkos CUDA backend does behind the scenes.
 - provide `min` and `max`
 - provide some algorithms for 1D views such as exclusive scan
 - there is some confusion/annoyance about the possible future "switch" from ThreadVectorRange to SIMD types.

There is probably more that I can't remember at the moment...

**Comment by dalg24** [comment]
> * provide min and max

We discussed the possible interest for STL-like algorithm on rank-1 views.

**Comment by ibaned** [comment]
@dalg24 it would be good to enumerate the ones your team is currently using

**Comment by dalg24** [comment]
* `exclusive_scan`
* `accumulate`
* `iota`
* `adjacent_difference`
* `min`, `max`, `minmax`

we also have one to fetch the last element in a view

**Comment by mhoemmen** [comment]
@dalg24 wrote:
> We discussed the possible interest for STL-like algorithm on rank-1 views.

I think we could do this with the Ranges TS and make it look like the new parallel algorithms, no?

**Comment by ibaned** [comment]
@mhoemmen I like the idea of fitting the new parallel algorithms interface, in particular `Kokkos::reduce` is most akin to `std::transform_reduce`. I'm not familiar with the Ranges TS, however, I would love a TL;DR about Ranges from someone more familiar here to get us started.

**Comment by mhoemmen** [comment]
@ibaned One-sentence description of Ranges: You can use containers or things that look like them in standard algorithms, in place of iterator ranges.

**Comment by ibaned** [comment]
Some anonymized feedback from the tutorial survey:
About Kokkos:
 - an equivalent to `boost::serialization`
 - non-experimental ScatterView
 - SyCL backend
 - more complete Wiki
 - best practices / lessons learned guide for transitioning codes
About the tutorial:
 - go slower for beginners
 - spend more time on the View early on
 - less hands-on overall
 - more time for the hands-on
 - improve the KokkosKernels documentation (LU & QR with complex numbers?)
 - not enough hints in the ScatterView tutorial
 - DualView not understood

**Comment by crtrott** [comment]
Regarding the STL like stuff: I am putting this on our work plan. @dhollman will potentially work on this.

**Comment by dhollman** [comment]
> an equivalent to `boost::serialization`

We have an equivalent of `boost::serialization` from DARMA that is totally separate from the rest of the DARMA stuff and extensively tested.  Do you think some spiffed-up version of this would help?

> SyCL backend

This is interesting, since SyCL is kind of trying to do the same thing we are in a sense.  Does "SyCL backend" or "SyCL compatibility" make more sense as a broad direction? Regardless, I've had a lot of contact with SyCL people for C++ executors, and I bet we'd be able to do this pretty quickly.

> I like the idea of fitting the new parallel algorithms interface

I've been thinking a lot about this as well as Kokkos' interaction with the ranges TS (and more broadly, the ranges v3 programming model) for a while now. I wrote a [paper](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0518r1.html) that was accepted into C++17 before we shipped it on a small piece of this topic (that should make things easier for us in a small way). For ranges particularly, there's a lot to do still beyond just implementation details; a lot of things in scientific computing don't fit cleanly into this model. But long story short — yes, I'm looking forward to digging into this in the upcoming months.

**Comment by ibaned** [comment]
This can be broken up into individual feature requests, closing in favor of that.
