### ISSUE TITLE
OpenCL

### ISSUE THREAD

**Issue by prodnet** [kokkos/kokkos#1856]
This compiler supports OpenCL?

**Comment by mhoemmen** [comment]
Kokkos is not a compiler.  Do you mean to ask, "Does Kokkos support OpenCL?"

**Comment by prodnet** [comment]
Yes exactly,  does Kokkos support OpenCL, OpenACC directives ?

**Comment by mhoemmen** [comment]
Kokkos does not currently support an OpenCL or OpenACC back-end.

**Comment by crtrott** [comment]
Practical existing OpenCL implementations do not support enough C++ in the kernel language so we can't implement an OpenCL backend.

**Comment by naromero77** [comment]
@crtrott I found this old thread. Can you say which specific things are missing in the OpenCL? Is it mostly about the lambdas?

**Comment by jayjaybillings** [comment]
Based on the announcement this morning by Secretary Perry that Frontier will be completely AMD based, including with Radeon GPUs, do you have any thoughts about how Kokkos will play with that architecture?

One of my staff members pointed me at this thread this morning after I said that Kokkos would probably support OpenCL... whoop! ;-)

**Comment by mhoemmen** [comment]
@crtrott will say more, but Kokkos definitely has a solid plan for Frontier's AMD architecture.

**Comment by naromero77** [comment]
So the backend for Aurora will be OpenMP 4.5?

**Comment by nmhamster** [comment]
@naromero77 - we cannot comment on the programming model support for Aurora in a public setting. There is a plan to support all currently announced DOE Exascale architectures with a performant programming model.

**Comment by naromero77** [comment]
thanks, understood.

FYI: There is one Aurora announcement at ISC already and more public details are supposed to be revealed this week.

**Comment by jeffhammond** [comment]
I can't speak for Kokkos but I can tell you what Intel as said publicly about Aurora software (#IamIntel).  Both OpenMP 5.0 and Data Parallel C++ (DPC++) based on Khronos SYCL will be supported on Aurora.  Both of those will be based on Clang/LLVM and Intel has or will put the open-source version on GitHub.

I have personally been working on the mapping from Kokkos to SYCL/DPC++ for more than a year.  They are very similar and I expect the Kokkos port to DPC++ to be straightforward (https://doi.org/10.1145/3318170.3318193).  Because Kokkos likes to use pointers internally, it will need to rely on an open-source extension (https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/USM/USM.adoc) until such a time - hopefully soon - as SYCL supports pointer-based memory management.  Kokkos also requires a trivial front-end extension  (`-fsycl-unnamed-lambda` - see https://github.com/intel/llvm/releases/tag/2019-08) because Kokkos does not require kernel names the way SYCL does.

Intel has a prototype implementation of Kokkos sitting on top of DPC++ that we use to break the compiler.  I believe that some combination of { @bjoo @crtrott @nliber } have created prototypes as well.

I don't know what the status of the OpenMP target back-end of Kokkos is, but that is also a viable target.  Personally, I think the mapping of Kokkos to SYCL/DPC++ is too good to pass up.

I will also add that, because Intel has open-source its LLVM-based GPU compiler (https://github.com/intel/intel-graphics-compiler), DOE may be able to support Kokkos natively using the Kokkos-Clang front-end and not go through any intermediate programming model.  However, I am not a compiler developer and have no idea how much work would be involved in this.

Anyways, if you want to ask me questions, it's probably better to do this on Slack.

# Details

Citing my sources so nobody freaks out and thinks that I am disclosing anything new here.

## OpenMP
* "The short answer is 1) Intel will release a C/C++/Fortran OpenMP offloading compiler for iGPU. The C/C++ OpenMP offloading compiler for GPU is available for Intel Internal users; 2) Intel will open source C/C++ OpenMP offloading compiler for CPU and GPU; 3) DPC++ is a complimentary to OpenMP, not replacing to OpenMP." (https://github.com/intel/intel-graphics-compiler/issues/62#issuecomment-468727149)
* "Yes, we will open source our LLVM-based OpenMP offloading compilers." (https://github.com/intel/intel-graphics-compiler/issues/62#issuecomment-509912798)

## SYCL/DPC++
* Aurora will support oneAPI (https://newsroom.intel.com/news-releases/u-s-department-energy-intel-deliver-first-exascale-supercomputer/)
* oneAPI includes the Data Parallel C++, which is based on Khronos SYCL (https://newsroom.intel.com/news/intels-one-api-project-delivers-unified-programming-model-across-diverse-architectures/).
* Intel stated its intent to support SYCL in the LLVM project in January (https://lists.llvm.org/pipermail/cfe-dev/2019-January/060811.html).  See https://github.com/intel/llvm/wiki/SYCL-patches-upstream-status for progress.
* The Intel SYCL compiler based on LLVM has been on GitHub for months (https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedWithSYCLCompiler.md).

**Comment by dingwentao** [comment]
@jeffhammond  Hi Jeff, thanks for these useful information. We are wondering what the current progress of developing Kokkos to support SYCL/DPC++ is. Is there any way to join the slack channel as you mentioned it's better to ask you questions there. Thank you!

**Comment by DavidPoliakoff** [comment]
@dingwentao , would you be able to share an email with us? That's the easiest way to get on Slack. Sorry for the inconvenience.

**Comment by rZhBoYao** [comment]
> Practical existing OpenCL implementations do not support enough C++ in the kernel language so we can't implement an OpenCL backend.

Does the new kernel language "C++ for OpenCL" support enough C++ to serve as a Kokkos backend?

**Comment by masterleinad** [comment]
We support `SYCL` now that supports OpenCL devices.
