### ISSUE TITLE
Kokkos Initialization of Views

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#1877]
I appreciate the Kokkos mantra of "no hidden deep copies", however I wish the same applied to view initialization. I'd rather have the default be no initialization, and require the user to explicitly initialize. It gets annoying to have to add `Kokkos::view_alloc("tag",Kokkos::WithoutInitializing)` all over the code.

**Comment by mhoemmen** [comment]
This could be a good idea, but it would require specializing Kokkos::View's constructor based on whether it makes sense to initialize a value type from random bits in memory.

**Comment by ibaned** [comment]
@mhoemmen no I don't think we'd bother with that, even for types which get into weird states (`NaN`), the common case is for users to run a `parallel_for` that just overwrites their values no matter what they are. I actually agree with @stanmoore1 in a design-from-scratch scenario. I do worry however that changing the default will break some code that relies on the zeroing behavior. To be fair, I suspect the majority of uses of View in the wild don't depend on this behavior, but I some of them do (especially those involving subsequent atomics, which people seem to love to do).

However, there is a possible good compromise in #1873: Essentially, the solution to that issue is a type-level attribute on the View that disables initialization. So the question for @stanmoore1 is does it sound sufficiently less annoying to simply change the typedefs in LAMMPS to `View<double**, Uninit>` or similar, as opposed to having to go through all the View constructor calls.

**Comment by stanmoore1** [comment]
After a lengthy Slack discussion, it sounds like this isn't going to happen. Closing this issue.
