### ISSUE TITLE
runtime cost of label when using View

### ISSUE THREAD

**Issue by tgzhou98** [kokkos/kokkos#1925]
![image](https://user-images.githubusercontent.com/24786426/49494849-0064e900-f89c-11e8-85ec-35c4409714b1.png)

This dtrace profile shows that constructing of the basic_string costs about 60% time. I'm pretty sure that I don't use any string explicitly. So the cost must from the constructing of View. How to solve this runtime cost problem?

System: Mac OS X 10.11
compiler: g++-8

If any information is required, please ask me.

When using apple clang, everything is fine.
![image](https://user-images.githubusercontent.com/24786426/49499691-c26ec180-f8a9-11e8-89ea-d75ac128b922.png)

```
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by crtrott** [comment]
That doesn't make much sense to me ;-). Do you have a reproducer? And how much absolute time are we talking about? One thing which could happen is that the string construction for GCC is a false positive because that is the place where it stalls out to get the actual physical memory. Too explain a bit more:

When you create a view it will call malloc or something like that at some point. But malloc only reserves virtual memory. As long as you don't actually touch the memory it may not give you actual memory in your DDR. The first time we really touch the memory of a View is when the constructor sticks a string into it. So maybe what the profiler sees is the latency of getting physical memory and associates it with the string creation. But it is still very weird. 

If you have a reproducer I'd love to look at it. Generally the string construction should be absolutely in the noise compared to getting an allocation.

**Comment by tgzhou98** [comment]
[My project](https://github.com/tgzhou98/DFT-DMET)

It's also weird to me g++-8 produce this profile result, but clang is correct. The profiler is dtrace invoking by CLion

**Comment by stanmoore1** [comment]
Are you using the correct binding/thread affinity?

**Comment by tgzhou98** [comment]
Since I'm new to kokkos, I don't understand what is the correct binding/thread affinity. What can I do is just following the examples of kokkos. Could you please explain more? @stanmoore1

**Comment by crtrott** [comment]
I am looking into your thingy (though gotta fix it first since it doesn't compile). To set OpenMP affinity follow the instructions printed by Kokkos initialize if you didn't set it yet. I.e. set OMP_PROC_BIND=spread OMP_PLACES=threads

**Comment by tgzhou98** [comment]
A update the version of `googletest` and now it can automatically download submodules by cmake and compiles easily. 

And I use this commands in zsh
```
export OMP_PROC_BIND=spread
export OMP_PLACES=threads 
```
but parallel version is still slow

**Comment by crtrott** [comment]
In your tests you often have a structure where you have a loop over NMax and within that loop you create small views. You should either reuse the views inside the loop and create them outside, or create 2D views with the first dimension being NMax.
