### ISSUE TITLE
Export CMake targets

### ISSUE THREAD

**Issue by Rombur** [kokkos/kokkos#1966]
It would be nice that when Kokkos is installed it always export targets that can be read by CMake. This way library developers do not have to worry how the users installed Kokkos (CMake or bash script install).

cc: @dalg24

**Comment by crtrott** [comment]
This is in the works and we expect it to go in in the next couple weeks.

**Comment by ndellingwood** [comment]
Related to kokkos/kokkos-kernels#120

**Comment by jjwilke** [comment]
Related to #1902. Kokkos has installed targets and packages for a while using standalone CMake.

I am in favor of NOT allowing a CMake target to be installed from the standalone Makefile. We should be encouraging people to move to using the standalone CMake. #1902 is an example of difficult problem to handle that can be fixed with some CMake magic. I don't want to be patching CMake in two places.  The Makefiles should really only be there for mini-apps or the rare system that only supports Make.

**Comment by ibaned** [comment]
@jjwilke definitely agreed. note that its not so much computing systems that don't support CMake, but rather applications like LAMMPS whose main build system is GNU Make calling Kokkos' GNU Make. LAMMPS does have CMake as well though, so it wouldn't be unreasonable to declare that Kokkos+LAMMPS requires CMake and deprecate the Kokkos GNU Make system. @crtrott probably has push-back on this though.

**Comment by jjwilke** [comment]
I believe we agreed that downstream CMake will be required to build Kokkos with CMake.
@crtrott: If so, we can close this?

**Comment by masterleinad** [comment]
Can we close this?
