### ISSUE TITLE
atomic_fetch_oper/atomic_oper_fetch aren't very convenient to use

### ISSUE THREAD

**Issue by etphipp** [kokkos/kokkos#1977]
I have a code where I need to do complex atomic operations using Kokkos::Impl::atomic_fetch_oper() and Kokkos::Impl::atomic_oper_fetch().  The problem is the operator that is passed to these functions needs to have a static, apply method, e.g.,
```
template < class Oper, typename T >
KOKKOS_INLINE_FUNCTION
T atomic_fetch_oper( const Oper& op, volatile T * const dest ,
  typename Kokkos::Impl::enable_if< sizeof(T) == sizeof(int) , const T >::type val )
{
  union { int i ; T t ; } oldval , assume , newval ;

  oldval.t = *dest ;

  do {
    assume.i = oldval.i ;
    newval.t = Oper::apply(assume.t, val) ;
    oldval.i = Kokkos::atomic_compare_exchange( (int*)dest , assume.i , newval.i );
  } while ( assume.i != oldval.i );

  return oldval.t ;
}
```
There are two problems with this that make it difficult to use in any general case:
* You can't use a lambda for Oper 
* You can't have any state in Oper 

Can Oper::apply() be replaced with
```
    newval.t = op(assume.t, val) ;
```
which would allow one to use lambda's or state-full functor's for Oper?

**Comment by dhollman** [comment]
Putting this in 3.3 release because that's the earliest I can see it getting done.  We might decide this is something that we don't want at all (for reasons discussed above), but I'm just putting it there for now.

**Comment by etphipp** [comment]
So all I was really requesting was to change Oper::apply() with op.apply(), which is a perfectly backward-compatible change given that an instance of Oper is already an argument to the function, and as far as I can see, has now downside.  I can see how it is important to nail down what the use-cases of this function are, but to me this change seems orthogonal to that.

**Comment by dhollman** [comment]
`op.apply()` still doesn't allow you to use lambdas directly, but that seems reasonable.  I don't know why we're taking something as an argument and then using a class method; I agree that doesn't make much sense.

This is a very scary area, though.  It's a function that's potentially called multiple times, but only in rare scenarios.  That's the kind of thing that can lead to bugs that only show up at scale (because it only gets run multiple times when there's a collision).  I know that you understand the risks, and many (if not most) `const` qualified call operators are pure (or at least idempotent), but these are the things we should to think about even to make the change to `op.apply()`.

That said, if you have a compelling use case (or something you can't talk about is also fine), we can give you something that provides the same functionality in an `Advanced` namespace (or `Experimental::Advanced`), but is spelled differently from the current feature so that we're not committing to extending or expanding the current functionality (which I think will probably end up being deprecated ultra-long-term).

**Comment by etphipp** [comment]
My use-case is HogWild!-like stochastic gradient descent algorithms for tensor decomposition that use more complicated updates than just an increment, and involve run-time determined numerical constants (think of step sizes).  Since the current interfaces uses a static method, I can't just put those constants in an Oper object and use them in apply().

I agree you can't do a lambda like this, but at least it would allow me to implement the operation I need (without hacking in constants).  And I would be happy for something in an `Experimental::Advanced::YouHaveToBeCrazyToUseThis::NoReallyCrazy` namespace :)

**Comment by dhollman** [comment]
reassigning to an earlier milestone.  This shouldn't take long.

**Comment by dhollman** [comment]
Attaching https://people.eecs.berkeley.edu/~brecht/papers/hogwildTR.pdf to read later for when we need to understand the broader implications of this use case

**Comment by masterleinad** [comment]
Fixed in https://github.com/kokkos/kokkos/pull/2838.
