### ISSUE TITLE
Parallel Reduce/Scan and deep_copy blocking behavior

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#2077]
In order to clean up the underspecified blocking behavior of parallel reduce we will do the following:

 * parallel reduce/scan with a scalar as result argument will block
 * parallel reduce with a reducer which wraps a scalar will block
 * parallel reduce/scan with a view as result argument will be asynchronous
 * parallel reduce with a reducer which was constructed from a view will be asynchronous

The blocking behavior will be enforced by the parallel_reduce/scan function, not the backend implementation. It will call Kokkos::fence() if required. Consequently the backend implementation can always be asynchronous - we enforce the semantics in a single place. 

To interact with reducers, the reducer concept will be extended to have a function `bool require_fence()` which will signal the way the reducer was constructed. Question: for backwards compatibility we could make that function optional and if its not there we fence. Thoughts?

deep_copy without execution space argument will always fence. With execution space argument it will fence only that execution space instance. I am considering to introduce a NullSpace execution space. This could be the exec space we use for example for memory spaces which can't be directly accessed (i.e. file system or so), but require bulk transfer via deep_copy. We can also use that as an argument to deep copy to indicate complete asynchronous behavior. Thoughts?

**Comment by crtrott** [comment]
parallel_scan without result argument may be asynchronous.

**Comment by dhollman** [comment]
- Question: for backwards compatibility we could make that function optional and if its not there we fence. Thoughts?

As much as it pains me to say it, probably the most reasonable behavior for now should be to fence if the customization is not present.

Also, we should consider phrasing this as a `query`-only property rather than as a method.  While it is technically semantic-changing (and thus on the edge of what we want to use properties for), it's orthogonal enough to the other things that reducers do that it might not be a great idea to require it to be intrusive.  We can always make the property defer to an intrusive `require_fence()` method if present, but to do that we have to call it as a property from the backend (rather than as a method).

> deep_copy without execution space argument will always fence. With execution space argument it will fence only that execution space instance. I am considering to introduce a NullSpace execution space. This could be the exec space we use for example for memory spaces which can't be directly accessed (i.e. file system or so), but require bulk transfer via deep_copy. We can also use that as an argument to deep copy to indicate complete asynchronous behavior. Thoughts?

This problem is actually a bit more complicated than we're making it.  There are actually two different prerequisites here that need to be expressed in asynchronous contexts: the dependency on the destination (in the destination memory space and with the destination execution space instance) and the anti-dependency on the source (in the source memory space and source (?) execution space).  We've gotten away with ignoring the latter thus far because of how streams work in CUDA, but with a more complex expression of dependencies (like that in SYCL, for instance), this anti-dependency also needs to be expressed.  It's not clear to me that one execution space argument can fully express this complexity.
