### ISSUE TITLE
Allocation of team_shared View of Unmanaged View segfault

### ISSUE THREAD

**Issue by dholladay00** [kokkos/kokkos#208]
In allocating a team shared View of Views (using a parallel for) as prescribed in an earlier issue #193 , I am receiving segfaults:

```c++
parallel_for (policy.set_scratch_size(level, PerTeam(mem_size), PerThread(0)),
    KOKKOS_LAMBDA(const member_type & team)
  {
    // cdata structure
    custom_array_t<real_t> A;
    // 1d view containing the data
    A.buffer = View<real_t*>(team.team_scratch(level), onedb_size);
    // view of views pointing to data
    A.data = 
      View< View<real_t*, MemoryUnmanaged>** >(team.team_scratch(level), bs, nbr);
    // specifying memory layout using parallel_for as prescribed seg-faults occur within
    parallel_for(Kokkos::TeamThreadRange(team, bs), [&] (const int e)
    {
      int_t begin = 0;
      for (int_t br = 0; br < nbr; ++br)
        begin += m(br);
      begin *= e;
      for (int_t br = 0; br < nbr; ++br) {
        const int_t end = begin + m(br);
        A.data(e, br) =
          Kokkos::subview(A.buffer,
                          Kokkos::pair<int_t, int_t>(begin, end));
        begin = end;
      }
    });
  });
```

First, I am getting a warning: 
`Kokkos::OpenMP::initialize WARNING: You are likely oversubscribing your CPU cores.
                                    Detected: 40 cores per node.
                                    Detected: 40 MPI_ranks per node.
                                    Requested: 40 threads per process.
`

This is within google test, is that what is causing the problem with this warning?

On OpenMP, this yields: `SUMMARY: AddressSanitizer: SEGV /.../kokkos/core/src/impl/Kokkos_Atomic_Fetch_Add.hpp:159 Kokkos::atomic_fetch_add(int volatile*, int)`

**Comment by dholladay00** [comment]
Here is a reproducer (will probably have to change some paths in the makefile, etc.). Probably not a true minimum working example, but it is fairly short and gives the error I am seeing. 
[reproducer.zip](https://github.com/kokkos/kokkos/files/167591/reproducer.zip)

**Comment by crtrott** [comment]
Carter are you looking into this?

**Comment by crtrott** [comment]
How critical is this for you?

**Comment by crtrott** [comment]
Btw. the oversubscription warning happens if your number of MPI ranks x threads per MPI rank is larger than the number of hyper-threads on the node. We know of two situations there this goes wrong currently (and gives a false positive warning)
(i) BG/Q
(ii) When running interactively with SLURM on some systems and then executing code without srun or mpirun. The environment can be setup as if you want to use one MPI rank per core, and it only get reset with actually using srun or mpirun. This for example happens on the Sandia testbed Shepard (and there is a corresponding issue open: issue #159

**Comment by dholladay00** [comment]
Our preference is to use team local memory as it is best suited for our implementation.

However, these data structures are still in the development stages. But it seems that if we wanted to go back to not using team local memory, we would need to get at the maximum number of teams that are active.

This goes back to a telecon we had with Carter around 5 weeks ago. There is an email chain (I believe you were CC'd) that might further information.

**Comment by dholladay00** [comment]
While this behavior might not be critical, the knowledge of whether it will or will not be supported is critical.

**Comment by crtrott** [comment]
I elevated this to the summer milestone. I think we need to fix this, and it is blocking a valid use-case.

**Comment by dholladay00** [comment]
Awesome! 

Did you get a chance to look at that .txt (it's ~75 lines of mostly ascii pictures)? I am curious to hear what you think about the implications of removing batching and its effect on parallel launch overhead.

**Comment by crtrott** [comment]
So it took me a lot of time to figure this out. But in the end it is actually user error - though to be fair in a situation where it is not obvious that it is ...

The root cause is that you are creating an unmanaged view of Non-POD types (scratch memory things are by default unmanaged, even independent of what you say they are). Now the problem with that is that its members don't get initialized, i.e. the memory itself is what ever it was. This in turn puts the nested views in an invalid state, which makes thinks like assignment operators non valid operations to do. The only way to get out of this is to use a placement new. I.e. construct a view directly into the memory. And that is what you technically need to do for all unmanaged views of non-pod types. 

Here is the relevant code snipped for the initialization loop:
```C++
new(&A.data(e, br)) View<double*, MemoryUnmanaged>(A.buffer,Kokkos::pair<int, int>(begin, end));
```

You could also run an initialization loop in the beginning with just initialization to the default constructor:
```C++
new(&A.data(e, br)) View<double*, MemoryUnmanaged>();
```

And then later simply assign the subviews as you have been doing now. 

I hope that clarifies the issue. Took me quite a while with a lot of stepping through code in the debugger to see this, even though we had a similar issue in a different scenario before. 

Also while we could fix that internally for you it would have quite a bit of unnecessary overhead for most people (i.e. that we run for the scratch memory constructor an initialization loop with move construction using the default constructor of the elements). But it is something we can discuss. Are you coming to next weeks API review meeting?

I am removing the bug label and make it a question.

**Comment by dholladay00** [comment]
I should be there next week. Would definitely like to discuss as there have been some changes. 

There is a modification to the structure (removal of batching) so it could be that the crs graph is a better option now, though I'm not 100% sure on that. 

Thanks for figuring this out, it looks like it was a subtle issue.

**Comment by crtrott** [comment]
Yeah I figured its all Carters fault for allowing Views of Views in the first place ;-)

Good I close this issue then.
