### ISSUE TITLE
Question: can I get execution_space given TeamPolicy::member_type

### ISSUE THREAD

**Issue by alanw0** [kokkos/kokkos#2089]
We have a 'TeamHandleType' typedef, defined like this:
using TeamHandleType = Kokkos::TeamPolicy<HostSpace, DynamicScheduleType>::member_type

We also have a DeviceTeamHandleType:
using DeviceTeamHandleType = Kokkos::TeamPolicy<DeviceSpace, DynamicScheduleType>::member_type

In a code scope where we are templated on TeamHandleType, is it possible to find out which execution_space it is attached to?

@sayerhs FYI

**Comment by crtrott** [comment]
Oh interestingly enough it is not really, the internal execution_space typedef appears to be private. The return type of team_scratch is actually guaranteed to have the execution space in it as a typedef, but it is somewhat cumbersome to extract it ...

**Comment by alanw0** [comment]
Thanks Christian, this would be great.

**Comment by Char-Aznable** [comment]
If it's a template function, you can make the compiler to deduce the execution space for you by using a `Tag` type templated on the execution space:
```c++
  template < class E > struct Tag {};
  template < class E > using Policy = Kokkos::TeamPolicy<Tag<E>,E>;
  template < class E > using Team = typename Policy<E>::member_type;
  template < class E > KOKKOS_INLINE_FUNCTION
  void operator()(const Tag<E>&, const Team<E>& team) const { ... }
```
I think it's because `Tag<E>` is simple enough so that the mapping "E --> Tag<E>" is injective but deduction won't work via `Team<E>` because of its various specializations. I guess similar deduction would apply to partial specialization if you are working with template classes

**Comment by crtrott** [comment]
Merged into develop.

**Comment by alanw0** [comment]
Thanks Christian.
