### ISSUE TITLE
CMake minimum version update?

### ISSUE THREAD

**Issue by jjwilke** [kokkos/kokkos#2103]
Trilinos is now on 3.10. Do we want to bump Kokkos from 3.3 to 3.10 (or 3.8)?

The most critical update would be for C++ standards. 
````
target_compile_features(kokkos PUBLIC cxx_std_11)
````
is the "right" way to set -std flags. Related to #2025. Right now we explicitly dump the C++ standard into the CXXFLAGS, which is probably the wrong way to do it. This minimally requires 3.8.

@crtrott 
@ndellingwood 
@dhollman

**Comment by crtrott** [comment]
Sure bump it up.

**Comment by jjwilke** [comment]
Going with 3.10 for now.  In the future:

3.12
* Cleaner use of object libraries for separate libs
* Avoid deduplication of -X and other flags through `SHELL`

3.13
* `target_link_options` instead of `target_link_libraries` hack

**Comment by cloudhan** [comment]
Trying to compile on windows but failed. There is too many things to be changed to pass the configure phase of cmake on develop branch... (I know it is not supported currently, thought.)

I'd like to comment that, the kokkos cmake build scripts have its taste, no offense, but not good taste.
I'd like to suggest the following slides/blogs for a modern cmake:
1. [Build Systems: Combining CUDA and Modern CMake](http://on-demand.gputechconf.com/gtc/2017/presentation/S7438-robert-maynard-build-systems-combining-cuda-and-machine-learning.pdf)
2. [Modern CMake for Library Developers](https://unclejimbo.github.io/2018/06/08/Modern-CMake-for-Library-Developers/)
3. [Effective CMake](https://github.com/boostcon/cppnow_presentations_2017/blob/master/05-19-2017_friday/effective_cmake__daniel_pfeifer__cppnow_05-19-2017.pdf)

or if you are even more aggressive, then [More Modern CMake: Working with CMake 3.12 and Later](https://meetingcpp.com/mcpp/slides/2018/MoreModernCMake.pdf)

For modern cmake, I think, we bravely add
```cmake 
cmake_minimum_required(VERSION 3.10)
```
at the top of the repo root `CMakeLists.txt` file.

I see that in https://github.com/kokkos/kokkos/blob/d5c36238dc6a2ea049fa96fbc5bc4c53b2c039f5/CMakeLists.txt#L56-L58
You just want to test if kokkos is added as a subdirectory, the proper way, AFAIK, is
```cmake
if(CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR)
```
as mentioned [here](https://stackoverflow.com/questions/43281410/test-whether-a-cmakelists-txt-is-used-as-a-subdirectory).

In addition to that, because you update to cmake 3.10, then
https://github.com/kokkos/kokkos/blob/d5c36238dc6a2ea049fa96fbc5bc4c53b2c039f5/cmake/kokkos_compiler_id.cmake#L7-L32 can be deleted since [cmake officially support nvcc from 3.8](https://cmake.org/cmake/help/v3.8/variable/CMAKE_LANG_COMPILER_ID.html)

There is also no need to define you own macro or function for `add_library` as `kokkos_add_library`, and the like.

If you want a good reference for complicated cmake project setup, I think [LLVM](https://github.com/llvm/llvm-project) is the way to go.

Hope you a good overhaul.

PS. Maybe setup CIs, otherwise, outsiders have no way to verify their changes won't break your case, thus no way to contribute back.

**Comment by jjwilke** [comment]
@cloudhan 

We are familiar with those documents. Kokkos is, unfortunately, saddled with technical debt that will take a while to pay off. Most of this comes from having to integrate with Trilinos. Being stuck on 3.10 or having to use wrapper calls like `kokkos_add_library` owes to Trilinos.  In addition, I would much prefer to use targets and properties for everything, but we have many projects that rely on  Kokkos cache variables so we have to tread carefully on breaking too much at once.

We discussed whether to completely separate the Trilinos and standalone build systems which would allow us to increase the version and do things more the "right way."  We (I mostly) deemed having two independent build systems to be more dangerous than having a single compromised CMake.

If Kokkos ever gets ripped out of Trilinos to be used as a TPL only, we would be able to make all these changes.

**Comment by cloudhan** [comment]
that is sad

**Comment by jjwilke** [comment]
There are some annoyances, but we have it basically working like a modern CMake project. Downstream Kokkos dependencies can just call `target_link_libraries` and be happily oblivious to the extra complications in Kokkos itself.  So it hopefully shouldn't be too complicated to use Kokkos in your own project at this point.
