### ISSUE TITLE
Add variable template trait for "is a cuda memory space"

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#2196]
We keep rewriting this thing over and over, in Tpetra, Ifpack2, etc.  [Here is a new example.](https://github.com/trilinos/Trilinos/pull/5445)  We should just add the thing to Kokkos.

**Comment by jjellio** [comment]
@mhoemmen As mentioned in my code, there is a bit of policy in this... *What* means Cuda? Technically, we should treat UVM and HostPinned as regular memory.... which means the code should really just check CudaSpace.

Perhaps, a better macro would be: `is_host_addressable<ViewType>`, that would be forward looking for non-nvidia products and match the intent that we really care if the memory is addressable in the traditional host way. E.g., `a[i]`  shouldn't segfault.

**Comment by mhoemmen** [comment]
@jjellio wrote:
> Perhaps, a better macro would be: `is_host_addressable<ViewType>`, ....

That exists already.  It's called `Kokkos::SpaceAccessibility`.  See `kokkos/core/src/Kokkos_Concepts.hpp`.

**Comment by mhoemmen** [comment]
@jjellio Do you think we still need this "is a CUDA thing" feature though?  Kokkos probably could use it, but I'm hoping we could write our code a bit more generically.  The problem is that "is MPI CUDA aware?" specifically refers to CUDA.  We don't have a use case yet for other kinds of memory that MPI could access if configured correctly.

**Comment by crtrott** [comment]
So what are you planning to do if we compile for Frontier or Aurora, where we presumably also need to deal with "can MPI access my memory". Trilinos is employing (an understandably) specific solution to CUDA because its the only production platform with non-host accessible memory they care about. But that is not correct going forward. So "is this a cuda memory space" is not a trait I want to see inside of Kokkos. Anyway what would you want it to be? Should it be true for CudaHostPinnedSpace? For UVMSpace? If yes in both cases the answer is: `SpaceAccessibility<Cuda,Space>` if the answer is only for UVM you can test `std::is_same<Space::execution_space,Cuda>`. If it is only true for CudaSpace the answer is: `std::is_same<Space,CudaSpace>`

**Comment by jjellio** [comment]
@mhoemmen The stuff in `kokkos/core/src/Kokkos_Concepts.hpp` is a natural way to implement this, I wasn't aware of them though.

I *do* think that moving forward, having a consistent and **advertised** API for determining whether memory is addressable is good.  As Christian points out, this is only going to get pushed closer to the spotlight going forward.

As for Trilinos. I wish that we could define a warning similar to deprecated so that all of the 'cuda-isms' in the code would be noted for future deletion. As-is, some are baked into core routines in odd-ball places, where they will be forgotten (and given my data, they should be deleted now).

**Comment by crtrott** [comment]
So are we good on this? @jjellio

**Comment by jjellio** [comment]
I resolved my issue using `kokkos/core/src/Kokkos_Concepts.hpp`

My comment above is more about how people may not know that this functionality exists.
