### ISSUE TITLE
DynRankView dimension information

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#224]
Suppose we have 
`Kokkos::DynRankView<...> a(3,2);'
'a.rank() // 2'
'a.dimension(0) // 3'
'a.dimension(1) // 2'
'a.dimension(2) // expect 0 but it will be 1 for an implementation reason`

What I ask is if you can provide an user interface to get dimension information of DynRankView. I can also do 'mydim = a.rank() > 3 ? a.dimension(2) : 0' but probably most users want to have access function for this to prevent accidental mistakes.

For instance, 'dimension(a, 2) // return 0 if rank is smaller than 3 ' ?? or change dimension method in the Kokkos. 

BTW, how can I put a new line in the code block ?

**Comment by crtrott** [comment]
We believe that returning 1 is better. This is also how normal Kokkos View behaves. 
```C++
Kokkos::View<double*> a("A",10); 
std::cout<< a.dimension_2() << std::endl;
```
This will print 1. The reason is that we have many use cases where people calculate products of dimensions to get some size information. For that purpose this function should return 1.
If you want to just figure out what the rank is use a.rank(). What is your use case where you want it to return 0? Returning 0 does not actually mean the rank is smaller. It is perfectly valid to have a 2D view with 1 or both dimensions 0:

```C++
int N = 1000;
int M = 0;
Kokkos::View<double**> a("A",N,M);  
```
In fact this is a required use case in Trilinos, since we have sometimes degenerated data (i.e. an MPI rank is empty or something). In those cases it must still work. And checking dimension_1()==0 to figure out if it is Rank 1 is actually wrong.

**Comment by hcedwar** [comment]
The `a.dimension(r)` specification is to return 1 when `a.rank() <= r` is an intentional abstraction semantics decision, as opposed to an implementaton artifact.  Consider the following use-case.

    for ( int i0 = 0 ; i0 < a.dimension(0) ; ++i0 )
      for ( int i1 = 0 ; i1 < a.dimension(1) ; ++i1 )
        for ( int i2 = 0 ; i2 < a.dimension(2) ; ++i2 )
          a(i0,i1,i2) += 1 ;

The above pattern will work properly for `0 <= a.rank() < 4` as long as `a.dimension(r) == 1` for `a.rank() <= r`.

**Comment by hcedwar** [comment]
Discussed with requester, can be closed.
