### ISSUE TITLE
Document build system and CMake philosophy

### ISSUE THREAD

**Issue by jjwilke** [kokkos/kokkos#2263]
Add a developer's section to the BUILD.md with instructions on adding new options, new header defines, and new TPLs.

**Comment by jjwilke** [comment]
This is now available for anyone wanting proofread and tell me if it makes sense.

**Comment by dalg24** [comment]
> This is now available for anyone wanting to proofread and tell me if it makes sense.

I looked at the `cmake-promotion` branch and I think it is a good start.  Please make sure not to mix it with miscellaneous fixes to the cmake when you open a PR.

**Comment by jjwilke** [comment]
I consider the documentation part of the Trilinos promotion stuff since most of the people asking for it were internal to Sandia and Trilinos people will ask the most questions about it.

But, yes, point taken. I will not mix unrelated things in PRs.

**Comment by crtrott** [comment]
A few notes: 
- It is Kokkos_ENABLE_OPENMP not Kokkos_ENABLE_OpenMP now isn't it?
- Remove Qthread and ROCm since they are not supported anymore: move HPX from TPL to this
- Change default on  Kokkos_CUDA_ENABLE_LDG_INTRINSIC to ON (we may need to remove this all together)
- How about renaming Kokkos_ENABLE_CUDA_UVM into Kokkos_ENABLE_CUDA_DEFAULT_UM (that is what it really does, and UVM allocations are always available, also NVIDIA is naming it now Unified Memory without the Virtual)
- Kokkos_ENABLE_DEPRECATED_CODE: default needs to be ON. We will switch that maybe tomorrow
- Standard: add c++2a; do we need a default here?

**Comment by masterleinad** [comment]
We should decide if this should be addressed in the 3.0 release or not. Currently, it is in the `Milestone: Release 3.1` project, but also part of the milestone `3.0 Release`. Given that we don't have a pull request yet and there are open questions, I tend to rather target 3.1.

**Comment by jjwilke** [comment]
I made some updates. I would push this out with 3.0.

There is now a PR #2420 that we can monitor that will hold doc fixes as they develop.

**Comment by masterleinad** [comment]
Addressed in #2473 and #2467.
