### ISSUE TITLE
Drop CMake option SEPARATE_TESTS

### ISSUE THREAD

**Issue by dalg24** [kokkos/kokkos#2266]
I am trying to cleanup the logic of the test registration in `core/unit_tests` and I am tempted to drop the `if(SEPARATE_TESTS)`.  I personally like the finer granularity (option set to `ON`).

Can you think of one reason one might want to have a single executable for the core unit tests?

cc: @crtrott @jjwilke

**Comment by jjwilke** [comment]
No opinion. I don't actually know the history of this.

**Comment by crtrott** [comment]
Oh I didn't know that someone added that. I personally like the `have everything for a backend in one executable` and use `--gtest-filter` for choosing individual tests.

**Comment by dalg24** [comment]
> Oh I didn't know that someone added that. I personally like the `have everything for a backend in one executable` and use `--gtest-filter` for choosing individual tests.

Fine by me.  Then I will drop the option and always do a single executable.

**Comment by crtrott** [comment]
We may have had some weird link issues on some early experimental compilers before (like OpenMPTarget, or ROCm) but I think we can handle that via the standalone unit test during experimental development phase. And if they can't link our unit tests for one backend, there is no way they can link a Trilinos executable anyway ...

**Comment by dhollman** [comment]
I added this option (sorry I missed this conversation!).  I mostly added this because tests were taking forever to recompile (because of Kokkos' "include everything everywhere" philosopy) and the only tests I was expecting to change behavior were the tasking tests. The `--gtest-filter` option doesn't work for this purpose because you still have to recompile every test (for a given backend) even to just run one test. That's a real pain when working on Kokkos itself, and discourages our team from compiling and testing early and often.
