### ISSUE TITLE
Kokkos Profiling Hooks: determine device kernel runs on

### ISSUE THREAD

**Issue by DavidPoliakoff** [kokkos/kokkos#2308]
Hey folks,

So I'm looking at the Profiling hooks, and we have this "deviceId" parameter for our beginParallel[Foo] constructs. The only problem is that it's always zero. Now, I put together a branch in which we would take that in as a parameter in the ExecutionPolicy (defaulted to zero) which solves my current problem (CudasimSpace), but wanted to take a moment to get feedback on what this ought to look like.

I think it is the way it is now because the hooks are implemented in Kokkos_Parallel.hpp, so we can't necessarily do things like "oh, if it's Cuda, the Cuda Execution Policy can look at runtime information and make smart decisions," by the time the ParallelFor is handed off to a backend the Profiling hooks have already fired.

The nonbreaking change is something like what I did, making deviceId a trait of a Policy, and maybe somebody a little more Kokkos-literate than I am could make it so that the Cuda policies would default to a different deviceId than the host.

The more breaking change is to move the Profiling hooks lower, into the backends. This introduces more work for a person writing a backend, but might pay dividends in situations where the profiling information really is tied to the backend making runtime decisions.

Personally I think the 99% case is solved by the nonbreaking solution, where people want to see "deviceId=1" for "this runs on GPU" and "deviceId=0" for "this runs on the host," but I wanted people's feedback before putting something together, the design tradeoffs here seem wired to design philosophical inclinations I don't know about Kokkos yet.

**Comment by ibaned** [comment]
We agreed that we will add new hooks, but not break the old hooks.

**Comment by crtrott** [comment]
Actually I am not sure why we would need new hooks. At the place where we call the current hooks, we know what the space instance is, we can actually get it from the execution policy, since it has a mandatory member function "space()". Now the only thing left is translating that into a device id. I even believe that we can simply encode both the type and the instance number in this. Say we use the upper 32 bit to encode the device type and the lower 32 bit for the device instance.
