### ISSUE TITLE
ViewFill fences

### ISSUE THREAD

**Issue by j8asic** [kokkos/kokkos#2335]
Doubts about when deep copying a single value from host across some device view:
- why is there `Kokkos::fence()` before and after the `ViewFill` execution? Why isn't it async like any other `parallel_for` call?
- within `ViewFill` there is `ExecSpace().fence()`, both before and after `parallel_for`. Why if there is already `Kokkos::fence()` as noted above?

**Comment by PhilMiller** [comment]
Since this recently came up in a Slack discussion as I was looking at old issues, here's the answer:
* There's a fence before the execution to ensure that the destination View is not in potential concurrent use by any execution space instance
* There's a fence after the execution because those are the defined semantics of a `deep_copy` call that isn't passed by execution space argument - the contents of the destination `View` are stable when control returns to the caller.

**Comment by JBludau** [comment]
But it still sounds like the `ExecSpace().fence()` inside the `ViewFill` is unnecessary in this case as there is already a global `fence()` ... But we would need to look into this if getting rid of the `ExecSpace().fence()` is worth it for this special case.

**Comment by masterleinad** [comment]
> But it still sounds like the `ExecSpace().fence()` inside the `ViewFill` is unnecessary in this case as there is already a global `fence()` ... But we would need to look into this if getting rid of the `ExecSpace().fence()` is worth it for this special case.

These fences don't exist anymore since https://github.com/kokkos/kokkos/pull/2911/files#diff-fa78644f38e5aaa37985a22ef350c56e075e8ca6eaa5fbb54897b19c5958c86c (Kokkos 3.1.0).
