### ISSUE TITLE
FAILED NIGHTLY: Kokkos_CXX_FLAGS and Kokkos_LINK_FLAGS not working correctly

### ISSUE THREAD

**Issue by jeffmiles63** [kokkos/kokkos#2361]
Cmake previously used KOKKOS_CXX_FLAGS and LINK_FLAGS, but not completely working with Camel Case names...

Need to add something like...

 IF (DEFINED Kokkos_CXX_FLAGS)
     STRING(REPLACE " " ";" KOKKOS_CXX_FLAGS_LIST "${Kokkos_CXX_FLAGS}")
     TARGET_COMPILE_OPTIONS(
       ${NAME}
       PUBLIC $<$<COMPILE_LANGUAGE:CXX>:${KOKKOS_CXX_FLAGS_LIST}>
     )
  ENDIF()

for the kokkos library, exes and test library and exes

Then need something like..

    IF(${CMAKE_VERSION} VERSION_LESS "3.13" OR MSVC)
       IF (DEFINED Kokkos_LINK_FLAGS)
         TARGET_LINK_LIBRARIES(kokkos PUBLIC ${Kokkos_LINK_FLAGS})
       ENDIF()
    ELSE()
      IF (DEFINED Kokkos_LINK_FLAGS)
         TARGET_LINK_OPTIONS(kokkos PUBLIC ${Kokkos_LINK_FLAGS})
      ENDIF()
    ENDIF()

for the kokkos library, exes and test library and exes

**Comment by jjwilke** [comment]
I'm technically on leave or I would do it. I would probably just add a:
````
KOKKOS_OPTION(CXX_FLAGS "" STRING "Extra C++ flags needed")
````
then
````
TARGET_COMPILE_OPTIONS(kokkoscore PUBLIC ${KOKKOS_CXX_FLAGS})
````
The all upper-case version is a regular CMake variable that can have other things appended to it. `Kokkos_CXX_FLAGS` should always match the user-provided cache variable.

Although we should definitely have these so that you can always "patch" a random system no matter what, it's always better to include special-case logic. We have no way to distinguish between "public" and "private" flags. There may be compiler/linker flags you don't want to force on downstream projects (or maybe it's always the case). Also, if we can detect automatically when flags are needed, that's better for usability.

Do we have examples of flags that have to bet set with `Kokkos_CXX_FLAGS`?

**Comment by dalg24** [comment]
When are `Kokkos_CXX_FLAGS` and `Kokkos_LINK_FLAGS` actually needed?
Are the built-in `CMAKE_CXX_FLAGS` and `CMAKE_EXE_LINKER_FLAGS` not sufficient?

**Comment by jeffmiles63** [comment]
It looks like CMAKE_CXX_FLAGS end up in the link line too, but it seems to work.  I am going to change the generate_makefile use CMAKE_CXX_FLAGS for the cxx flags and link the LINK FLAGS to CMAKE_EXE_LINKER_FLAGS.  I will also remove the overlapping flags since they would both end up on the link line.
