### ISSUE TITLE
MPI backend

### ISSUE THREAD

**Issue by aprokop** [kokkos/kokkos#241]
Some people claim that MPI+MPI with MPI3 is the way to go. It could be interesting to think about implementing MPI backend for Kokkos to progress the discussion.

**Comment by mhoemmen** [comment]
We've talked about this a few times.  The idea is that the "inner" MPI would use 1-sided communication, restricted to a single node.  Kokkos::View would wrap an `MPI_Win`, and we would overload operator() to do `MPI_Put`, `MPI_Get`, `MPI_Accumulate`, etc.

There are a few issues with this:

1. For the two levels of parallelism, do we use processes + threads (with `MPI_THREAD_MULTIPLE`), or processes + processes?  The former makes memory tracking easier.  (`MPI_Win_free` must be called collectively by all processes in the group associated with its window.  If there's only one process, then Kokkos only needs to ensure that the threads have joined.  Otherwise, View's destructor would block if the reference count goes to zero, potentially leading to deadlock.  Issues like this are why the C++ MPI interface in MPI 2 was never that good (Jeff Squyres has a good rant on this).)  However, if you're using threads anyway, what's the point?

2. `MPI_Accumulate` only works for data types corresponding to built-in `MPI_Datatype`.  I've heard reports of some MPI implementation versions not working correctly for custom data types with `MPI_Put` etc.  (However, I imagine we could use Kokkos' support for general atomics to work around.)

3. Kokkos uses the ["fence" model of synchronization](https://cvw.cac.cornell.edu/MPIoneSided/fence).  This may lose some performance compared to the [Post-Start-Complete-Wait model](https://cvw.cac.cornell.edu/MPIoneSided/pscw), where "senders" and "receivers" do different things.

I still think it's a good idea, though.  It could be fun also to compare with other PGAS (partitioned global address space) programming models, like [UPC++](https://bitbucket.org/upcxx/upcxx/wiki/Home) or [Global Arrays](http://hpc.pnl.gov/globalarrays/).

**Comment by ibaned** [comment]
I've also just heard a bit about the MPI+MPI approach. What @mhoemmen just proposed is one variant of it, but I believe Bill Gropp was clear to distinguish between MPI 1-sided and MPI shared memory, which suggests a different variant is also possible. I haven't used these functions myself, but the outline would be as follows:

1. Only processes for parallelism. One process per core, maybe even per hardware thread ?

2. Identify processes that share physical memory via `MPI_Comm_split_type(MPI_COMM_TYPE_SHARED)`

3. Kokkos allocators would call `MPI_Win_allocate_shared`

4. Kokkos::View::operator() just indexes directly into allocated memory

5. The fence model stays, using `MPI_Win_fence`

This would look a lot like the current OpenMP backend, for example the communicator returned by `MPI_Comm_split_type` is your "team" and things like team reductions can just be `MPI_Reduce` over that communicator. Similarly, ranges for each team member can be computed starting from `MPI_Comm_size` and `MPI_Comm_rank` called on the team communicator.

I think this variant would be more performant since it uses the same shared memory mechanisms you'd get with OpenMP/Pthreads, namely direct load/stores instead of `MPI_Put` which is likely to be much slower by comparison.

MPI experts please feel free to correct what I've said above.

**Comment by nmhamster** [comment]
@ibaned this is how I thought a model like this would be implemented. It needs some careful thought at the full application level for things like reductions since we need one parent rank per "team" to participate in the multi-node level.

**Comment by ibaned** [comment]
@nmhamster you're right, I just came to the realization of this fundamental break in semantics before your comment showed up. MPI+MPI moves MPI to the right of the "+", every other MPI+X had assumed it was on the left. In less cryptic terms, all code outside `parallel_for` needs to understand that it shares its `Kokkos::View`s with other processes, and coordinate that with regular distributed memory communication, etc. Thats a big programming model distinction, and coming up with an abstraction that covers both MPI+(!MPI) and MPI+MPI in that sense becomes the first big challenge. I don't yet have an answer for this...

**Comment by nmhamster** [comment]
@ibaned if we can ensure correct use of an MPI communicator to keep the RHS MPI "ranklets" out of way I think this could be encouraged to work. It will be somewhat dependent on developers and libraries playing well with communicators (and not `MPI_COMM_WORLD`).

**Comment by ibaned** [comment]
@nmhamster thats a good angle... I don't know if the MPI standard has a converse `MPI_Comm_split_type` but I think you're suggesting to get a communicator that has one rank per machine node and use that for message passing ?

That would preserve the current programming model and be a decent way forward... It occurs to me though that it also ignores a possible benefit of MPI+MPI that we've never had available before, which is that we can have all "threads" participate in the _entire_ message passing process. "threads" could now send/receive their ranges of data, similar to an `MPI_THREAD_MULTIPLE` environment with none of the down sides that come from the locking inherent in the latter.

It may be harder to take advantage of this opportunity, but if we can then it prevents MPI from becoming a bottleneck in the MPI+X world, right now I keep worrying about the fact that MPI has to serially handle arrays of size N while the rest of my code is parallelized and handles N/P.

**Comment by hcedwar** [comment]
Dan (ibaned) expressed desire to develop such a back-end.  This experimental/research back-end must begin life in the Kokkos::Experimental namespace.

**Comment by mhoemmen** [comment]
The big risk is deallocation -- users have to make sure that Kokkos::View destructor calls are consistent across processes, or at least that "the reference count goes to zero collectively."

**Comment by ibaned** [comment]
my first guess is `MPI_Barrier(team_comm)` would be both the implementation of `fence()` and be called before allocation and deallocation.

**Comment by ibaned** [comment]
by the way, is there a `View` constructor that accepts a `MemorySpace` instance ? It would be nice for `View`, `parallel_for`, etc. to accept a user-supplied communicator, the requirement being that all ranks share physical memory.

**Comment by nmhamster** [comment]
> @nmhamster thats a good angle... I don't know if the MPI standard has a converse MPI_Comm_split_type but I think you're suggesting to get a communicator that has one rank per machine node and use that for message passing ?
@ibaned yes, that's how it works in my head (with not much time devoted to thinking through the issues). I think of the one rank per machine node as the Level-1 MPI (perhaps the "legacy") rank. Then within the node a separate communicator handles the Level-2 MPI. Using `MPI_COMM_WORLD` does then allow of things like true global reductions etc.

**Comment by hcedwar** [comment]
Execution space and memory space instances are top priority for May-July.

**Comment by ibaned** [comment]
progress can be tracked via this dummy PR: ibaned/kokkos#1. anyone who wants to help is welcome. so far, the basic memory space allocation has been drafted, but no attempt at compilation has been made. I'll take a break from this for a while and try to figure out execution dispatch later.

**Comment by mhoemmen** [comment]
@ibaned Awesome!  Thanks for contributing!  I'll post some comments on the PR.  If we're a bit slow, please don't worry -- things have gotten really crazy for us these days.

The trickiest part of execution dispatch might be writing totally portable code.  If you're using only processes (representing a team as a subcommunicator), `parallel_for` is trivial.  `parallel_reduce` would need a clever mapping from reduction type to `MPI_Datatype` (or would need to roll its own reductions using shared memory).  Ditto for `parallel_scan`.

**Comment by mhoemmen** [comment]
I was thinking about the issue of reference counts getting out of sync across processes.  I can think of at least two ways to deal with this:

1. Add extra checks in a debug build
2. Ref count -> 0 "marks the View for deallocation," but does not necessarily deallocate it

For "extra checks," one could (for example) keep an `MPI_Win` of reference counts, do `MPI_Accumulate` on it at every reference count update, and make sure at convenient global sync points that it's consistent.  This is expensive, so one would only do it in a debug build.

Option 2 above imitates MPI's language for `MPI_Comm_free`, which "schedules the communicator for allocation," but still allows "pending operations that use the communicator" to "complete normally."  (`MPI_Win_free` isn't so clever -- it requires an intervening fence or unlock to ensure that the calling process has finished its involvement in the window.)

As with Option 1, this implies that fences on the window may do some extra communication now and then to make sure that everybody is in sync.  The View may not get deallocated right away.  This could cause trouble for users who currently expect immediate deallocation when the reference count goes to zero.

**Comment by mhoemmen** [comment]
It occurred to me just now that `MPI_Win_fence` operates on the window (the `View` in this case), not on the window's communicator.  All one-sided MPI synchronization is through the window.  This means that correct implementation of `fence()` should require calling `MPI_Win_fence` on all windows that might be affected by a piece of code, right?

**Comment by ibaned** [comment]
Yes, if you want to do everything by the MPI standard one-sided memory model then `MpiShmemSpace::fence()` ought to walk over all the currently allocated Views and call `MPI_Win_fence` on their Win. That sounds really inefficient to me, so I decided to bypass it and just use a C++11 memory fence. At SIAMPP16, the suggestion of the MPI+MPI folks was to use MPI shared memory, not one-sided, and combine it with C++11 atomics.

In terms of reference counting, I was thinking of something like `MPI_Barrier(m_team)` at key points, e.g. when reference count goes to zero or even every time it changes. In every scheme I can think of, a difference in reference counts will manifest as some processes not entering collective operations at the right time, possibly causing deadlocks. Basically, out-of-sync Views in MPI+MPI are equivalent to misusing MPI communication calls, and to some degree checking their correctness amounts to an MPI debugger / program validator.

**Comment by hcedwar** [comment]
@aprokop  Closing this until we have a driver or research project actually working on it.
