### ISSUE TITLE
Inter-operatibility between View and DynRankView.

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#245]
Now I mix a view with a dynrankview. Currently when I code
```
DynRankView a;
View b;
deep_copy(a, b);
````
this does not work. Can you provide assignment operator to chane one to another ?
```
DynRankView a;
View b;
DynRankView b_copy = b;
deep_copy(a, b_copy);

// or 

DynRankView a;
View b;
View a_copy = a;
deep_copy(a_copy, b);

// or 
deep_copy(a,b); 
```

Otherwise, I need to do 
```
View b;
DynRankView<b::Layout,b::space> b_copy(a.data(), b.dimension(0), b.dimension(1));
```
This needs properties (like layout and space) and padding information. I don't think that the manual conversion is portable.

Any good idea ?

**Comment by crtrott** [comment]
Yeah these things are missing features. I'll mark it as feature request.

**Comment by ndellingwood** [comment]
The following interoperability features were added in #359 
DynRankView redesigned to be its own View implementation
Added features:

    Copy, Copy-assign View to DynRankView
    deep_copy between Views and DynRankViews
    subview function name now enabled (subdynrankview has same functionality)
    Common method to request rank of a View and DynRankView: rank(user_view); This will eventually be replaced by a constexpr rank() in the View, but this will require coordination with packages and apps to avoid breaking their builds.

**Important!**
Before merging into Trilinos corresponding changes in Sacado must also be made as those in the attached patch file (as .txt)
[sacado-mod-drvredesign-7.patch.txt](https://github.com/kokkos/kokkos/files/359903/sacado-mod-drvredesign-7.patch.txt)
. Otherwise compatibility will break.
