### ISSUE TITLE
Volatile overloads for OpenMP incompatible with SIMD prototype

### ISSUE THREAD

**Issue by tasmith4** [kokkos/kokkos#2770]
The current implementation of `Kokkos::parallel_for` for OpenMP requires volatile overloads of the `+=` operator, which makes it incompatible with the Kokkos SIMD prototype (https://github.com/kokkos/simd-math).  Would it be possible to remove this requirement (perhaps as in https://github.com/kokkos/kokkos/pull/1746)?

**Comment by dhollman** [comment]
I've tried everything I can think of to remove the requirement of a `volatile` `operator+=` from types used with Kokkos reductions, up to and including things like reinterpret casts around volatile `__asm__` blocks. The fundamental problem is that in Cuda, `volatile` has a specific meaning, and as far as I can tell there's no way to get the compiler to emit the instructions that fuse the plus equals instruction(s) with that meaning of `volatile` unless the values are themselves `volatile` at the point where the user does the `+=`. Without this fusing (@crtrott or someone from Nvidia can correct me if that's not what's actually happening), we can see some pretty significant slowdowns in our reductions, so the problem is not just theoretical or some pedantic oddity. Probably some solution exists somewhere, but it is beyond my abilities in terms of generic programming tricks.

**Comment by alanw0** [comment]
@dhollman Thanks for the detailed info. I would like to hear from @crtrott and @ibaned, about possible paths forward here. We (on the stk team) have added Dan's simd header as the implementation for stk-simd, but this issue is blocking us from enabling it as our default. I don't think we have a preference, we just need to know what we have to do. Apparently the issue is that we have some usage code that uses a simd type in a parallel_reduce operation, and that won't compile in an OpenMP build. So please let us know about possible paths forward.

**Comment by dhollman** [comment]
Probably the short-term path forward is for @ibaned to add `volatile` operator overloads, as much as it pains me to say so. I don't know that we have a fix on the horizon for this issue.

**Comment by ibaned** [comment]
@dhollman No, I won't be doing that. The NVIDIA Thrust library does reductions faster than Kokkos (by @crtrott 's own admission) without requiring volatile overloads, so if no Sandian can think of anything better we can simply have Kokkos call Thrust which is available in every CUDA installation. Also @tasmith4 is concerned only with the OpenMP backend since SIMD is only non-trivial for CPUs, and I know for sum reductions we could be calling the OpenMP built-in sum reduction which also doesn't require volatile overloads. Neither of these changes (calling Thrust for CUDA and actually calling OpenMP for OpenMP) are conceptually hard. I'm sure there are reasons of bad architecture in Kokkos why they may be difficult, but I'm not going to proliferate bad architecture to defend bad architecture. Someone else can add volatile overloads to the SIMD classes protected by an `#ifdef` and I'll accept the pull request if Kokkos insists on not improving.

**Comment by crtrott** [comment]
Just as point of reference: the OpenMP native reductions still seem to be slower than ours :-(. This is one of the reasons why we didn't replace that yet (besides compiler issues with custom reductions). 

Code:
```c++
#include<Kokkos_Core.hpp>
#include<cmath>

int main(int argc, char* argv[]) {
  Kokkos::initialize(argc,argv);
  {
    int N = argc>1?atoi(argv[1]):1000000;
    int R = argc>2?atoi(argv[2]):10;

    double sum;
    Kokkos::parallel_reduce(N, KOKKOS_LAMBDA (const int i, double& lsum) {
      lsum+= 1.0*i;
    },sum);

    Kokkos::Timer timer;
    timer.reset();
    for(int i=0; i<R; i++) {
      Kokkos::parallel_reduce(N, KOKKOS_LAMBDA (const int i, double& lsum) {
        lsum+= 1.0*i;
      },sum);
    }
    double kk_time = timer.seconds();
    printf("KK  Time: %e\n",kk_time);

    #ifdef KOKKOS_ENABLE_OPENMP
    timer.reset();
    for(int i=0; i<R; i++) {
      sum = 0.0;
      #pragma omp parallel for reduction(+:sum)
      for(int i=0; i<N; i++) {
        sum+= 1.0*i;
      };
    }
    double omp_time = timer.seconds();
    printf("OMP Time: %e\n",omp_time);
    #endif


    timer.reset();
    for(int i=0; i<R; i++) {
      Kokkos::parallel_reduce(N, KOKKOS_LAMBDA (const int i, double& lsum) {
        lsum+= 1.0*i;
      },sum);
    }
    kk_time = timer.seconds();
    printf("KK  Time: %e\n",kk_time);
 

   #ifdef KOKKOS_ENABLE_OPENMP
    timer.reset();
    for(int i=0; i<R; i++) {
      sum = 0.0;
      #pragma omp parallel for reduction(+:sum)
      for(int i=0; i<N; i++) {
        sum+= 1.0*i;
      };
    }
    omp_time = timer.seconds();
    printf("OMP Time: %e\n",omp_time);
    #endif
  }
  Kokkos::finalize();
}
```

Results:
```
// kokkos-dev-2
export OMP_NUM_THREADS=20
export OMP_PROC_BIND=close
export OMP_PLACES=cores
./test.host 100000 1000
GCC 6.1
KK  Time: 1.074618e-02
OMP Time: 1.425285e-02
KK  Time: 1.231607e-02
OMP Time: 1.396557e-02

Clang 8.0
KK  Time: 8.540976e-03
OMP Time: 9.762912e-03
KK  Time: 8.552720e-03
OMP Time: 9.739548e-03

ICPC 19.0
KK  Time: 3.116474e-03
OMP Time: 4.170151e-03
KK  Time: 3.123789e-03
OMP Time: 4.244643e-03
```

**Comment by crtrott** [comment]
That said: this doesn't mean we shouldn't try to get rid of the volatiles. The question is how to do that while making sure we don't have subtle race conditions etc. Relaxed atomic loads may work, and we can check whether that will keep the performance.

**Comment by alanw0** [comment]
ok we have to proceed. Unless there is a solution forthcoming in kokkos, we will prepare a pull-request with volatile overloads for Dan's (@ibaned ) simd header.

**Comment by crtrott** [comment]
I think this is the safest way to go right now. I have been looking at this code again and again, I think on the CUDA side we can fix this fairly straightforward now, but on the OpenMP side its gonna take time to figure it out in a way that it a) keeps performance where it is and b) doesn't introduce subtle race conditions. I mean I would love for the native reductions just to work but its all pretty ugly right now. Also it would require custom reductions to support SIMD, which we don't get with all the compilers we support (in particular older GCC).

**Comment by pkestene** [comment]
I've tried to use parallel_reduce on OpenMP with a simd native type (e.g. AVX) from kokkos/simd-math, but it seems to me that currently there is still another problem (see https://github.com/kokkos/simd-math/issues/34) regarding memory alignment.

Indeed, even after adding the += operator in simd type, each OpenMP thread initializes its partial reduction using a temp variable located in HostThreadTeamData, and this space is memory aligned using this (from Kokkos_HostThreadTeam.hpp)
```c++
  static constexpr int align_to_int64(int n) {
    return ((n + mask_to_16) & ~mask_to_16) >> shift_to_8;
  }
```
which at the end gives a pointer that is 16 bytes aligned, and using AVX simd it generates a run time seg fault.

If I just add a new alignement:
```c++
  enum : int { mask_to_32 = 0x1f };  // align to 32 bytes

  static constexpr int align_to_int128(int n) {
    return ((n + mask_to_32) & ~mask_to_32) >> shift_to_8;
  }
```
then, it works ok.

Did I miss something, or did something succeeding in making OpenMP parallel reduce work with simd types (from simd-math) without having to modify memory alignment like above ?

**Comment by PhilMiller** [comment]
The requirement for `volatile` in reductions was dropped in 3.7.
