### ISSUE TITLE
subview member function ?

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#280]
Now we have dynrankview and view and they have different subview syntax. If I receive a view with a template type, for instance
```
template<typeanme ViewType>
void function(ViewType a) {
  // either of two are needed
  auto sub = Kokkos::subview(a, 1, Kokkos::ALL());
  auto sub = Kokkos::subdynrankview(a, 1, Kokkos::ALL());

  // is this possible or other unified wayt to create a subview ? 
  auto sub = a::subview(a, 1, Kokkos::ALL());
  auto sub = decltype(a)::subview(a, 1, Kokkos::ALL());
}
```

**Comment by ndellingwood** [comment]
If I understand correctly, the template type ViewType may be either DynRankView of View, so you are wanting a generic subview call that works for both. 
Currently what you have (auto sub = a::subview(...) ) is not possible, the name change to subdynview was made due to some implicit conversions causing the compiler trouble deducing the proper subview. I can look back into that.

**Comment by kyungjoo-kim** [comment]
Yes.You got the point. If we have a generic subview, that would be the best. Alternatively my suggestion is to put static member function of subview under the view so that proper subview is derived from the view.

**Comment by hcedwar** [comment]
Need to resolve the 'subview' vs. 'subdynrankview' function resolution issue as opposed to adding a member function.

**Comment by ndellingwood** [comment]
@kyungjoo-kim 
With #359  can now use subview function with DynRankView
