### ISSUE TITLE
Less restrictive TeamPolicy reduction on Cuda

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#286]
Allow arbitrary team sizes and vector_length > 1 for reductions using TeamPolicy.

**Comment by mndevec** [comment]
My shared memory allocations seems to be failing in this case on GPUs for parallel_reduce.

I set the shared memory size to:
   size_t team_shmem_size (int team_size) const {
      return 16384;
    }

Then I try to allocate:
      char *all_shared_memory = (char *) (teamMember.team_shmem().get_shmem(16384));

This is working for parallel_for, but when I use parallel_reduce, my allocation appears to be null. I am not sure if it is really related to vector size, since it also fails when vector_size = 1 as well.
