### ISSUE TITLE
Deprecating Profiling::SpaceHandle

### ISSUE THREAD

**Issue by DavidPoliakoff** [kokkos/kokkos#2893]
SpaceHandle is just weird, and every time I describe it to people they're like "why does that work that way" and I'm like "dunno, seems like a bad idea to me." I talked with @crtrott, who also thinks it's broken.

Question 1) Should we kill SpaceHandle?

My answer is yes, feel free to disagree in the comments, this isn't set in stone. Stipulating that we should kill SpaceHandle, the question is how. There are three options for this.

1) Clean break change the interface of everything that has a SpaceHandle in its signature
2) Maintain two sets of symbols with different names
3) 2 until a major release (maybe two major releases, depending on timeframe), then 1

I'm leaning (3), but again, ideas are appreciated, nothing is set in stone here.

We'll likely replace the SpaceHandle with Ye Aulde Bitmaske, much like we did in #2824 for execution spaces.

Implementation plan:

1) Separate out the code reorg from tuning into its own PR
2) Assuming the "hold two interfaces til the major release" idea works, figure out the new symbol names. Implement profiling in terms of "if I found v2, load it, else look for v1"
3) Update tools where possible
4) Maintain this til a major (maybe two), then remove the branch that looks for v1

**Comment by mhoemmen** [comment]
It's a dlopen interface anyway, so why not let Kokkos ask the profiling library what interface version it requires, or let the profiling library ask Kokkos what interface version it provides?

**Comment by dalg24** [comment]
https://github.com/kokkos/kokkos/blob/82eb5bbf04212bb6322a87e9a6ee564d4e11db3e/core/src/impl/Kokkos_Profiling_Interface.hpp#L97-L100

**Comment by DavidPoliakoff** [comment]
@mhoemmen , I don't see what the query buys us, could you let me know what I'm missing? I'm being slow today.

If I try to dlopen `symbol_v2` and get it, the tool supports v2. If I get `nullptr`, I look for `symbol`, if I find it the tool supports v1. What benefit do we see from a model where I ask the tool directly what version it supports, rather than discovering it?

**Comment by mhoemmen** [comment]
@DavidPoliakoff wrote:
> If I try to dlopen `symbol_v2` and get it, the tool supports v2. If I get `nullptr`, I look for `symbol`, if I find it the tool supports v1.

That's what I meant, but I said it in a confusing way : - ) .

**Comment by wrwilliams** [comment]
My two cents: what I want out of the role that `SpaceHandle` currently fills is two things: fast equality comparison (in Score-P we'd like to group allocations into one metric per space) and any labelling that comes with that (which lets us assign meaningful names to those metrics--we assume and I hope reasonably so that the `name` parameter on alloc/dealloc is more fine-grained than the `SpaceHandle`). If the goal of `SpaceHandle` is to be, essentially, an enum-name mapping for a small number of enum values, is there a reason not to put a name lookup method into Kokkos for the profiling interface to use (or I guess have everyone implement their own, but this can/should be a header-only inline) so that we could do something like this:

```
kokkosp_initialize(...)
{
    ...
    for(int j=0;  j<KOKKOS_NUM_SPACE_HANDLES; j++)
    {
        metrics[j] = new Metric(..., kokkosp_spacehandle_name(j), ...);
    }
    ...
}

kokkosp_allocate(SpaceHandle h, const char* name, void* where, size_t size)
{
    record_alloc(metrics[h], where, size, name);
}
```
That would be far cleaner than my current approach, which has to be something like blindly convert SpaceHandle to char[64] and play either hash table or strncmp games to check whether we already have a corresponding metric.

**Comment by DavidPoliakoff** [comment]
Sorry to have taken people's time on this one. I could see this happening in the far future, but I don't see it happening any time soon, so I'm going to close this issue. In the event we decide to go down this road later I'll reopen or reference this issue
