### ISSUE TITLE
MemoryPool unit test hangs on Power8 with GCC 6.1.0

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#298]
This works with GCC 4.9.2 and GCC 5.3.0 on Power8. Can be reproduced on white.

```
~/kokkos/generate_makefile.bash --with-openmp --arch=Power8
make test
```

**Comment by gmackey** [comment]
This bug is still here.  Everything works with GCC 5.3.0.  With GCC 6.1.0, the serial version runs fine for all tests.  The OpenMP version runs fine for most tests but hangs for memory_pool and task_fib.  Both tests pass if run through valgrind, though.  Using print statements, it appears that the hang in the memory_pool test happens on the parallel_for() that allocates all the memory.  Execution makes to the end of the last iteration's execution of the functor body and then doesn't exit the parallel_for().  I will continue to investigate this.

**Comment by gmackey** [comment]
Oh.  I was testing on ride, so the bug occurs there, too.

**Comment by crtrott** [comment]
Yeah white and ride should be largely identical.

**Comment by nmhamster** [comment]
@gmackey @crtrott some of the environments between white and ride are now not identical as we are stepping white into the next generation of stack. Just make sure you are super careful with module loading for now while we make the changes. 

@gmackey I am also seeing this with Intel and GCC 6.1.0 as well (see #445).

**Comment by gmackey** [comment]
I just confirmed that the same two tests: memory_pool and task_fib are hanging on Intel and GCC 6.1.0.

**Comment by gmackey** [comment]
Just to clarify, I meant running on x86 compiled with GCC 6.1.0.

**Comment by nmhamster** [comment]
@gmackey can confirm I am also seeing a similar hang on ARMv8 with GCC 6.1.0 using `develop`.
