### ISSUE TITLE
Kokkos::initArguments guidance

### ISSUE THREAD

**Issue by kvmatsuno** [kokkos/kokkos#3002]
We are looking to optimize our code; our two preferred platforms are (i) GPU distributed memory parallelized with MPI and (ii) CPU distributed memory parallelized with OpenMP/MPI. 

We would like to customize the kokkos initialization arguments (listed at
https://github.com/kokkos/kokkos/blob/master/core/src/Kokkos_Core.hpp#L104-119)

~~~
  int num_threads;
  int num_numa;
  int device_id;
  int ndevices;
  int skip_device;
~~~
What do the above parameters mean, how are they defined, and how should we set them for our preferred platforms mentioned previously?

Also, is there likely to be a large impact on performance using the default settings versus customized ones?

**Comment by dalg24** [comment]
These are documented in the wiki [here](https://github.com/kokkos/kokkos/wiki/Initialization#initialization)

**Comment by kvmatsuno** [comment]
Thanks for the reply. We are looking for some more specific answers to these questions:

1. What it the definition of num_numa  for GPU nodes (there was an example on the linked page, but it is still unclear to us for our desired platforms) 
2. Will performance will be significantly hurt with the default settings
3. If the device parallelization is CUDA, will num_threads still be used in the code? If so, what is the exact definition of num_threads? 
4. Do num_threads and num_device mean the total number of a computation job or a numbers for each node?

**Comment by crtrott** [comment]
* num_threads and num_numa only mean anything for CPU. 
* num_numa only has meaning if you enable hwloc as a TPL. 
* device_id is if you want to set which GPU to use from an MPI rank
* ndevices together with skip_device can be used to round-robin assign GPUs to MPI ranks (we use internally stuff like OMPI_LOCAL_RANK environment variable to discover this layout). Essentially you get device_id = local_rank%ndevices; if(device_id>=skip_device) device_id++;

Skip device is meant for desktops where you have a display GPU. By default ndevices is 1. We are planning to change that. 

If you use OpenMP we recommend using the OpenMP environment variables to provide CPU thread binding.

**Comment by songhanglucky** [comment]
Thank you so much for the reply. Following up with the answers for GPU clusters, how should we set `ndevices` and `device_id`, for example, if we want to run the code using 8 GPUs on two compute nodes where each node has 4 GPUs, and we desire one MPI process per GPU?

Also, if we use a generic MPI library other than OMPI, e.g., MVAPICH2, do we need to do any extra work since you mentioned the default setting uses `OMPI_LOCAL_RANK`?

**Comment by masterleinad** [comment]
Since https://github.com/kokkos/kokkos/pull/3013, the number of devices should be auto-detected if you don't specify it. You should set `ndevices` to the number of local devices (4) and `device_id` to a value between 0 and 4 (inclusive).

If you don't specify `device_id` the local MPI rank is used and this should also work for `MVAPICH2`, see
https://github.com/kokkos/kokkos/blob/7933c2e4b9c83a4d99101acbf2ae06a1115f50d5/core/src/impl/Kokkos_Core.cpp#L205-L210

**Comment by PhilMiller** [comment]
Based on recent improvements to MPI context detection in #5576, #5525 and others, I think we can close this as obsolete.
