### ISSUE TITLE
ThreadTeam vector level parallelism API

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#301]
The thread team vector level parallel_for currently requires a ThreadVectorRange policy constructed from a TeamPolicy::member_type object.  While this provides a consistent API the object is actually unnecessary to the implementation.  Vector level parallelism would be easier to use within functions called by a TeamPolicy kernel if the object were not required.
Reevaluate this design and API decision, and revise API and implementation accordingly.

**Comment by hcedwar** [comment]
Concern with having implied TeamThreadRange execution context within a function that performs a ThreadVectorRange.  Without an explicit handle for the execution context there is no way to detect whether the ThreadVectorRange is called within the proper context.  Removing the member_type is not a good path.  
Follow on: In debug mode should verify that the execution context is proper within the hierarchy.

**Comment by crtrott** [comment]
I just had another email exchange about this. Here is a longer explanation and a workaround for people who really want this:

The reason that we don't publicly expose a standalone VectorPolicy is that you may loose track of whether you are in a redundant execution mode or not.

For example take this:

```c++
KOKKOS_INLINE_FUNCTION
double bar(const int& i, const int& j) {
  double val;
  parallel_reduce(VectorPolicy(K), [&] (const int& l, double& tmp) {
     tmp+=b(i,j,l);
  }, val);
  return val;
}

KOKKOS_INLINE_FUNCTION
void foo(const int& i, const int& j) {
   ....
   auto val = bar(i,j);
   atomic_add(&a(i,j), val);
  
}

parallel_for(TeamPolicy<>(N,4,8), KOKKOS_LAMBDA (const t_team& team) {
   int j = team.league_rank();
   int i = team.team_rank();
   foo(i,j);
});
```
inside of "foo" there is no hint whatsoever that the atomic may need to be protected by a single statement, since on GPUs this statement is redundantly executed by all 'vector lanes'. If foo has to take a team handle in order to pass it on to bar, then you would at least need to think: 'Oh there is a team_policy going on somewhere do I need to protect this atomic?'.

That said there is a way to do this by relying on Impl namespace capabilities. The thing is we actually don't need the TeamHandle to create a vector loop. Only the user facing interface requires it. Thus you can avoid it by going to the internal one:

```c++
#include<Kokkos_Core.hpp>

int main(int argc, char* argv[]) {
  Kokkos::initialize(argc,argv);

  int N = 100000;
  int M = 32;
  Kokkos::View<double**> a("A",N,M);
 
  //Defining a free VectorPolicy
  typedef Kokkos::TeamPolicy<>::member_type t_team_handle;
  typedef Kokkos::Impl::ThreadVectorRangeBoundariesStruct<int,t_team_handle> VectorPolicy;
 
  Kokkos::parallel_for(N, KOKKOS_LAMBDA (const int &i) {
    Kokkos::parallel_for(VectorPolicy(M), [&] (const int& j) {
      a(i,j) = 100*i+j;
    });
  });

  Kokkos::finalize();
}
```
