### ISSUE TITLE
Best way to handle memory trait combinations

### ISSUE THREAD

**Issue by dholladay00** [kokkos/kokkos#306]
My application broke when I updated Kokkos. I'm guessing it is likely related to issue #282. 

Initially I had: 

```c++
template < class D, class ... Q >
using Vector_t = View<D*, MemoryUnmanaged, Q ... >;
``` 

with the goal of being able to add memory traits such as `Kokkos::Atomic` like `Vector_t<double, Kokkos::Atomic>` or `Vector_t<const double, Kokkos::RandomAccess>`. That of course won't work as memory traits don't work that way.

Has anyone come upon a similar issue and already come up with an elegant and compact solution?

**Comment by hcedwar** [comment]
If `Q...` does not contain a trait then `View<D*,Q...,MemoryUnmanaged>` should work.

**Comment by dholladay00** [comment]
That is good to know. 

My question is if i did want to pass in a memory trait, say Kokkos::Atomic: `Vector_t<double, Kokkos::Atomic>`, is there a nice way to set up the template alias such that it would give me `View<double*, MemorTraits< Unmanaged | Atomic > >`?

**Comment by crtrott** [comment]
Actually the thing before didn't necessarily do what you thought it would do and we changed Kokkos to catch that. In particular the order of arguments is fixed for Views, you can't for example define MemorySpace after MemoryTraits. 

Therefore `Vector_t<double,HostSpace>` wouldn't actually give you HostSpace if you enable Cuda since it would come down to `View<double*,Unmanaged,HostSpace>`. The HostSpace would have gotten silently ignored and it would have been the same as `View<double*,Unmanaged>`. Now we fail to compile. 

To get what you want you could use something like:
```C++
template<class Traits, unsigned Attribute>
struct AppendTraits;

template<class Args, unsigned Attribute>
struct AppendTraits<MemoryTraits<Args,Attribute> {
  typedef MemoryTraits<Args|Attribute> memory_traits
};

typedef View<........> view_type;
typedef View< view_type::data_type,
                        view_type::array_layout,
                        view_type::device_type,
                        AppendTraits<view_type::memory_traits,Atomic>::type> view_atomic_type;
```

**Comment by dholladay00** [comment]
I went with: 

```c++
const unsigned int un = Unmanaged;
const unsigned int at = Unmanaged | Atomic;

template < class D, unsigned MT, class ... Q >
using Vector_t = View<D*, Q ..., MemoryTraits< MT > >;

Vector_t<double, un> A;
Vector_t<double, at> B; 
```

It would be nice to have `un` as the default unsigned int, but this works well enough. This issue can be closed.
