### ISSUE TITLE
Building Kokkos on Windows in Visual Studio

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#3063]
This is a step by step instructions to build Kokkos and its test in Visual Studio. 

The short variant is this:

- Common to any Configuration:
  - clone Kokkos via File->Clone Or Check Out Code
  - Change CMake settins to turn `Kokkos_ENABLE_TESTS=ON` and `Kokkos_ENABLE_LIBDL=OFF` and `Kokkos_ENABLE_PROFILING=OFF`
- Serial Build:
  - configure
  - build
- CUDA Build
  - *Currently:* checkout the develop branch
  - Create new cmake configuration based on visual studio X64-Release
  - Edit the JSON file to not inherit any environment
  - Turn `Kokkos_ENABLE_CUDA=ON` and the appropriate GPU architecture such as `Kokkos_ENABLE_TURING75=ON`
  - Add CMake command arguments to set `CMAKE_CXX_COMPILER=nvcc`, `CMAKE_CXX_FLAGS="-ccbin PATH_TO_MSVC`, `CMAKE_AR=PATH_TO_VS_LLVM_AR/llvm-ar.exe` and `CMAKE_LINKER=PATH_TO_VS_LLVM_LINK/lld-link.exe`
    - e.g. : `-DCMAKE_CXX_COMPILER=nvcc -DCMAKE_CXX_FLAGS="-ccbin \"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\bin\HostX64\x64\" " -DCMAKE_LINKER="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/Llvm/bin/lld-link.exe" -DCMAKE_AR="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/Llvm/bin/llvm-ar.exe"`
    - Note the extra slash for the `CMAKE_CXX_FLAGS` nested `"`. This is how to enter this into the GUI, in the JSON file extra escape args must go in. 
  - configure
  - build

I will post a longer variant with screenshots. 

*NOTE:* I did NOT create a visual studio project and DO NOT have *.sln file.

**Comment by crtrott** [comment]
My JSON file after the steps above:
```
{
  "configurations": [
    {
      "name": "x64-Debug",
      "generator": "Ninja",
      "configurationType": "Debug",
      "inheritEnvironments": [ "msvc_x64_x64" ],
      "buildRoot": "${projectDir}\\out\\build\\${name}",
      "installRoot": "${projectDir}\\out\\install\\${name}",
      "cmakeCommandArgs": "",
      "buildCommandArgs": "-v",
      "ctestCommandArgs": "",
      "variables": [
        {
          "name": "Kokkos_ENABLE_LIBDL",
          "value": "False",
          "type": "BOOL"
        },
        {
          "name": "Kokkos_ENABLE_PROFILING",
          "value": "False",
          "type": "BOOL"
        },
        {
          "name": "Kokkos_ENABLE_TESTS",
          "value": "True",
          "type": "BOOL"
        }
      ]
    },
    {
      "name": "Cuda-Release",
      "generator": "Ninja",
      "configurationType": "RelWithDebInfo",
      "buildRoot": "${projectDir}\\out\\build\\${name}",
      "installRoot": "${projectDir}\\out\\install\\${name}",
      "cmakeCommandArgs": "-DCMAKE_CXX_COMPILER=nvcc -DCMAKE_CXX_FLAGS=\"-ccbin \\\"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX64\\x64\\\" \" -DCMAKE_LINKER=\"C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/Llvm/bin/lld-link.exe\" -DCMAKE_AR=\"C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/Llvm/bin/llvm-ar.exe\"",
      "buildCommandArgs": "-v",
      "ctestCommandArgs": "",
      "inheritEnvironments": [],
      "variables": [
        {
          "name": "Kokkos_ARCH_VOLTA70",
          "value": "True",
          "type": "BOOL"
        },
        {
          "name": "Kokkos_ENABLE_LIBDL",
          "value": "False",
          "type": "BOOL"
        },
        {
          "name": "Kokkos_ENABLE_PROFILING",
          "value": "False",
          "type": "BOOL"
        },
        {
          "name": "Kokkos_ENABLE_TESTS",
          "value": "True",
          "type": "BOOL"
        },
        {
          "name": "Kokkos_ENABLE_CUDA",
          "value": "True",
          "type": "BOOL"
        },
        {
          "name": "Kokkos_ENABLE_CUDA_LAMBDA",
          "value": "True",
          "type": "BOOL"
        }
      ]
    }
  ]
}
```

**Comment by benc303** [comment]
FYI: I did some experimenting with using `nvcc_wrapper` to compile on Windows. I’m using CMake directly in a CYGWIN shell environment, with the `NMake Makefiles JOM` generator. The issue is that CMake runs the compiler program, specified by `CMAKE_CXX_COMPILER`, as a Windows executable, not just something that can be run from the current shell environment. So I wrote a little wrapper (of a wrapper) DOS batch script that takes all the arguments to `nvcc_wrapper`, single-quotes them to avoid parsing the spaces and backslashes that show up in Windows paths, and passes them to Kokkos’ `nvcc_wrapper` launched with `bash -c` (using the bash for CYGWIN).

This configures successfully from Trilinos/master, with a few small changes to `nvcc_wrapper` and some Trilinos CMake files. The build fails though, since CMake identifies the compiler as MSVC, so it passes MSVC options in a response file (i.e. `@<file containing MSVC options>`. So `nvcc_wrapper` would need to be modified to parse options from the response file just as it parses them from the command line. Also, the DOS batch script would need to be modified to pass environment variables into the bash environment it uses to run `nvcc_wrapper`.

The DOS batch script is [attached here](https://github.com/kokkos/kokkos/files/5215189/nvcc_wrapper.bat.txt) (remove the `.txt` extension; GitHub doesn’t allow `.bat`s). Also I can create a Trilinos branch for the few changes I made there if you want to look at this further.

**Comment by kurtsansom** [comment]
I tried doing this in the windows command line with cmake I get that same ` nvcc fatal   : Don't know what to do with 'C:/FS'` error

here is the command I used with cmake in the PATH, and I added carriage returns to make it readable
```
cmake -G Ninja -DCMAKE_MAKE_PROGRAM="C:/Users/kurt.sansom/tools/ninja-win/ninja.exe" 
-DKokkos_ENABLE_CUDA=ON -DKokkos_ENABLE_MAXWELL50=ON 
-DCMAKE_CXX_COMPILER="C:/Users/kurt.sansom/tools/cuda_11.1.1_456.81_win10/cuda_nvcc/nvcc/bin/nvcc.exe" 
-DCMAKE_LINKER="C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/Llvm/bin/ldd-link.exe"  
-DCMAKE_AR="C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/Llvm/bin/llvm-ar.exe" 
-DCUDA_HOST_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/Llvm/bin/clang-cl.exe"  ..\kokkos
```

**Comment by PhilMiller** [comment]
This should get added to the documentation, where it'll be readily found.

**Comment by 5ch0** [comment]
The problem comes after this：
![result](https://github.com/kokkos/kokkos/assets/158433114/11380c63-f45a-46e2-873f-7f1fa8b36d85)

**Comment by masterleinad** [comment]
Please follow what we are doing in our CI: https://github.com/kokkos/kokkos/blob/2035e313d7a54f9e1572eb5f315249ea841fb258/.github/workflows/windows.yml#L31.
