### ISSUE TITLE
Smaller inner loops yield longer runtime on CPU

### ISSUE THREAD

**Issue by mcarilli** [kokkos/kokkos#313]
Hello Kokkos Team,

I'm witnessing some strange CPU behavior of a kernel in which each thread iterates across its own private 2D data segment.  It's the same kernel I asked Christian to look at [earlier](https://github.com/kokkos/kokkos/issues/240#issuecomment-210663414), with hoisted loads and a simd reduction (the placement of the simd pragma was selected by trial and error for best performance).  Christian, I decided not to go with the hierarchical version you wrote, because the version presented here appears to offer better performance on the CPU.

Here is my problem:  The parameter `ns` controls the size of the per-thread 2D subarrays, as well as the trip count of the inner loops within the kernel.  I ran the kernel in single-threaded CPU mode for varying values of `ns`, and naturally expected that runtime would decrease as `ns` decreased.  Runtime does decrease, but in a sawtooth fashion:  every 8 values of `ns` there is a spike.  A reasonable hypothesis is that within each thread's inner loops, accesses to the 2D subarrays lose cache/vector alignment for certain values of ns.  However, I tried writing two additional versions of the kernel with different memory padding strategies to correct the issue, and all exhibited the same sawtooth behavior.

**Control Case** (no padding):  [pseudo2D_no_padding.cpp.txt](https://github.com/kokkos/kokkos/files/294564/pseudo2D_no_padding.cpp.txt)
Each grid point's 2D subarray is allocated and accessed as a pseudo-2D array.
Allocation example:  `View2D input3( "input1", nGridPoints, ns*ns )`
Access example    :  `input3( threadIdx, i + j*ns )`

**Padded Version 1**:  [pseudo2D_manual_padding.cpp.txt](https://github.com/kokkos/kokkos/files/294567/pseudo2D_manual_padding.cpp.txt)
Each grid point's 2D subarray is allocated and accessed as a manually padded pseudo-2D array. 
Allocation example:  `View2D input3( "input1", nGridPoints, nsp*nsp )`
Access example    :  `input3( threadIdx, i + j*nsp )`
(`nsp` is `ns`, padded to a multiple of 8 doubles.)

**Padded Version 2**:  [kokkos_padding.cpp.txt](https://github.com/kokkos/kokkos/files/294569/kokkos_padding.cpp.txt)
Here, the allocation is a 3D array, and I use [the built-in Kokkos padding](https://github.com/kokkos/kokkos/issues/273)
Allocation example:  
```
View3D input3(Experimental::view_alloc("input3",Kokkos::Experimental::AllowPadding), nGridPoints, ns, ns);
```
Access example  :  `input1( threadIdx, i, j )`

Here is a plot of the runtimes for each kernel as ns is varied, showing the sawtooth pattern:
![runtime_vs_ns_sawtooth](https://cloud.githubusercontent.com/assets/7799218/15729457/3192ca02-2819-11e6-872c-6dce80942dff.png)

Here is the makefile used to build all examples:  [Makefile.txt](https://github.com/kokkos/kokkos/files/294574/Makefile.txt)

My CPU is an Intel E5-2650 v3 with 64-byte cache lines, and I compiled for avx2, if any of that helps.

It's quite possible I am misunderstanding how to properly align the data.  Do you have any thoughts?  I'm also curious as to why the version using Kokkos' built-in padding is so much slower.

Thanks very much for your help,
Michael

**Comment by crtrott** [comment]
Hi

I need to look a bit more into it. But a couple of things I saw immediately is that for example your memory access patterns are not the same in the different versions. The 3D array version the way you use the indexing doesn't give you stride 1 access in a couple cases where your 2D array version does. That is probably the main reason why the 3D padding version is slower. Also the padding in the Kokkos Views pertains to the per-thread iteration space. In case of LayoutRight that means we pad the first dimensions, so that different threads don't share cachelines. It does not pad the third dimension for vector alignment. That said I need to look a bit more into it to see what the compiler is actually doing.

Christian

**Comment by mcarilli** [comment]
Hi Christian,

Thanks for looking into it.  You're right about the different access strides for the last two indices between my pseudo-2D arrays and the 3D arrays:  for LayoutRight, `input1(t,i,j)` is equivalent to `input1(t,j+i*ns)`, not `input1(t,i+j*ns)`.  I tried reversing the order of those last two indices in kokkos_padding.cpp (eg. changed every input(t,x,y) to input(t,y,x) ) and found that the runtime reduced by over 2x, approaching the pseudo-2D runtimes more closely.  For example, for 50 species, the kokkos_padding version now runs in 2.53 seconds (instead of 6.2ish as shown in the graph above). 

I'm still at a loss about the sawtooth pattern though.  As I said, my naive attempt to manually pad for cache and vector alignment seemed to have no effect.  I should mention that [I previously asked H. Carter Edwards](https://github.com/kokkos/kokkos/issues/273#issuecomment-217969190) about how exactly the Kokkos padding worked, and he claimed that the second-through-last dimensions, rather than the first dimension, are padded for cache alignment (which should ensure vector alignment as well, since the fastest dimension would be padded).

Much appreciated,
Michael

**Comment by crtrott** [comment]
Regarding the padding: I expressed myself a bit inaccurate. What I meant is that we pad in a way that for Layouright the stride of dimension 0 is changed. If you just pad the last dimension of a 3D view stride of dimension 1 would be changed versus the unpadded version. 

My suspicion for the saw pattern: your code gets twice unrolled and then vectorized. Since the loop length is ns-1 you would then expect optimal performance at ns%8=1. The reason being that the non full vectorized thing is probably run as a scalar peel loop instead of a masked loop. 

But again to verify that we would need to run some very deep profiling with instruction catching.

**Comment by nmhamster** [comment]
The VPUs on Haswell do not have masking in the sense you are describing them here, the mechanism by which this happens on platforms prior to AVX512 is quite complex and so is almost always run in the following pattern: (1) prologue loops to get into alignment; (2) vector loops; (3) remainder loops. On HSW (3) is almost always scalar since a specific set of circumstances have to happen otherwise. From AVX512 onwards the compiler will be able to decide what to do with (1) and (3) in terms of masks. The choice there will be down to the expense of having mask generation included in the main vector loop versus splitting off epilogue and prologue loops.

**Comment by crtrott** [comment]
Si is obviously right. I should have been clearer on that. The masking option (which should not show a saw pattern in the ideal case but more like a step function) could possibly happen on KNL, and would almost surely happen on GPUs if you were to use hierarchical parallelism (e.g. you expose the inner two levels through team and vector level parallelism).

**Comment by mcarilli** [comment]
You can close this issue if you want.  I can easily pad the loop trip counts as well as the memory (with the last few iterations potentially operating on dummy data) to ensure the runtime vs ns plot looks like a series of step functions instead of the sawtooth pattern.  I was mostly wondering why I got the sawtooth pattern even with padded memory.
