### ISSUE TITLE
Extend Kokkos::DualView Resize to support Kokkos::WithoutInitializing Option

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#3342]
In #2285, the `Kokkos::WithoutInitializing` option was added to `Kokkos::resize`. However, this only works for a regular `Kokkos::View`. Can this also be extended to `Kokkos::DualView`?

**Comment by crtrott** [comment]
yes

**Comment by Char-Aznable** [comment]
@masterleinad I have a related question. For a host-only dualview like `DualView<int*, HostExecutionSpace> v("v", 3);`,  resizing by `resize(Withoutinitializing, v, 6);` will result in a memory size peak where the memory size is `view of 3 int plus view of 6 int`, is that right? I think this is because the old memory allocation is only given up after the create_mirror_view call judging from the code:
https://github.com/kokkos/kokkos/blob/ae5fc649ef4b62b48a01123759ed066bff227b43/containers/src/Kokkos_DualView.hpp#L942-L961

**Comment by masterleinad** [comment]
Yes, `resize` copies the old content over so we create the new view before destroying the old allocation (even when `WithoutInitializing` is requested).

**Comment by Char-Aznable** [comment]
Is it possible to do something like this in the above code so to avoid the memory peak:
```c++

   if (modified_flags(1) >= modified_flags(0)) { 
     /* Resize on Device */ 
     if (sizeMismatch) {
       h_view = decltype(h_view)();
       ::Kokkos::resize(d_view, n0, n1, n2, n3, n4, n5, n6, n7); 
       h_view = create_mirror_view(d_view); 
  
       /* Mark Device copy as modified */ 
       modified_flags(1) = modified_flags(1) + 1; 
     } 
   } else { 
     /* Realloc on Device */ 
     if (sizeMismatch) {
       d_view = decltype(d_view)();
       ::Kokkos::resize(h_view, n0, n1, n2, n3, n4, n5, n6, n7); 
       d_view = create_mirror_view(typename t_dev::execution_space(), h_view); 
  
       /* Mark Host copy as modified */ 
       modified_flags(0) = modified_flags(0) + 1; 
     } 
   } 
```
since the mirror view has to be reconstructed anyway

**Comment by masterleinad** [comment]
We could do this (but I suspect you would still see a peak in memory since `resize` needs to have two allocations alive at the same time). I think it's best if you just open a pull request.
