### ISSUE TITLE
Per thread Scratch memory from a RangePolicy

### ISSUE THREAD

**Issue by glesur** [kokkos/kokkos#3427]
Hi,

I'm implementing a cfd code with Kokkos. I've had some experience with CUDA in the past, and I know that it's best to use cuda shared memory for intermediate computations.  In cuda, this is easily done using the __shared__ memory keyword.

On kokkos, as I understand it, one needs a TeamPolicy to allocate scratch memory (which I understand is the equivalent of cuda shared memory when executationspace=cuda). In particular, there is no way to get access to this scratch memory from a RangePolicy. That's an issue for me because my loops do not require an explicit access to team/threads and it would add a significant layer of unneeded complexity to the code.

Now, I would just need a per-thread shared memory, just like I would do with cuda __shared__ memory keyword. Why isn't it possible to do this from a simpler RangePolicy?

Thanks!

**Comment by crtrott** [comment]
What is the actual use case for per thread scratch you have in a range policy? Generally speaking at least since Pascal/Volta generation the L1 cache combined with potentially spilled registers does at least as good a job as shared memory in my experience if its pure per thread access (i.e. you don't use it to actually share access).

**Comment by crtrott** [comment]
Yeah: so on those architectures (even more so on Volta) L1 cache and Shared memory are pretty much equivalent, and local load/stores (which this array leads too) are cached at the L1 level. Generally I found for this use case that local load/stores are working actually better than shared since you don't have to mess with the layout and bank conflicts etc. The arrays are effectively interleaved on a warp level granularity. One problem is the amount of memory you need. L1 cache even at its max (same for shared memory) is less than 100kB. At 7 * 8 * 2048 (full occupancy) you run out. What is the achieved occupancy for your kernel btw? 

We are adding a feature which lets you limit the occupancy at demand, which means more L1 cache per thread is available. We have seen 2x performance improvements for a number of kernels reasonably often. At the outsight even 6x. Whats the performance difference between the register based and the local array based version?

One thing you can also look at is the different memory metrics to figure out where your accesses are going: global load/store, L2 read/write, DRAM read/write, local load/store.

**Comment by glesur** [comment]
So on the largest loops (Riemann solver), we go down to 12.5% of occupancy, 
mostly due to register limitation (in the implementation where temporary 
arrays are transformed into variable series, stored in registers). 
Decreasing maxregcount increases the occupancy (register spilling) but it 
leads to weaker performances. It could mean that we use more memory than 
available in L1, or just that L1 is slower than registers. I'll check that.

I believe in our case, the optimum would be to store all of these temporary 
arrays in registers, even if it means decreasing the occupancy. I don't 
know if it's possible to ask this to the compiler or to kokkos though. 
Clearly, decreasing the occupancy for some kernels seems to help, so if 
this feature is included in kokkos in the future, I think we would be 
interested.





Le 28 septembre 2020 18:55:54 Christian Trott <notifications@github.com> a 
écrit :

**Comment by crtrott** [comment]
One thing you need to remember is that you have actually twice as much register memory as L1 and Shared Memory combined (256kB vs 128kB). So if 12.5% occupancy is due to register usage that means going from 12.5% to 25% via spilling will increase your total per thread state from 256kB to 512kB per SM. Of that 512kB 256kB will still be in registers but the other 256kB come from global memory and are potentially cached. Even if you don't use any additional shared memory you won't cache more than maybe a third or less of it though (since all other data accesses also get cached and will evict some of your spilled register state). But even if you don't have any other data accesses, the 256kB per SM will lead to 80*256kB = 20MB of L2 request which exceeds the L2 by over 3x.
