### ISSUE TITLE
Decide what to do with Kokkos_CXX_STANDARD

### ISSUE THREAD

**Issue by dalg24** [kokkos/kokkos#3432]
_Originally posted by @ndellingwood in https://github.com/kokkos/kokkos/pull/3425#issuecomment-700209474_

**Comment by jjwilke** [comment]
I generally don't like the idea of having variables named `CMAKE_YYY` have consequences for downstream projects.  If really intend for something to be a transitive aspect of the build, it's nice to have an idiom that `Kokkos_YYY` sets someting that is true for Kokkos and all downstream projects.

If we want to make an exception in the case of CMAKE_CXX_STANDARD, that's fine.  CMAKE_CXX_STANDARD has a specific meaning in the context of CMake - and is probably the WORST variable in all of CMake. It just means "please do your best to make this my C++ standard if you can".  Kokkos_CXX_STANDARD sets a compiler feature that means "no, I absolutely need 14, 17, etc". We would be somewhat changing the meaning of CMAKE_CXX_STANDARD for Kokkos (which, again, is probably fine).

What I'm more afraid of is that setting CMAKE_CXX_STANDARD changes the way cmake tests compiler features.  We don't want to require downstream projects to set CMAKE_CXX_STANDARD. In fact, this should almost be discouraged. You should inherit the C++ standard from Kokkos.  But this means that Kokkos might build and install successfully with CMAKE_CXX_STANDARD set. Then the downstream project fails to configure because it doesn't have CMAKE_CXX_STANDARD set. 

If we want to abandon Kokkos_CXX_STANDARD, that's probably fine. But then we need a way to test builds where CMAKE_CXX_STANDARD is not set.

**Comment by crtrott** [comment]
Can we take whatever comes out of CMAKE_CXX_STANDARD and then require that as a language feature also for downstream?

**Comment by jjwilke** [comment]
Yeah, we can do that. This really just comes down to coming up with a testing scheme. 

* Building with compiler feature "cxx_std_14" and CMAKE_CXX_STANDARD=14 is not equivalent to building to with compiler feature "cxx_std_14" and CMAKE_CXX_STANDARD unset.  We need to make sure downstream projects can configure and build correctly both ways
* We need to at least make sure we can configure with all supported compilers

**Comment by jrmadsen** [comment]
Why don't we set `CXX_STANDARD` as a target property on `Kokkos::kokkoscore`? Also, I always set `CMAKE_CXX_STANDARD_REQUIRED` to ON and never have had an issue with it not setting the standard.

**Comment by jjwilke** [comment]
The issue is downstream projects. We can do all of this while building Kokkos, but have no good way to translate this to downstream apps. If your build only relies on `cxx_std_14` as a compiler feature, the Kokkos test suite and downstream apps are all building the same way. If you rely on any of the `CXX_STANDARD` stuff, the Kokkos test suite and downstream apps will build under slightly different CMake conditions.

**Comment by jrmadsen** [comment]
Ah I forgot the CXX_STANDARD property isn't transitive in the install. I think we should get rid of Kokkos_CXX_STANDARD in the build tree but configure that variable to the value of CMAKE_CXX_STANDARD in the installation so the user can check it if need be and then continue to use the compiler feature in the build tree the way we currently do with Kokkos_CXX_STANDARD but replace the evaluation based on the value of CMAKE_. Unless I'm overlooking something, if we set the compile feature based on Kokkos_*, setting it via the CMake one should be straightforward.

**Comment by jjwilke** [comment]
Yeah, I have no objection to changing this and getting rid of Kokkos_CXX_STANDARD.  We'll need to keep it around as a deprecated option for a while, but we've been doing that with Trilinos where I auto-translate the option and unset it in the cache.
