### ISSUE TITLE
Questions regarding atomic operations

### ISSUE THREAD

**Issue by hudakoulani** [kokkos/kokkos#3656]
Hi,
I am working with Kokkos and I have some questions about it that I would like to ask.
Have I got it right that I can use the std library when I am programming with Kokkos? The wiki says that some of std::* classes are not supported and are replaced with alternatives from Kokkos. So regarding this statement all other functionalities from std should work, right? 
Regarding atomic operations, there is an atomic operations library in std. So why does Kokkos present his own atomic operations and not use the usual from std library? 

Thanks,
Huda

**Comment by crtrott** [comment]
Did we really say "some"? A lot of std classes are not portably supported. Like std::atomics don't work on GPUs, none of the containers work. Most functions don't work. The only stuff which works reasonably reliable are traits. Even math functions don't anymore - which is why we added our own wrappers now.
