### ISSUE TITLE
Nested parallel_reduce not initialising.

### ISSUE THREAD

**Issue by jamuus** [kokkos/kokkos#375]
The following code doesn't seem to working as expected. The init in functor d1 isn't called resulting in a default value of update being 0.

```
#include <Kokkos_Core.hpp>
using namespace Kokkos;

struct d1 {
    typedef double value_type;
    KOKKOS_INLINE_FUNCTION
    void operator()(const int& x, value_type& update) const
    {
        if (x < update)
            update = x;
    }

    KOKKOS_INLINE_FUNCTION
    void init(value_type& dst) const
    {
        printf("2\n");
        dst = 20.0;
    }
};

struct d2 {
    typedef double value_type;
    KOKKOS_INLINE_FUNCTION
    void operator()(TeamPolicy<>::member_type const& member, value_type& update) const
    {
        d1 f1;
        double result;
        parallel_reduce(TeamThreadRange(member, 4), f1, result);
        if (result < update)
            update = result;
    }

    KOKKOS_INLINE_FUNCTION
    void init(value_type& dst) const
    {
        printf("1\n");
        dst = 10.0;
    }
};

int main(int argc, char** argv)
{
    initialize(argc, argv);
    double min = 100.0;
    d2 f2;
    parallel_reduce(TeamPolicy<>(4, AUTO), f2, min);
    printf("%e\n", min);
    finalize();
}
```

**Comment by hcedwar** [comment]
The team nested parallel pattern behavior is inconsistent with respect to the global parallel pattern.  The optional nested parallel join functor or lambda uses `operator()` instead of function `join` and does not support initialization.  The initialization value is the initial value of the `result` argument, which is input/output.
Resolution of this inconsistency is a to-be-done.

**Comment by jamuus** [comment]
I've tried setting `result` but `update2` isn't initialised to that value as seen in the following code.

```
#include <Kokkos_Core.hpp>
using namespace Kokkos;

struct d1 {
    typedef double value_type;
    KOKKOS_INLINE_FUNCTION
    void operator()(const int& x, value_type& update2) const
    {
        printf("2 %e\n", update2);
    }
};

struct d2 {
    typedef double value_type;
    KOKKOS_INLINE_FUNCTION
    void operator()(TeamPolicy<>::member_type const& member, value_type& update1) const
    {
        printf("1 %e\n", update1);
        d1 f1;
        double result = 4.0;
        parallel_reduce(TeamThreadRange(member, 4), f1, result);
    }

    KOKKOS_INLINE_FUNCTION
    void init(value_type& dst) const
    {
        dst = 2.0;
    }
};

int main(int argc, char** argv)
{
    initialize(argc, argv);
    double min = 1.0;
    d2 f2;
    parallel_reduce(TeamPolicy<>(4, AUTO), f2, min);
    printf("\n%e\n", min);
    finalize();
}
```

**Comment by crtrott** [comment]
It does initialize if you give it an explicit join operator. Otherwise it initializes with default constructor. One of the reasons is that the initial value MUST be the neutral element with respect to the join operator.  Also if we would always expect an init value it would be an error to give  a reference to an unitialized variable.

This should work:

parallel_reduce(TeamThreadRange(member,4),f1,[&](value_type& val, const value_type& update) { val += update;},result).

As Carter set a unification with the improved generic reductions at the non-nested level is planned.

**Comment by jamuus** [comment]
The value still doesn't seem to be initialised with the given code snippet. I replaced the code in my example with the following.

```
d1 f1;
double result = 4.0;
parallel_reduce(TeamThreadRange(member, 4), f1, [&](value_type & val, const value_type & update) {
    val += update;
}, result);
```

Is there a better method for a 2d reduction that I'm missing?

**Comment by hcedwar** [comment]
This needs to be done in the greater context of consistent interface for custom reductions between global and nested.

**Comment by ibaned** [comment]
@crtrott we need to review what is required here

**Comment by crtrott** [comment]
This had been resolved a long time ago. Custom Reducers will allow you to set an initiaalization thing for nested reducers (I just tested that). Note the initial value of "result" is still not going to be used.
