### ISSUE TITLE
Impossible to modify objects in a kernel

### ISSUE THREAD

**Issue by zaphod41** [kokkos/kokkos#3775]
Hello,

I have a template object containing a pointer to a  Kokkos::View<T*, Kokkos::CudaSpace>. Unfortunately, I seem unable to modify it inside a kernel.

I obtain the following compilation error:

error: expression must be a modifiable lvalue

If I remove the const operator[], it gives:

error: no operator "[]" matches these operands
operand types are: const test<int> [ const int ]

It's as if the object was captured in the lambda as a reference to a const. Would there be a way to change that?

Thanks!

**Comment by dalg24** [comment]
Please post a minimum reducer.

**Comment by zaphod41** [comment]
Hello,

Thank you for your reply.

Here is a minimal example that reproduces the problem.


```
#include <Kokkos_Core.hpp>

template<class T> class test{
public:
  using size_t = unsigned long;
private:
  size_t n;
  Kokkos::View<T*, Kokkos::CudaSpace>* elements;
public:
  test(int i_n){
    n=i_n;
    elements=new Kokkos::View<T*, Kokkos::CudaSpace>("elements", n);
  }
  ~test(){
    delete[] elements;
  }
  inline size_t size() const {
    return n;
  }
  inline const T& operator[](const int i) const {
    return (*elements)(i);
  }
  inline T& operator[](const int i){
    return (*elements)(i);
  }
};

int main(int argc, char** argv){
  
  Kokkos::initialize(argc, argv);

  {
    test<int> t(42);

    Kokkos::parallel_for(Kokkos::RangePolicy<Kokkos::Cuda>(0, t.size()) , KOKKOS_LAMBDA(const int& i){ 
       	t[i]=42;
      });
  }

  Kokkos::finalize();

  return 0;
}
```

When I try to compile it, it gives the following error message:
```
error: expression must be a modifiable lvalue
```

If I comment out the operator[] returning a const reference, I obtain this error message:
```
error: no operator "[]" matches these operands
            operand types are: const test<int> [ const int ]
```

Thanks!

**Comment by dalg24** [comment]
They are multiple issues with what you are doing.
The compile error you see is because `t` is captured by copy so it is const in the lambda body and the const-qualified `operator[]` returns a const reference so you can't assign to `t[i]`.
Other issues include your forgoting to the `KOKKOS_FUNCTION` annotations to the member functions, your using a pointer to a view instead of just a view.

**Comment by crtrott** [comment]
As discussed in the lectures Kokkos has to make the object const for various reasons. Think about it this way: say you implemented the class as just owning an array of length 42. You then capture the class, we need to do it by copy since you want to execute on the GPU and a reference would result in an access error. Which means the lambda now has a copy of test. That copy never comes back to the original, the copy just goes out of scope when the lambda goes out of scope, so your modification would be lost. Hence we enforce constness. 

Now you actually have a View in there: first of all you need an actual View not a ptr to a View, since otherwise that ptr points to a struct on the host thread stack. Access it on the GPU and boom. 
Next you can make that operator const: you have reference semantics, its like a const pointer, not a ptr to const. Constness for Kokkos Views is indicated through the Scalar type. You can not do it via the const ness of the method. 

Does that make sense?

So what you should do is something like this:
```c++
template<class T> class test{
public:
  // size_t is already reserved by the C++ standard
  using size_type = unsigned long;
private:
  Kokkos::View<T*, Kokkos::CudaSpace> elements;
public:
  test(int i_n){
    elements=Kokkos::View<T*, Kokkos::CudaSpace>("elements", n);
  }

  // don't need a destructor elements will self destruct

  template<class U>
  test operator= (test<U>& rhs) {
     elements = rhs.elements;
  }
  inline size_type size() const {
    return elements.extent(0);
  }
  inline T& operator[](const int i) const {
    return elements(i);
  }
};

void foo(int N) {
  test<int> a(N); // modifiable
  test<const int> const_a = a; // not modifiable
}
```

**Comment by zaphod41** [comment]
Thank you very much for your detailed explanations.

I thought I had to specify the length of the view when declaring it. It's the reason why I used a pointer.

In fact, I am a bit worried about what I am doing. I am trying to port a large and complex application to Kokkos. It would have been better to design it around Kokkos but it's how it goes...

If I do the following things:
1. Put the data allocated on the heap (even complicated objects) in views.
2. Put KOKKOS_FUNCTION in front of the function declarations
3. Do the demanding calculations inside Kokkos::parallel_for
4. Copy the data from and to the GPU or use Kokkos::CudaUVMSpace

will I be all right or could it turn out to be really complicated?

Many thanks!

**Comment by crtrott** [comment]
That is generally the approach. Complicated objects which are not arrays you can just capture as part of the lambda / or make it part of a functor. I mean if they are not arrays they are hopefully read only since otherwise you have tons of access conflicts when 100k threads on the GPU use it. 

Also to just ground your expectations correctly: remember that as long as you move data back and forth and you still have compute happening on the CPU your speedup may be limited or negative. Moving data back and forth is very costly. THe end goal is to use the CPU just to organize kernels, never actually do anything with the data you compute on. Largely that is because on a machine like summit the CPUs represent only 5% of your compute/bandwidth and moving data to the GPU costs you as much as going through all the data once on the CPU. Hope that makes sense?

**Comment by zaphod41** [comment]
Thank you very much for your explanations.

I agree with you and I indeed think I'm doing the wrong thing but this looks like the only solution in my situation.

**Comment by crtrott** [comment]
Just to close this out: what you are doing is exactly how we are porting all our legacy applications, so you are not doing anything wrong. What we found useful is to port essentially one path through the application. I.e. port everything needed for one simple input deck, instead of porting one capability category at a time. That way you can see at least for one test case what you would get if you had ported everythign.

**Comment by zaphod41** [comment]
OK. Thanks for your help!
