### ISSUE TITLE
Kokkos: add cmake check for gcc version now that c++14 is required

### ISSUE THREAD

**Issue by jhux2** [kokkos/kokkos#3789]
(Migrated from https://github.com/trilinos/Trilinos/issues/8720)

There are at least a couple issues (Trilinos  issues 8710 and 8673), as well as reports on the Kokkos slack channel, all related I think to the c++14 change. When someone uses the intel compiler, they need to make sure that a new enough GCC is being used.

Is it possible for Kokkos add a cmake check to make sure that a recent enough GCC is being used?

See the Trilinos issue for some ideas that @jjellio suggested.

**Comment by DavidPoliakoff** [comment]
I'm a fan of the try_compile answer from @jjellio . This is the kind of thing we could provide real value with, if Kokkos is how users _avoid_ inscrutable C++ error messages.

**Comment by DavidPoliakoff** [comment]
So, the error comes from building Kokkos_Core.cpp. Is there a way to:

1) try compiling Kokkos_Core.cpp
2) grep for failures containing `namespace "std" has no member   "remove_cv_t"`
3) If we spot them, call out "hey, your GCC is too old for Intel"

@jrmadsen, aren't you glad you showed initiative in build systems? You get to be a part of these fun conversations!

**Comment by DavidPoliakoff** [comment]
Last comment, I swear: actually, come to think of it, this probably fixes a lot of other compilers, too

**Comment by jjellio** [comment]
David, I would avoid telling them their GCC is too old. In my experience, this problem comes from a broken environment / module - the user thinks they are using Intel, and now you are talking about GNU. Moreover, just because `which g++` points to a valid version, their include or library path may be totally bogus. Just adding a newer GCC to their PATH or something may actually create more hellish problems.

I'd say, try to build something that is oddly specific to your std version (or a choice file from Kokkos), if that fails, print a detailed error message explaining what the problem likely is. My examples using `ldd` can be helpful, but they aren't fool proof - on Mutrino at one point this was broken because of how modules got loaded (and what they did in the module files). To that end, explaining that Intel uses GNU headers and thus needs to be matched to (ideally) the GNU used to install it would atleast be helpful. I don't think I ever opened an issue w/Trilinos about this, as it was resolved via Admin tickets on the machine - which ultimately the user is probably going to have to pursue (if their modules are whacky).

**Comment by DavidPoliakoff** [comment]
@jjellio : this gets into some goofiness, though. At Sandia, the way to solve this problem is with modules, if your Intel found a GCC that's too old, you load a newer GCC module. At LLNL, the way would be to pass -gcc-name (or gcc-toolchain), as the philosophy there is that environment shouldn't be relied upon to guarantee builds. Outside of DOE, the answer is to `apt-get` a newer GCC.

So I agree we need to go beyond "GCC too old" and discuss headers, but the resolution might be hard to make general.

**Comment by mhoemmen** [comment]
> I'd say, try to build something that is oddly specific to your std version (or a choice file from Kokkos), if that fails, print a detailed error message explaining what the problem likely is.

This reminds me of (the algebraic multigrid library) ML's one error message that includes a detailed explanation and an ASCII art diagram (courtesy Ray Tuminaro).  ML developers sometimes get a phone call that starts "hey, so I got this ASCII art diagram..." and they can immediately interrupt with "read it and it will tell you what's wrong and how to fix it."  (Lesson: Users will still bother you, but it's satisfying to embarrass them into reading the error message that solves their problem.)

**Comment by masterleinad** [comment]
Fixed in #3809.
