### ISSUE TITLE
Casting runtime sized subviews to compile time sized subviews

### ISSUE THREAD

**Issue by mrtupek** [kokkos/kokkos#380]
I'd like to be able to do this:

Kokkos::View<real**> field("name", 100, 6);
Kokkos::View<real[6], Kokkos::LayoutStride> y = Kokkos::subview(field, 76, Kokkos::ALL());

Is this possible, or are their technical reasons why this is hard?  I'm currently getting a compiler error.  The idea is at the low level I know the size of the subview, and I want the index calculations to be optimized.

**Comment by ndellingwood** [comment]
Just to clarify, were the ranks provided to the `Kokkos::View`? 
i.e. 
```
typedef double Type;
Kokkos::View<Type**> field("name", 100, 6);
Kokkos::View<Type**> y = Kokkos::subview(field, 76, Kokkos::ALL());
```
If so, that should compile. 

For runtime-determined rank a DynRankView can be used as follows which is closer to the syntax used in the question:
```
Kokkos::DynRankView<Type> field("name", 100, 6);
auto y = Kokkos::subview(field, 76, Kokkos::ALL());
```

**Comment by ndellingwood** [comment]
Actually, in the first case you should use `auto` since the layout may be strided depending on the layout of the original view, i.e.

```
typedef double Type;
Kokkos::View<Type**> field("name", 100, 6);
auto y = Kokkos::subview(field, 76, Kokkos::ALL());
```

**Comment by mrtupek** [comment]
Looks like I forgot to check the formatting before I posted.  What I wanted to do is actually:

typedef double Type;
Kokkos::View\<Type\*\*> field("name", 100, 6);
Kokkos::View\<Type[6], LayoutStride> y = Kokkos::subview(field, 76, Kokkos::ALL());

It looks like this does actually work in the current Kokkos (the version I had access to was some months old).  Now I have a few follow on questions:

1. 

Is doing this useful?  Thinking about this more it seems the difference between 

Kokkos::View\<double*, LayoutStride> 
and
Kokkos::View\<double[6], LayoutStride> 

might be nothing, as that 6 doesn't need to be stored in the first case, and the index calculations don't use 6.  Is there any memory or performance benefit to specifying at compile time the subview dimension?

 2.

The auto trick seems more useful, as subviews to LayoutRight in that case are basically just pointers to a "double[6] struct".  But this means any routines which work on that subview will have to be templated on the layout.  For various reasons, this is probably not a workable solution for us.  Is the cost of always assuming LayoutStride significant?

**Comment by crtrott** [comment]
LayoutStride is a significant cost, since it might prevent vectorization since the access is not stride 1. Also it always adds the stride as a value to the metadata. I.e. a 1D LayoutStride view handle is 8byte larger than one with a LayoutLeft. On GPUs this might or might not hurt. Using a compile time dimension for a 1D view at least safes 8 byte on the meta data since the 6 is stored as an enum instead of an int64 or something like that. 

If your original view were LayoutRight that subview could actually be assigned to a LayoutLeft or LayoutRight. If you use the subview function this works via a temporary LayoutStride view construction. If you use the subview constructor (i.e. just create "y" directly and use the arguments to the subview function as the constructor arguments) the temporary is avoided.
