### ISSUE TITLE
Fast path for zeroing Views

### ISSUE THREAD

**Issue by DavidPoliakoff** [kokkos/kokkos#3930]
Reported via Slack, it's much slower to use either a parallel_for or deep_copy to zero a view, as compared to something like a cudaMemset. We need to fix this before people sprinkle nonportable memsets through their code

**Comment by stanmoore1** [comment]
Yes please!

**Comment by crtrott** [comment]
So basically we need to intercept the deep copy call which sets to a value where the value consists only of 0 bytes.
Then on some backends we can call the appropriate memset. Note this doesn't apply to all of them: for OpenMP for example its slower to use memset since its not parallel.  

One optimization for the generic deep copy kernel we could do is instead of setting element wise we cast to struct<SCALAR,N> { SCALAR vals[N}; } and set those (also assert alignment).
That way you get the CUDA 128bit memops which we still miss out on with int or double.
Kokkos::complex<double> is basically as fast as memset.
And the struct trick we can also use to set to arbitrary values.
As long as every element is supposed to be set to the same value.

Note that the main issue the original reporter had is that they cast every view to a view of char. Char is bad on every architecture since it does sub word memory ops.

**Comment by masterleinad** [comment]
Using cudaMemset, I am seeing
```
  BM_generic<TestZeroing, int>/1024/real_time                   11823 ns        11781 ns        58757 Bandwidth=346.455M/s
  BM_generic<TestZeroing, int>/4096/real_time                   15045 ns        14873 ns        41120 Bandwidth=1089.03M/s
  BM_generic<TestZeroing, int>/32768/real_time                  15141 ns        15103 ns        45694 Bandwidth=8.65699G/s
  BM_generic<TestZeroing, int>/262144/real_time                 15995 ns        15895 ns        44368 Bandwidth=65.5582G/s
  BM_generic<TestZeroing, int>/2097152/real_time                24528 ns        24484 ns        28429 Bandwidth=342.006G/s
  BM_generic<TestZeroing, int>/16777216/real_time               91880 ns        91734 ns         7681 Bandwidth=730.398G/s
  BM_generic<TestZeroing, int>/134217728/real_time             619818 ns       618953 ns         1114 Bandwidth=866.175G/s
```
on a V100 and
```
BM_generic<TestZeroing, int>/1024/real_time                   16153 ns        16153 ns        43246 Bandwidth=253.577M/s
BM_generic<TestZeroing, int>/4096/real_time                   15764 ns        15764 ns        44020 Bandwidth=1039.3M/s
BM_generic<TestZeroing, int>/32768/real_time                  16981 ns        16981 ns        41228 Bandwidth=7.71884G/s
BM_generic<TestZeroing, int>/262144/real_time                 23298 ns        23298 ns        29727 Bandwidth=45.0066G/s
BM_generic<TestZeroing, int>/2097152/real_time                68435 ns        68435 ns         9592 Bandwidth=122.578G/s
BM_generic<TestZeroing, int>/16777216/real_time              429421 ns       429418 ns         1633 Bandwidth=156.278G/s
BM_generic<TestZeroing, int>/134217728/real_time            3412157 ns      3394131 ns          212 Bandwidth=157.341G/s
```
using our current approach which seems to be faster for up to a couple hundred thousand elements.
