### ISSUE TITLE
Mapping of thread IDs to threads/vector lanes on CPU

### ISSUE THREAD

**Issue by mcarilli** [kokkos/kokkos#395]
Hi Kokkos Team,

Am I correct in saying that in a given parallel construct, say 
`parallel_for( N, KOKKOS_LAMBDA( int threadID ){ lambda body; } )`
threadID maps to a thread rather than a vector lane on the CPU?  This certainly seems to be the case, as I am able to vectorize inner loops within "lambda body."

Alternatively, if I compile with -DKOKKOS_OPT_RANGE_AGGRESSIVE_VECTORIZATION, does Kokkos map threadIDs to vector lanes rather than threads?

Thank you for your help,
Michael

**Comment by crtrott** [comment]
Hi

you shouldn't consider the index as a threadId. It is actually a workset index. The workset index range is then split across threads which loop over their (not necessarily contiguous) sub-range. 
What we do when the aggressive vectorization option is given, is to mark the internal loops of threads over their own sub-range with pragmas to indicate that iterations are independent. 
As a consequence the compiler will ignore assumed data dependencies and more likely vectorize these loops if possible (i.e. if there are no other inner loops). If your code can run correctly on GPUs, it is save to use the aggressive vectorization option. 

It is always legal to have inner loops. On CPUs, the compiler will try to vectorize those. 

All in all: Kokkos does never do explicit mapping to vector lanes on CPUs, since there is actually no good way to do that except for writing all the code in vector intrinsics. Vectorization is hence implicit if the compiler can figure out how to vectorize a loop, which can be an explicit inner loop in the lambda body, or the index-sub-range loops of each thread which are not visible to the user. 

I hope that clarifies it.

**Comment by nmhamster** [comment]
@mcarilli you should really think of this as an index in the iteration space *not* as a specific hardware resource ID. You're giving the runtime N items of parallel work, the mapping of those resources is then determined by a variety of scenarios and what we might do today isn't a commitment for equivalent mapping in the future. That means you should try to write independent iterations (in the lambda body) and then leave the partionning of that to threads/vectors to the compiler and runtime. The aggressive vectorisation flags just tell the library to enforce vector dependency markings during compile.

**Comment by nmhamster** [comment]
@crtrott - good job we had the same reply :-)!

**Comment by mcarilli** [comment]
Understood, thanks for the quick reply.

**Comment by crtrott** [comment]
@nmhamster - yeah, hopefully that is a good sign that we actually understand what we are doing, and what the semantics of our constructs are ;-)
