### ISSUE TITLE
OpenMP Test should set omp_set_num_threads to 1

### ISSUE THREAD

**Issue by mcolg** [kokkos/kokkos#4]
When testing Kokkos with pgc++, the following test case fails: 

 static void TearDownTestCase()
  {
    Kokkos::OpenMP::finalize();
    omp_set_num_threads(0);
    ASSERT_EQ( 1 , omp_get_max_threads() );
  }

PGI returns "0" from omp_get_max_threads since that is what is set.  If the expected result is "1", shouldn't omp_set_num_threads be set to "1"?

**Comment by mhoemmen** [comment]
OpenMP 4.0 standard, Section 3.2.1 (omp_set_num_threads) says that "[t]he value of the argument passed to this routine must evaluate to a positive integer, or else the behavior of this routine is implementation defined."

Thus, this is not a valid test.  Does it work when the input argument is 1?

mfh

On 4/16/15, 2:37 PM, "mcolg" <notifications@github.com<mailto:notifications@github.com>> wrote:


When testing Kokkos with pgc++, the following test case fails:

static void TearDownTestCase()
{
Kokkos::OpenMP::finalize();
omp_set_num_threads(0);
ASSERT_EQ( 1 , omp_get_max_threads() );
}

PGI returns "0" from omp_get_max_threads since that is what is set. If the expected result is "1", shouldn't omp_set_num_threads be set to "1"?

-

**Comment by crtrott** [comment]
Yeah we tested it. Doing omp_set_num_threads(1) should work. We'll fix that asap.

**Comment by crtrott** [comment]
I pushed a fix. Can you please test and confirm that it works for you?

**Comment by crtrott** [comment]
I close this for now since I believe its fixed. Please let me know if that is not true.
