### ISSUE TITLE
Disallow enabling both OpenMP and Threads in the same executable

### ISSUE THREAD

**Issue by dsunder** [kokkos/kokkos#406]
Many problems exist when enabling OpenMP and Threads in the same executable, one of which is that using the DefaultHostSpace can lead to the Threads execution space launching OpenMP threads.

**Comment by crtrott** [comment]
I don't get what you mean with the Threads execution space launching OpenMP threads?

**Comment by hcedwar** [comment]
When using HostSpace views initialization is with the HostSpace::execution_space, which will be OpenMP.  Thus using Threads instead of OpenMP when both are available leads to problems.  
It is not a good idea to have both available in a single executable since if both are used there will be thread pool resource conflicts.

**Comment by crtrott** [comment]
Yeah I know that. But what I don't get is why the Threads execution space would launch OpenMP threads. The scenario you describe the OpenMP space launches OpenMP threads.
