### ISSUE TITLE
Restructure the `kokkos::algorithms` subdirectory to be more consistent with std library

### ISSUE THREAD

**Issue by fnrizzi** [kokkos/kokkos#4134]
@crtrott @dalg24 @cz4rs @DavidPoliakoff [@mhoemmen]

The current kokkos directory structure is as follows: 
```
Kokkos/
  core/
  algorithms/
  ...
```
Inside the `algorithms/` we have: 
```
Kokkos_Random.hpp
Kokkos_Sort.hpp
Kokkos_StdAlgorithms.hpp # this is what we are going to add to include all std-like algos
std_algorithms/          # this is subdir where we will put all the headers 
```
# My suggestion
```
Kokkos/
  core/
  algorithms/
    Kokkos_Sort.hpp
    Kokkos_StdAlgorithms.hpp # this is what we are going to add to include all std-like algos
    std_algorithms/          # this is subdir where we put all the headers 
  numerics/
    Kokkos_Random.hpp
    Kokkos_StdNumeric.hpp # provides access to the operations defined in std <numeric> 
                          # (reduce, iota, accumulate, etc see also issue #4075 for more details)
    std_numeric/          # this is subdir where we put the headers with implementations 
  ...
```
We could also drop the `Std` and just have `Kokkos_Numeric.hpp` and `Kokkos_Algorithms.hpp`. 

# Benefits and motivation
If we look at the c++ std, Random is part of the [numeric library](https://en.cppreference.com/w/cpp/numeric), not of the algorithms library but sort is part of the algo.
I would also argue this is (1) cleaner, (2) allows users a finer-granularity when including things (for example, if one wants to use `Kokkos::include_scan` which will be part of numeric, they would not need to include all algorithms), (3) by definition we are consistent with the standard, (4) if a user remembers where a specific function is in the std, they would know where the corresponding kokkos counterpart is, (5) obviously reduces conflicts during development. 

# Drawbacks 
I don't see any.

**Comment by crtrott** [comment]
There are drawbacks due to Trilinos treating stuff as sub projects (so you would need to introduce a new one). 
There is also another consideration: we may wanna talk about some of this stuff in the future as more distinct efforts. I.e. we got Kokkos Core, Kokkos Tools, Kokkos Kernels, but we also got Kokkos Algorithms and maybe Kokkos Containers. We had recently a discussion about this how this may help in the mind of management, funding agencies, even just leadership/code ownership perspective. 

With all the algorithms you guys are writing now, giving Kokkos Algorithms its own identity feels like it makes sense. It doesn't make sense how ever to split two much further. So I would leave all the numeric stuff in the algorithms directory. Note that reduce and accumulate and what not are fairly described as algorithms too.

**Comment by fnrizzi** [comment]
@crtrott, agreed! 
Re trilinos, i will follow up to that offline with you since I have some thoughts and also becusss we are currently involved in the build system of trilinos. 

Re second thing: yes, I agree one can see all these as algorithms broadly
