### ISSUE TITLE
Standardize methodologies for Tools subsytem "only evaluate this if a tool is listening"

### ISSUE THREAD

**Issue by DavidPoliakoff** [kokkos/kokkos#4152]
It is frequently the case that Kokkos needs to not incur overheads when a tool isn't loaded. Most recently: [this](https://github.com/kokkos/kokkos/pull/3966#discussion_r666295235), but you can see it dating back to [this stuff](https://github.com/kokkos/kokkos/blob/master/core/src/impl/Kokkos_Profiling.hpp#L486-L496).

In fact, we are at this point probably inefficient, I think there are many inefficiencies in this design. If you look at the thing I linked, we currently build a name for a functor if a _tool is loaded_, not if _somebody is listening the the begin_parallel_for event_. We also check whether a tool and/or callback is loaded multiple times in that path. 

*Proposal* I'd like to standardize this concept in Kokkos: of how to only look up expensive arguments when they are needed.

*Proposed solution* (note that this is _orthogonal_ to whether we want to solve this at all): Rather than passing a value if some condition is met, move to a model in which we pass a functor that will return the argument. Then, invoke that functor [exactly if the given callback exists, here](https://github.com/kokkos/kokkos/blob/master/core/src/impl/Kokkos_Profiling.cpp#L136). This saves us on code debt, we don't have to maintain umpteen versions of this logic, and should be faster.

I'll leave detailed pro/con analysis on this til after we decide whether we want this concept, there's actually a lot of hairy issues here. I do have an implementation sketch, but will also wait to show that til after we decide whether this is a good idea

**Comment by crtrott** [comment]
Generally I think yes, we should do something like this, but I believe the devil is in the details. For example we defintiely shouldn't use lambdas for this in the general case (for example inside the parallel_for functions), since that would mean we compile a different version of that guy for every template instantiation of the calling function. For stuff like fence its less problematic since those functions are not really templated (i.e. not templated on user stuff). 

Then the other question is whether the construction of the functor gets optimized away if the condition is not true. If that functor takes potentially expensive things like strings and has to construct them then we don't gain anything.  (see below for code sketch)

So in principle I think we should try to find some standardized solution, but I can't quite think of one at the top of the hat which behaves as I like it to.


Code sketch of what I think you were thinking off:
```c++
template<class Action>
void call_if_callback_exists(ptr_to_callback, Action a) {
  if(ptr_to_callback) a();
}

void parallel_for(const std::string label, const policy p, ...) {
    call_if_callback_exists(parallel_for_callback_ptr, [&] () {
       parallel_for_callback_ptr(label, p.space.get_device_id(), ...);
    });
    ....
}
```

Compared to 
```c++
void parallel_for(const std::string label, const policy p, ...) {
    if(parallel_for_callback_ptr) {
       parallel_for_callback_ptr(label, p.space.get_device_id(), ...);
    }
    ....
}
```

In the functor/lambda case the compiler will likely have to invoke the copy constructor for std::string, and for policy, while in the direct conditional case it doesn't. 

That is basically what I run into when trying to think about how to do this (without the use of macros, which could MAYBE be an option).

**Comment by DavidPoliakoff** [comment]
1) I don't think the callback needs to capture everything, just everything it needs to create expensive arguments. So lets focus on the string. If you capture a `const std::string& label` by reference, it shouldn't copy-construct it, no? You should just hold a reference? You'd of course need to manage object lifetimes, but in our case, that should be fine. In such a case constructing the functor just means setting the value of a reference, I believe

**Comment by crtrott** [comment]
I am not super sure that is true if the original string was a literal, since in that case no memory existed to begin with?

**Comment by crtrott** [comment]
Looks like its ok:
```
#include<Kokkos_Core.hpp>

extern "C" void use_string(const char* c);

bool is_used;

void foo(const std::string& label) {
  if(is_used) use_string(label.c_str());
}

template<class F>
void call_if_true(bool cond, const F& f) {
  if(cond) f();
}

void foo_wrapper(const std::string& label) {
  call_if_true(is_used, [&] () {
    use_string(label.c_str());
  });
}

int main(int argc, char* argv[]) {
  Kokkos::initialize(argc,argv);
  {
     int N = (argc>1) ? atoi(argv[1]) : 1000000;
     int M = (argc>2) ? atoi(argv[2]) : 1;
     is_used = false;
     if(M) is_used=true;
     foo("A");
     foo_wrapper("A");
     Kokkos::Timer timer;
     for(int i=0; i<N; i++) foo("A");
     double time_plain = timer.seconds();
     timer.reset();
     for(int i=0; i<N; i++) foo_wrapper("A");
     double time_wrapper = timer.seconds();

     printf("%e %e\n",time_plain,time_wrapper);
  }
  Kokkos::finalize();
}
```

**Comment by crtrott** [comment]
Getting 
```
bash-4.2$ ./test.host 100000 0
1.442240e-04 1.441020e-04
```
for a serial build.

**Comment by masterleinad** [comment]
I think it's a good idea to be more careful about using specific events and something like
```
void parallel_for(const std::string label, const policy p, ...) {
    if(parallel_for_callback_ptr) {
       parallel_for_callback_ptr(label, p.space.get_device_id(), ...);
    }
    ....
}
```
looks reasonable to me.

**Comment by crtrott** [comment]
OK we want to at least explore options for this, and probably need a concrete impl to figure out drawbacks and currently unenvisioned side effects.
