### ISSUE TITLE
Enhancement: Need a way to turn off View initialization with Kokkos::realloc

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#4154]
It seems like there is currently no way to turn off View initialization for `Kokkos::realloc` (i.e. no way passing `ViewAllocateWithoutInitializing` to the constructor of the new view, unless I missed it). So I have to instead use the empty constructor then call the constructor again with `ViewAllocateWithoutInitializing` to avoid double allocation leading to memory bloat. It would be very nice if  `Kokkos::realloc` supported  `ViewAllocateWithoutInitializing`.

**Comment by stanmoore1** [comment]
Also see #3342 for a related request to DualView.

**Comment by stanmoore1** [comment]
And see https://github.com/kokkos/kokkos/pull/2285 for a related implementation for `View::resize` instead of `realloc`

**Comment by masterleinad** [comment]
Sounds like a good idea to me if we make it an option and don't change the current behavior.

**Comment by crtrott** [comment]
Do we want to support this: 
Unanimous consent.

Do we want to do just what resize does, or forward view_alloc in its totally (problem here: label should be preserved, instead of new one).

Allow what resize does (pass through arg for view_alloc):
SF F N A SA
1 4 6 0 0

Need more info whether we want direct view_alloc forward too (instead of just the arg to view_alloc), but can revisit later.

**Comment by crtrott** [comment]
Do what resize did if possible with code reuse: also address DualView.
