### ISSUE TITLE
recent compilers ...

### ISSUE THREAD

**Issue by etijskens** [kokkos/kokkos#4303]
The C++ compilers mentioned on the Kokkos repo are rather old. gcc 8.1.0, clang 8.0.0, ... Is there a specific reason for using these? is the documentation out of date? I am a bit surprised that a system that promises performance portability even in the future, uses old compilers...

**Comment by DavidPoliakoff** [comment]
Hi @etijskens , those are the minimum supported versions. You're more than welcome to use very new compilers, we just have to support old compilers as some of our customers are stuck with them. I use unreleased Clangs and GCCs on a pretty regular basis without any trouble

**Comment by ajpowelsnl** [comment]
@DavidPoliakoff , @crtrott -- This is an interesting topic.  Does Kokkos have a formal strategy for both deprecating (as in no longer supporting) and screening new compilers (with a view to bringing candidates into development and production) ?  Do we have a formal rubric for evaluating and qualifying new compilers?  Do we need such a strategy and rubric?  I have the impression that our approach is rather ad hoc, but that could just be because of my limited knowledge.

**Comment by DavidPoliakoff** [comment]
@ajpowelsnl: for deprecation, it's really a question of when code team product owners will allow us to do so. Screening, we generally have compilers we want to support (Clang, hipcc), and try to build with a most recent release. As to when they're in CI, that's mainly a question with @dalg24

**Comment by crtrott** [comment]
Its actually not the minimum compilers. Its more like what do we test like constantly. The general policy is that we have minimum compilers (GCC 5.3.0, CUDA 9.2.88 for example) and that any newer version should be supported, and if you find it doesn't work that is a legitimate bug we will try to fix as soon as possible. We currently test around 200 configurations per day (about 30 or so at PR time). But unfortunately we can't test every compiler version. I am pretty sure we have a GCC 10 build somewhere flying around anyway. 

Oh and calling GCC 8 rather old is kinda funny :-), doesn't appear you are working at DOE lol.

**Comment by ajpowelsnl** [comment]
@DavidPoliakoff , @crtrott -- OK, so, it sounds like we're more or less happy with the approach we have...?

**Comment by masterleinad** [comment]
I think we discuss supported compilers regularly enough, i.e. pretty much for every release.

**Comment by ajpowelsnl** [comment]
@masterleinad -- OK, I can remove it from our issues to discuss, if the general feeling is that we're happy with our current approach.

**Comment by etijskens** [comment]
@DavidPoliakoff , @crtrott
Many thanks for the quick answer. That was not at all clear from the documentation. on slide 98 of kokkosTutorial_01_Introduction.pdf I read:
**Currently very sensitive to exact compiler/STL combination** 
Clang9+
GCC6 Toolchain
Which to me suggest that it only works with GCC6. I am happy to hear that this is not the case. 

If I may suggest to add the answer to the documentation, just to not scare off potential users?

I learned about Kokkos a few days ago and I find it a very interesting approach in view of the increasing variety of hardware of supercomputers. I will start to explore the approach soon.

**Comment by crtrott** [comment]
Oh that slide 98 is explicitly about the OpenMPTarget backend, which uses OpenMP 5.0 Offload. And indeed for OpenMP 5.0 the compilers are still VERY fragile. I.e. stuff breaks from one minor version to the next, its picky about the C++ standard library etc.. This isn't so much a problem with Kokkos but with the fact that OpenMP 5.0 itself is still very much in the implementation phase in compilers. 

The more mature backends CPU OpenMP, CUDA etc. work generally with the whole range of compilers. Generally part of the reason that HIP, SYCL and OpenMPTarget are considered experimental backends in Kokkos is because the vendor software stacks are not fully stable and mature yet, and thus folks are much more likely to run into issues. HIP is the furthest along though. We are expecting it to be primary stable by early next year in time for the ORNL Frontier ExaScale machine.

**Comment by etijskens** [comment]
@crtrott
Thanks again for the clarification. this increases my confidence. I will probably be involved with supporting LUMI, So HIP is also of interest to me.

**Comment by crtrott** [comment]
Ah ok. I wouldn't expect any problems on LUMI, since as far as I can tell it is using the same (or at least a very similar) configuration to Frontier. Most of the development for that backend happens by Oak Ridge and AMD staff.
