### ISSUE TITLE
hip.team_policy_max_recommended test failing nightly tests in Hip_Serial build, rocm/4.3.0, MI50 and MI100

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#4338]
The `hip.team_policy_max_recommended` test began failing nightly Hip_Serial builds with/without debugging enabled, with rocm/4.3.0 on MI50 and MI100 architecture, appears to have begun following merge of PR #4332

Error message:
```
23:43:11 4: [ RUN      ] hip.team_policy_max_recommended
23:43:11 4: unknown file: Failure
23:43:11 4: C++ exception with description "Kokkos::Impl::ParallelReduce< HIP > could not find a valid team size.
23:43:11 4: Traceback functionality not available
23:43:11 4: " thrown in the test body.
23:43:11 4: [  FAILED  ] hip.team_policy_max_recommended (82 ms)
```

Sample reproducer
```
module load cmake/3.19.3 rocm/4.3.0

# generate_makefile script configure option
$KOKKOS_PATH/generate_makefile.bash --with-devices=Hip,Serial --arch=VEGA908 --compiler=hipcc --cxxflags="-g -Werror " --cxxstandard="14" --kokkos-path=$KOKKOS_PATH --no-examples --with-options=enable_large_mem_tests --debug

```

**Comment by Rombur** [comment]
I can reproduce the error with rocm/4.3.0. The test passes with rocm/4.4.0.

**Comment by arghdos** [comment]
I'll take a look -- I saw this at some point, but wasn't able to reproduce with the final version of the PR.

**Comment by arghdos** [comment]
Ok, can repro locally -- will keep digging.

**Comment by arghdos** [comment]
For some reason, the shmem functor for this reduce: https://github.com/kokkos/kokkos/blob/develop/core/unit_test/TestTeamTeamSize.hpp#L110

is always returning > 64KiB of LDS, so the error code at least checks out.  No idea why this would cause > 64 KiB of LDS required, tho... still digging.

**Comment by arghdos** [comment]
I'm able to work around the regression by setting the max LDS scratch size to the equally arbitrary 32K, [here](https://github.com/kokkos/kokkos/blob/develop/core/src/HIP/Kokkos_HIP_Parallel_Team.hpp#L193).  

I suspect the removal of either the volatile or the threadfence is allowing the compiler to "optimize" placement of the `MyArray` or `static_array` into LDS [if it can prove uniformity], driving up the overall LDS usage.  Going to drop it into a standalone for easier testing.

**Comment by arghdos** [comment]
Ok, yeah -- using 2cc4c43295b52420d1accbf2c92442b4de9a93ac, I'm seeing an LDS size of 17424B, and on 962ed6b091f41d4a82a71bb96781e63cfbdc7188, I'm seeing an LDS size of 25616B.

All this is using a debug build, so the #'s might change in Release / ROCm 4.3.
So, 40Kib + 25.616 KiB is ~65KiB, hence the ask to find a valid scratch space is tough.

IMO the real bug here is that the `max_scratch_size` is disconnected from what the compiler is using for LDS allocations.  This means we can run into situations where the value returned from that function can exceed what is allowed for the kernel based on the compiler's static LDS allocation.

Secondarily, there may be a compiler perf. issue we should look into as well i.e., why are we using an extra 8KB (or so) of LDS in this case?

**Comment by arghdos** [comment]
Re: the compiler perf issue, I checked real quick w/ a much newer compiler (https://github.com/ROCm-Developer-Tools/amd-llvm-project/commit/ecb83fd6143215b338d16500a5fc7deb023f5159), from ~Jul 30th, and the LDS use here is only 1032B.  This is very likely why this issue is "solved" in ROCm 4.4, so I suggest we work on solving the `max_scratch_size` disconnect first.  Sound good @Rombur ?

**Comment by Rombur** [comment]
yes, that makes sense.

**Comment by arghdos** [comment]
Discussed with @dalg24 on slack, copying an edited form of it here for posterity:

In my view, the issue is really that:

    - A) the 40 KiB LDS max in `scratch_size_max` isn't always guaranteed to work
    - B) the policy API is disconnected from the actual kernel that will be invoked, so we don't have an accurate way of returning a real limit.

As an example of what is meant by point B, we have:

```
  using policy_type = Kokkos::TeamPolicy<TEST_EXECSPACE>;
  int max_scratch_size = policy_type::scratch_size_max(0);
  PolicyType p = PolicyType(10000, Kokkos::AUTO, 4)
                     .set_scratch_size(0, Kokkos::PerTeam(scratch_size));
  int team_size_max_for = p.team_size_max(FunctorFor<T, N, PolicyType, S>(),
                                          Kokkos::ParallelForTag());
```

In this case, we get the max LDS size & set the L0 scratch size before we ever get to the `team_size_max` call that has access to the functor & the tag.  It is only within the `team_size_max` call that we can reconstruct the actual kernel that will be executed in order to figure out how much static LDS it is using -- this is required for strict correctness, otherwise there is no guarantee that the value returned by `scratch_size_max` is actually valid.

Discussing w/ @dalg24, we think the best way is to change the policy constructor such that it takes both a functor and a tag, such that we can reconstruct the kernel.  This should be done in the constructor rather than e.g., the `scratch_size_max` call to avoid ambiguity like the following:

```
int **max_scratch_size** = policy_type::scratch_size_max(0, **FunctorFor**<T, N, PolicyType, S>(),
                                          Kokkos::**ParallelForTag**());
PolicyType p = PolicyType(10000, Kokkos::AUTO, 4)
                     .set_scratch_size(0, Kokkos::PerTeam(**max_scratch_size**));
int team_size_max_red = p.team_size_max(**FunctorReduce**<T, N, PolicyType, S>(),
                                          Kokkos::**ParallelReduceTag**())
```

**Comment by crtrott** [comment]
This proposed interface is not sufficient: we would also need to provide the team_size since the team_size controls how much shared memory we reserve for reductions. 

That gets us in the problematic situation that you need to know max available scratch to figure out what a good team size is, which is needed to figure out how much scratch we can use. 

I think its fairly dangerous that the compiler decides to use this much LDS memory for thread local stuff. Note this is NOT happening with nvcc ever. NVCC puts such arrays into "local memory" which comes out of global memory. What if I know I gonna need 40kB of shared memory, is there any way to tell the compiler not to put MyArray into LDS? Does that mean perfectly fine code breaks from one release to another? Does it mean that if I have a larger MyArray its gonna use up all my LDS?

**Comment by ajpowelsnl** [comment]
Item for Wed. Dev. Meeting discussion

**Comment by arghdos** [comment]
I would note that:

1. The compiler makes no guarantee where data will or will not be placed
2. In order for strict correctness, you need to check how much static LDS a particular kernel uses before deciding on the size of the scratch space.  This is true even on the CUDA side... consider a deviant user who puts (e.g.,) 25k of static LDS using `__shared__` in their kernel (when using the standard 64k allocation on Volta).

**Comment by arghdos** [comment]
As an example of what I mean by the latter point (w/o resorting to "devious" use of `__shared__` in a Kokkos kernel, or the compiler doing a thing we don't expect), consider the following example:

```
#include <Kokkos_Core.hpp>
#include <Kokkos_DualView.hpp>

#define TEST_EXECSPACE Kokkos::Experimental::HIP
#define ASSERT_EQ(X, Y) if(((X) != (Y))) {printf("Assertion: " #X " == " #Y " failed\n"); throw std::runtime_error("bad");}
#define ASSERT_GE(X, Y) if(!((X) >= (Y))) {printf("Assertion: " #X " >= " #Y " failed\n"); throw std::runtime_error("bad");}

using policy_type = Kokkos::TeamPolicy<TEST_EXECSPACE>;
template <class ExecutionSpace, class PolicyType>
struct functor {
  typedef ExecutionSpace execution_space;
  typedef typename PolicyType::member_type member_type;

  KOKKOS_INLINE_FUNCTION
  void operator() (member_type team_member, int& i) const {
    i += 1;
  }

  // select 4 * 6 KiB = 24 KiB
  size_t team_shmem_size (int team_size) const {
    return sizeof(int)*6144;
  }
};


int main(int argc, char** argv) {
  Kokkos::initialize(argc, argv);
  int max_scratch_size = policy_type::scratch_size_max(0);
  policy_type p = policy_type(10000, Kokkos::AUTO, 4)
                     .set_scratch_size(0, Kokkos::PerTeam(max_scratch_size));
  int team_size_max_reduce = p.team_size_max(
      functor<TEST_EXECSPACE, policy_type>(), Kokkos::ParallelReduceTag());
}
```

Essentially, the user has asked for 40KiB of dynamic LDS via the scratch size, and declared that they need 24 KiB of dynamic LDS for the team [the exact details could be modified to be more realistic].

So: we've asked for 64KiB of LDS, which should be perfectly permissible on hardware w/ a 64KiB LDS allocation, right?  Well, the above will fail on HIP with the same team size error because internally in the ParallelReduce, we used LDS for (e.g.,) `__syncthreads_or`.  Similarly, with light modification it fails on the CUDA side with:

```
Kokkos contract violation:
    Asserted condition `block_size > 0` evaluated false.
Error at "/home/nicurtis/scratch/kokkos/core/src/Cuda/Kokkos_Cuda_Parallel.hpp":410 
Aborted (core dumped)
```

**Comment by ajpowelsnl** [comment]
Morning @Rombur , @crtrott , @dalg24 -- Do you have an idea about which release this this will be in?  Release 3.6?  Release 3.7?  For now, I'll associate this issue with Release 3.6, and we can change it as needed.

**Comment by ndellingwood** [comment]
Updating the testing to use rocm/4.5.0, will update the issue to confirm if this resolves the failures

**Comment by ndellingwood** [comment]
This is still failing with rocm/4.5.0 on our caraway system with MI100 :(

**Comment by ajpowelsnl** [comment]
Discuss in Wed. , Jan. 19th meeting

**Comment by ndellingwood** [comment]
This issue is no longer present after updates on the testing system, closing
