### ISSUE TITLE
Feature request. DynRankView subview extension.

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#437]
I use a subview with dynrankview in Intrepid2. The subview mechanism is expensive as it involves rank 7 structure copy and assignment. 

Since most Intrepid2 functions are light weight (consider 3x3 determinant), this overhead is too large for such light weight computations. What I suggest is that the subview with dynrankview creates a static view as the rank is already known in the compile time.

```
DynRankView A;
operator()(int i, int j) {
  auto part = subview_static(A, i, j, ALL, ALL); 
  // the part is rank 2 static view and inherit the layout from A instead of using stride layout
  // this invovle the construction and assignment operator and it just copy the minimum meta data
  // for describing the rank 2.
```

Since subview supports both dynrankview and view, it may be required to have subview_static to returns static view all the time.

**Comment by ndellingwood** [comment]
Modifying the subview to return a static rank view is a good suggestion as the returned View will not have the same overheads that come with using a DynRankView, but to revise the subview to improve performance issues due to construction of a View from the input DynRankView will require specializing the SubviewExtents method that generate the extents. This part will require more substantial work and will be necessary in order to improve subview performance.

**Comment by ajpowelsnl** [comment]
Check in with @ndellingwood regarding completion.

**Comment by ndellingwood** [comment]
@ajpowelsnl this would require non-trivial updates to various subview components and was moved to the backlog as other tasks were higher priority at the time and never made it out of the backlog. This is incomplete, but I won't have cycles to work on this anytime soon.

**Comment by ajpowelsnl** [comment]
@kyungjoo-kim , @ndellingwood -- Many thanks for having a look at this and commenting.  We'll re-open and update the issue in the future, if this comes up again.
