### ISSUE TITLE
Synchronic in Kokkos::Impl

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#44]
Need an implementation of [Synchronic](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4195.pdf) in Kokkos::Impl with unit testing.  We have permission to use the [prototype source code](https://code.google.com/p/synchronic); no licensing issues.

**Comment by jgfouca** [comment]
OK, looking at it now.

**Comment by jgfouca** [comment]
@hcedwar, we have somewhat of a severe problem with the Synchronic stuff. The code uses std::this_thread::sleep_for which is only available if GCC detects that nanosleep is available. Apparently, there's a bug in GCC 4.7 and 4.8 where it fails to detect nanosleep and therefore compiles without sleep_for. The bug has since been fixed, but 4.7.2 is our standard compiler. Thoughts?

**Comment by nmhamster** [comment]
Do you need timing for this, its only ever been a best efforts anyway. Can we not just stick in some NOOP values here to cause a core stall out?

**Comment by hcedwar** [comment]
We don't need a direct port, just the design and functionality.  If there is an equivalent function that is conditionally available then we could use that function with the appropriate compiler version checks.  The Synchronic concept (see previously linked paper and code for details) is to spin but with several incrementally applied back-off strategies to relieve pressure on memory system.

**Comment by nmhamster** [comment]
Understood, but this does *not* need to be *time* based in order to meet specification (you can just execute a NOOP block with an exponential number of calls). The point of NOOPs is to prevent the cores from continuing to issue requests into the memory system.

**Comment by hcedwar** [comment]
Si - willing to consult with Jim for the implementation?

**Comment by jgfouca** [comment]
My current impl:
#ifdef _GLIBCXX_USE_NANOSLEEP
                    std::this_thread::sleep_for(time);
#else
                    usleep(time.count());
#endif

This assumes UNIX-type system, but I assume that should work fine for now.

**Comment by bmpersc** [comment]
There is at least one project(DICE) using Tpetra on windows regularly right now. I don't know how important that build is to them, Dan Turner could answer that though.

Brent

**Comment by crtrott** [comment]
?There are more projects who want to do that. They currently use Intel compiler. I think we need a fallback which at least works on windows.


________________________________

**Comment by nmhamster** [comment]
They are using Cygwin though right? Ie they have UNIX headers etc on the system?

S



--
Si Hammond
Scalable Computer Architectures
Sandia National Laboratories, NM
[Sent remotely, please excuse typing errors]
________________________________

**Comment by crtrott** [comment]
?I don't know, but you might be right.


________________________________

**Comment by bmpersc** [comment]
I don't think they are using cygwin actually, but I don't know for sure. Their goal was to make libraries that are linkable by a native windows program so I would suspect not. Dan would have all the answers to these questions. I've CC'd him so that we don't have to continue playing the guessing game.

Dan, can you fill us in on how you are using Tpetra on windows and what your requirements are?

Thanks,

Brent

**Comment by bmpersc** [comment]
Hi Brent,

We are not using cygwin. We compile Trilinos via the Intel 15 compilers. Is there anything else you wanted feedback on?

Thanks,
Dan


On Jul 13, 2015, at 9:59 AM, Perschbacher, Brent M <bmpersc@sandia.gov<mailto:bmpersc@sandia.gov>> wrote:

I don't think they are using cygwin actually, but I don't know for sure. Their goal was to make libraries that are linkable by a native windows program so I would suspect not. Dan would have all the answers to these questions. I've CC'd him so that we don't have to continue playing the guessing game.

Dan, can you fill us in on how you are using Tpetra on windows and what your requirements are?

Thanks,

Brent

**Comment by jgfouca** [comment]
OK, I'll redo the implementation to work on Windows.

**Comment by crtrott** [comment]
Merged in.
