### ISSUE TITLE
Can you tell me where to get the code for this part of the paper("Kokkos Array Performance-Portable Manycore Programming Model") in which file?

### ISSUE THREAD

**Issue by yuanAIhan** [kokkos/kokkos#4600]
When I was reading the paper "Kokkos Array Performance-Portable Manycore Programming Model". I found this part about "NUMA Thread Pool" or "NUMA Thread / Memory Management". Where should I find the source code of this part ?

**Comment by dalg24** [comment]
https://github.com/kokkos/code-examples/tree/main/papers/kokkos-core-tpds-2021

**Comment by dalg24** [comment]
@hcedwar @dsunder

**Comment by crtrott** [comment]
I don't know whether the actual code of this is anywhere publicly available - I don't even have that internally. But basically this is all just variants of a very old version of what is now on github here.

In the end it turned out that the NUMA part isn't super used, or the part of it which is important isn't really complicated. Effectively we just pin our threads, and then we make sure we initialize our data structures not with a single thread but with parallel loop with the most common data access pattern so that the first touch of pages happens on the numa domain of the thread which needs it. 

Effectively:

double * ptr = malloc(....);
parallel_for(size, [=](int i) { ptr[i] = 0; };

That on its own solves the vast majority of NUMA access issues in parallel code - assuming your threads are already pinned via HWLOC or because you use OpenMP and set the OpenMP binding clauses.

**Comment by yuanAIhan** [comment]
Yes, I got it! Thank you very much!
