### ISSUE TITLE
[Feature request] Extra dimensions and subview

### ISSUE THREAD

**Issue by ambrad** [kokkos/kokkos#464]
I can write
    `
    Kokkos::View<double*> x("x", 10);
    x(3,0) = 2;
`
The second index, 0, is both valid and ignored for the rank-1 View x.

However, I can't seem to write
    `
    xsv = Kokkos::subview(x, Kokkos::make_pair(2, 5), Kokkos::ALL());
`
The second index, Kokkos::ALL(), triggers a static assertion. It
seems to me that this line of code is just as valid as the first:
the second index is both valid (it expresses a range that is
meangingful for a non-constructed dimension) and it can be
ignored.

Another correct (IMO) subview is
    `
    xsv = Kokkos::subview(x, Kokkos::make_pair(2, 5), 0);
`

If I'm not mistaken, Kokkos::subview does not currently support
these use cases right now. Support would be helpful in at least the
following situation: one is writing a linear algebra routine that
is intended to work on both View<Scalar*> (local vector) and
View<Scalar**> (local multi-vector), and the routine wants to
operate on dimension-0 subviews along with whatever comes along
in the possible multi-vector.

**Comment by crtrott** [comment]
Ok in order to support this I need a really really compelling reason. The subview logic stuff is one of the most difficult and prone to break parts of Kokkos. 

Also (and this is personal feeling and not consensus in the Kokkos team ;-) ): I don't actually like the "you can give additional arguments" capability of Views, I had customers a couple of times spend many hours trying to figure out what is going wrong, and it turned out they had forgotten a dimension in their typedef, but their code did still compile.

**Comment by ambrad** [comment]
My opinion is that being able to handle local vectors and multi-vectors in the same routine is a compelling reason. However, this was just a feature request, so it's fair to reject it.

**Comment by crtrott** [comment]
This was not a final rejection yet, I was just warning you that you should prepare to make your case for it at the next meeting (which I unfortunately will miss).

**Comment by ambrad** [comment]
Ok, thanks. Re: the extra arguments: Did the customer build with array bounds checking enabled and still not get an informative error? I don't think the potential for error, particularly if a debug build will catch it, is a strong argument against the value of compile-time array rank polymorphism.

**Comment by hcedwar** [comment]
Concept is that all dimensions beyond the rank can be treated as having a value of one.
In optimized extra indices are ignored, with bounds checking extra indices must be zero.

**Comment by ibaned** [comment]
We've recently compiled a substantial number of _new_ user experiences which suggest that the potential for error is a strong (and winning) argument against compile-time rank polymorphism. The most popular error case (which @crtrott refers to above) is this:
```cpp
Kokkos::View<double*> forces("forces", num_atoms, spatial_dim);
Kokkos::parallel_for(num_atoms, KOKKOS_LAMBDA(int atom) {
  forces(atom, 0) = 1.0;
  forces(atom, 1) = -2.0;
});
```
In this case the user wanted to create a 2D view, but forgot a single `*` character in the type name. This example compiles without error or warning and runs without error or warning in most cases. The only symptom is that values seem to all be `-2.0`. I myself as well as @stanmoore1 , @crtrott , and @lxmota have all at some point made this kind of mistake in real production codes and spent inordinate amounts of time debugging them.

Thus Kokkos has decided to move to a "rank-strict by default" design, meaning that in upcoming Kokkos versions the `View::operator()` will no longer accept extra indices, but we will provide a new `View::access()` with that behavior.

This is in recognition of the fact that the overwhelming majority of Kokkos users expect strict rank and only suffer from polymorphism because it hides their mistakes, while the percentage of users that consciously design code around rank-polymorphism is small and advanced enough that they can make the additional effort to use non-standard APIs for this.

Recent experiences make us even more hesistant to add new rank-polymorphic capability, especially something that looks like the mainstream API. I'll close this for now, but if its really really needed by some application, we would want to make it a non-standard interface like `rank_polymorphic_subview`.
