### ISSUE TITLE
TeamPolicy team size 32 (or smaller) with 100% occupancy

### ISSUE THREAD

**Issue by ambrad** [kokkos/kokkos#477]
Right now, a Kokkos team is 1-1 with a Cuda thread block. A thread block must have a minimum of 4 warps to achieve 100% occupancy. 2 warps gives 50%; 1, 25%. Together, these imply that one generally must use a team size of at least 128 threads, and use these 128 threads effectively, to get maximum performance with TeamPolicy.

This issue tracks decoupling the Kokkos team from the Cuda thread block.

A goal is to permit 4 teams per thread block, thus giving 100% occupancy for team size 32.

A use case is equation assembly that is parallelized by finite volume cell or finite element, with one team per element or cell. There is likely to be enough work for perhaps 1 warp, but 4 warps is often too many threads.

In fact, 16 or even 8 threads per team would be nice, but 32 is still much better than 128.

@dsunder mentioned he might also have a use case of interest.

A workaround right now that works as long as one does not need a team reduction or scan (so just team_barrier()) is to divide a team into sub-teams with offsets for the team_rank().

**Comment by crtrott** [comment]
Carter actually needs this for Tasks as well, but there are a couple issues:
(i) Different teams can not share the same warp (that means non-power2 team sizes needs to idle threads)
(ii) More internal resources are required to keep state (for example I need to replicate stuff we keep in shared memory across multiple teams) 
(iii) From my perspective the biggest internal problem is that I can't use static sized shared variables in the implementation. This will a) make implementation much more complicated, and b) have performance issues because I need to pass handles to dynamic shared memory around. 

Here is the another thing: realistically team_size 64 will work for most codes either because they anyway need more registers than 32 per thread or b) 50% occupancy doesn't make much difference to 100% occupancy. 

So summary: This is gonna be a significant overhaul with some real implementation hurdles, and the number of use cases where it helps is not quite clear. 

Here is a lightly less complicated alternative:
Allow team sizes 32 or smaller (i.e. a team is a warp or a sub warp). That is a bit simpler and the only other relevant team_size is probably 64.

**Comment by ndellingwood** [comment]
Maxwell and later architectures allow 32 resident blocks (up from 16); that means with a single warp 50% occupancy is possible. 
Do we want sub-warp team sizes?

**Comment by ambrad** [comment]
@ndellingwood, I think the answer is that (i) a min of 32 would be awesome, but (ii) there's (IMO) no question that there are use cases that would benefit from even fewer. However, @crtrott's point I think is very important: if sub-warp team size requires more bookkeeping overhead, it's probably not a good trade off.

**Comment by crtrott** [comment]
Ok I think I convinced myself that doing (sub-)warpsize team_size is reasonable doable.

**Comment by hcedwar** [comment]
Wait for refactoring that allows this thread-team functionality to be shared with task-team functionality.

**Comment by ibaned** [comment]
This is prerequisite to #577

**Comment by hcedwar** [comment]
Requires CUDA 9 sub-block synchronization mechanisms to work reliably.

**Comment by crtrott** [comment]
I don't think this is a priority, and unlikely to be worth the extra effort for now. We can rethink this if we come across something where it would really help.
