### ISSUE TITLE
Memory Space Classes and Instances

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#478]
When the View uses memory space instances for memory allocation the memory space instance is retained by the shared allocation tracker to deallocate memory.
Thus a memory space class need only carry _accessibility_ information; _e.g._ what space can access what memory space.  For example, their is no accessibility difference between a CudaUVMSpace and a CudaHostPinnedSpace, or between HostSpace and HBWSpace.
The number of memory spaces can be reduced by consolidating memory spaces with identical accessibility traits and differentiating among allocation and deallocation mechanisms by a parameter when obtaining memory space instances.

This will reduce the number of class instantiations and specializations for memory tracking, deep copies, etc.  This will be better for memory placement extensibility; e.g., NUMA placement.  This helps out issue #290 as well.

TBD consolidations:
- HostSpace assimilates HBWSpace as an (experimental) instance parameter
- CudaUVMSpace assimilates CudaHostPinned space as an instance parameter

**Comment by hcedwar** [comment]
Backward compatibility could be maintained as

    HBWSpace : HostSpace { HBWSpace() : HostSpace( use_hbw ); };
    CudaHostPinnedSpace : CudaUVMSpace { CudaHostPinnedSpace() : CudaUVMSpace( use_pinned ); };

**Comment by crtrott** [comment]
I am not sure this is a good idea. We loose compile time tracking of pretty important performance and behavior traits. In particular we would end up with a SINGLE memory space type on practically all future platforms. On both Trinity and Coral every memory space is accessible from every execution space. 

With regards to important information which is really useful at compile time: I would now need to deduce at runtime what the optimal execution space is to run something in. For example if I now allocate something in HostPinnedSpace and I want to run some bandwidth bound operation on it I should do so on the Host Execution Space. While for a UVM space I probably should run it on the GPU. If you make me deduct that at runtime I have to compile twice as much code for that. 

Also after running a kernel using UVM Memory I need a fence before I can run stuff on the host, because of the current semantics. When I run a GPU kernel on HostPinnedMemory I don't need to do that. I can run a Host kernel concurrently.

**Comment by crtrott** [comment]
Consider the above post as a plea not to start implementing this before we have had some serious time to think about the ramifications.

**Comment by hcedwar** [comment]
Yeah - the execution space association is a compile time property as well.
What about HostSpace and HBWSpace ?

**Comment by crtrott** [comment]
What you mean with the execution space association is a compile time property as well? 

HostSpace, HBWSpace might be more feasible. But the current mechanism which we have been recommending for keeping track and changing of what goes where is via a typedef file. I am not quite sure how a new easy mechanism looks like to change the place of an allocation for a set of data arrays throughout a whole code if it is now a runtime option to the constructor.

**Comment by crtrott** [comment]
I can imagine other problems being possible: for example certain load intrinsics may only work on specific memory spaces and error out or so if you try to use them on pointers associated with other memory spaces.

**Comment by crtrott** [comment]
Regarding previous post ^^: for example can one actually create a texture object on a host pinned allocation?

**Comment by hcedwar** [comment]
``MemorySpace::execution_space`` is important compile time knowledge.
Defaults can be set at configure-time.

**Comment by crtrott** [comment]
OK so you agree we can't make HostPinned and UVM Spaces the same?

**Comment by mhoemmen** [comment]
@crtrott wrote:
> I can imagine other problems being possible: for example certain load intrinsics may only work on specific memory spaces and error out or so if you try to use them on pointers associated with other memory spaces.

I think assignment from a View in MemorySpace1 to a View in MemorySpace2 should only work if the program could correctly and efficient execute the same code for either memory space.  For example, the same kernels would work well for either CudaSpace or CudaUVMSpace, or for either HostSpace or HBM.  However, assignment from CudaUVMSpace to HostSpace should _not_ work, even though the same code could technically run with either space, because this hides a performance issue.

**Comment by hcedwar** [comment]
Yup.  But I see pieces of implementation that could have been shared.

**Comment by hcedwar** [comment]
View assignment should require 

- MemorySpace1::execution_space == MemorySpace2::execution_space
- anywhere MemorySpace2 can be accessed MemorySpace1 can be accessed

**Comment by crtrott** [comment]
Yeah sharing of implementation is something one could do. 

Mark: I was actually advocating earlier for a compatibility memory space: it doesn't necessarily give you all intrinsics and it doesn't have any string association with any memory space. Practically something like an UnmanagedSpace. It would allow us to get the reduction we need in kernel instantiations and we can deduct the execution space before pushing of the actual kernel.

**Comment by mhoemmen** [comment]
@crtrott wrote:
> Mark: I was actually advocating earlier for a compatibility memory space: it doesn't necessarily give you all intrinsics ...

What if a kernel uses atomic Views?  Transposed sparse matrix-vector multiply is one example; explicit sparse matrix transpose is another.

**Comment by hcedwar** [comment]
No collapsing of current memory space types.
