### ISSUE TITLE
Nightly clang/7+cuda/9.2 compilation errors with -Werror: Kokkos_Array.hpp:354:1: error: 'tuple_size' defined as a struct template here but previously declared as a class template 

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#4968]
Following merge of #4962 the clang/7+cuda/9.2 nightly job showed compilation errors:

```
22:23:31 In file included from /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkos-dev_clang_701_cuda_92/kokkos/core/src/impl/Kokkos_ViewArray.hpp:48:
22:23:31 /home/jenkins/jenkins-new/workspace/Kokkos_develop_kokkos-dev_clang_701_cuda_92/kokkos/core/src/Kokkos_Array.hpp:354:1: error: 'tuple_size' defined as a struct template here but previously declared as a class template [-Werror,-Wmismatched-tags]
22:23:31 struct std::tuple_size<Kokkos::Array<T, N>>
22:23:31 ^
22:23:31 /projects/sems/install/rhel7-x86_64/sems/compiler/gcc/7.2.0/base/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../include/c++/7.2.0/array:342:5: note: did you mean struct here?
22:23:31     class tuple_size;
22:23:31     ^
22:23:31 In file i
```

**Reproducer**:
```
module load sems-archive-env sems-archive-cmake/3.17.1 sems-archive-gcc/7.2.0 sems-archive-cuda/9.2 sems-archive-clang/7.0.1

$KOKKOS_PATH/generate_makefile.bash --with-devices=Cuda,OpenMP --arch=Kepler35 --compiler=clang++ --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="14" --kokkos-path=$KOKKOS_PATH --no-examples
```

**Comment by dalg24** [comment]
Will be closed by #4969

**Comment by dalg24** [comment]
Some standard libraries define `tuple_size` as a `class`, other use `struct`.  It seems that Clang < 8.0.0 warns about mismatch.  I couldn't trigger the warning with more recent versions.

**Comment by PhilMiller** [comment]
Ugh, if the compilers are going to warn about this, it seems like the choice of keyword used should be specified in the standard.

Do we think newer versions of Clang just don't warn about this anymore (perhaps just when there's no consequent member accessibility differences), or that they've somehow special cased standard library constituents because client code can't rely on it being one or the other?

There's potentially a hypothetical ABI compatibility concern if there's a mismatch that does affect member visibility, because IIRC the standard only specifies consistent member ordering within each visibility, not overall. I don't know that any implementation actually generates layouts other than straight declaration order, but ...

@nliber do you have any insight on this?

**Comment by dalg24** [comment]
> Ugh, if the compilers are going to warn about this, it seems like the choice of keyword used should be specified in the standard.

https://reviews.llvm.org/D55466 suggests that the standard now mandates to use `struct` even though it was not obvious to me when looking at https://eel.is/c++draft/tuple#helper

> Do we think newer versions of Clang just don't warn about this anymore (perhaps just when there's no consequent member accessibility differences), or that they've somehow special cased standard library constituents because client code can't rely on it being one or the other?

Yes that is what I observed
https://github.com/kokkos/kokkos/pull/4969#issuecomment-1100237745
I did get the warning when I specialized my own traits.

**Comment by ndellingwood** [comment]
PR #4969 resolved the issues and the nightly test is back to passing status, thanks @dalg24 !
