### ISSUE TITLE
Do we need a HIP_ENABLE_MANAGED/SYCL_ENABLE_SHARED flag like we have for cuda

### ISSUE THREAD

**Issue by JBludau** [kokkos/kokkos#5193]
This is to discuss (and document) if we want to add a flag to cmake that would enable all allocations into HIP or SYCL be done in the HIPManaged/SYCLShared space as we do with the CudaUVM.

I am leaning towards no, but as there is/was a reason to provide this for cuda, we could reevaluate if this still is a thing.

**Comment by PhilMiller** [comment]
As I understand it, the CUDA flag is there for backwards compatibility, since Kokkos used to allocate UVM by default, and then moved away from that because the most performance sensitive client codes all recognized that they needed to avoid implicit data movement.

On the other hand, for less ambitious applications, automatic allocation in shared memory is a huge convenience. I think the way for them to do that going forward should be use of a suitable type alias or template explicit in their code, or even just writing a memory space into every View declaration. Kokkos could potentially provide some portable expression for that, like SharedMemView, that knows the appropriate space to use for the active backend.

**Comment by JBludau** [comment]
Also for porting stuff to Kokkos a shared space could be a drop-in for things that are required for the code to run but are not yet being redesigned to deal with heterogeneous memory. As not all backends do (currently) support a page migrating memory, providing a portable expression could be incomplete.

**Comment by masterleinad** [comment]
I would be in favor of adding an alias that can be used for backends such as `DefaultSharedMemorySpace` as also suggested by @crtrott. I think we should get rid of a configure-time option to make the default memory space shared since bugs are harder to find.

**Comment by JBludau** [comment]
I favor an alias, I think this would be a nice convenience as they are named differently over the backends.
Other than that, I kind of see that users do not have to explicitly specify a MemorySpace as only benefit of a compile time option. For porting users could just use the alias in all places where they are not sure yet which MemorySpace it be in the end. So I agree with @masterleinad and @dalg24 that we should ditch the configure-time option, if there are no compelling reasons to keep it.

If we provide an alias, I think the name should be more specific, as e.g. host pinned/page locked memory is also device accessible and there is even cpu accessible gpu memory. I suggest, that the memory this alias would point to would logically be a `(page)migrating` memory ... thus we could name it `DefaultMigratingMemorySpace`. Shared could be misunderstood as shared between threads.

**Comment by JBludau** [comment]
I think the responses we got here are enough to draft something and propose a pr. This will reignite the discussions anyway and with having a code to look at it becomes less abstract

**Comment by dalg24** [comment]
As Jakob pointed out `DefaultSharedMemorySpace` is a bad idea because "shared memory" is part of the CUDA terminology and that would likely be confusing.

**Comment by JBludau** [comment]
I will go ahead and close this issue, as the dev-team decided to introduce the aliases `SharedSpace` and `SharedHostPinnedSpace` that are portable to most backends in `Kokkos 4.0`. #5289 and #5405 
Furthermore, it looks like `ENABLE_UVM` and similar functionalities that change the memory space defaults will be deprecated in `4.0` and probably removed in `5.x`
