### ISSUE TITLE
Multiple instances of same league and team rank

### ISSUE THREAD

**Issue by dholladay00** [kokkos/kokkos#531]
I have the following in a code:

```c++
// set schedule type
typedef Kokkos::Schedule< Kokkos::Dynamic > schedule;

// team policy (takes a scheduling parameter)
typedef Kokkos::TeamPolicy<schedule> team_policy;

typedef team_policy::member_type member_type;
int ns = 100;
//  const team_policy policy(ns, AUTO);
const team_policy policy(ns, 2); // test intra-team parallelization
    
parallel_for (policy.set_scratch_size(level, PerTeam(mem_size)),
  KOKKOS_LAMBDA (const member_type & team)
{
  Kokkos::single (PerTeam(team), [&] ()
  {
    printf("League Rank: %i Team Rank: %i \n",
           team.league_rank(), team.team_rank());
  });
  ...
```
In the output, I get:
```
7: League Rank: 74 Team Rank: 0 
7: League Rank: 22 Team Rank: 0 
7: League Rank: 61 Team Rank: 0 
7: League Rank: 9 Team Rank: 0 
7: League Rank: 87 Team Rank: 0 
7: League Rank: 35 Team Rank: 0 
7: League Rank: 48 Team Rank: 0 
7: League Rank: 0 Team Rank: 0 
... 
7: League Rank: 87 Team Rank: 0 
7: League Rank: 61 Team Rank: 0 
7: League Rank: 74 Team Rank: 0 
7: League Rank: 22 Team Rank: 0 
7: League Rank: 35 Team Rank: 0 
7: League Rank: 48 Team Rank: 0 
7: League Rank: 9 Team Rank: 0 
7: League Rank: 0 Team Rank: 0 
```

Notice that the same league rank gets printed twice **even with the same team rank** (74, 22, 61, 9, 87, 35, 48, 0). Perhaps my understanding is incorrect, but I did not expect this behavior. Is this the expected behavior? If not, I can provide more details to help figure out the issue (OpenMP, backend, debug build, intel 16.0.3 compiler, hwloc enabled, etc.)

**Comment by hcedwar** [comment]
This is the correct behavior.  team_rank == rank of thread within a team

Sent from my iPad

On Nov 4, 2016, at 9:26 PM, Daniel Holladay <notifications@github.com<mailto:notifications@github.com>> wrote:


I have the following in a code:

// set schedule type
typedef Kokkos::Schedule< Kokkos::Dynamic > schedule;

// team policy (takes a scheduling parameter)
typedef Kokkos::TeamPolicy<schedule> team_policy;

typedef team_policy::member_type member_type;
int ns = 100;
//  const team_policy policy(ns, AUTO);
const team_policy policy(ns, 2); // test intra-team parallelization

parallel_for (policy.set_scratch_size(level, PerTeam(mem_size)),
  KOKKOS_LAMBDA (const member_type & team)
{
  Kokkos::single (PerTeam(team), [&] ()
  {
    printf("League Rank: %i Team Rank: %i \n",
           team.league_rank(), team.team_rank());
  });
  ...

In the output, I get:

7: League Rank: 74 Team Rank: 0
7: League Rank: 22 Team Rank: 0
7: League Rank: 61 Team Rank: 0
7: League Rank: 9 Team Rank: 0
7: League Rank: 87 Team Rank: 0
7: League Rank: 35 Team Rank: 0
7: League Rank: 48 Team Rank: 0
7: League Rank: 0 Team Rank: 0
...
7: League Rank: 87 Team Rank: 0
7: League Rank: 61 Team Rank: 0
7: League Rank: 74 Team Rank: 0
7: League Rank: 22 Team Rank: 0
7: League Rank: 35 Team Rank: 0
7: League Rank: 48 Team Rank: 0
7: League Rank: 9 Team Rank: 0
7: League Rank: 0 Team Rank: 0


Notice that the same league rank gets printed multiple times even with the same team rank. Perhaps my understanding is incorrect, but I did not expect this behavior. Is this the expected behavior? If not, I can provide more details to help figure out the issue (OpenMP, backend, debug build, intel 16.0.3 compiler, hwloc enabled, etc.)

-

**Comment by dholladay00** [comment]
So multiple teams can have the same league rank?

**Comment by hcedwar** [comment]
League of teams of threads

league_size == number of teams in the league
League_rank == which team within the league
Team_size == number threads in the team
Team_rank == which thread within the team


Sent from my iPad

On Nov 6, 2016, at 1:21 PM, Daniel Holladay <notifications@github.com<mailto:notifications@github.com>> wrote:


So multiple teams can have the same league rank?

-

**Comment by dholladay00** [comment]
Yes, I do not think I am arguing against that.

But shouldn't a `parallel_for` of a team policy launch `league_size` number of teams with each team having a unique `league_rank`? 

In the above output, the numbers in separated by the `…` are the same but in a different order. I would have suspected to have seen a list with no repeated values for the `league_rank`

**Comment by crtrott** [comment]
This looks like a bug. Do you have a full reproducer I can just copy and paste? Or does the above work with just an initialize and finalize added?

Carter: the problem is that he gets two print outs with League Rank 74 and team rank 0 (the same for league rank 61 and 22 etc. ). This should not happen from what I can see.

**Comment by crtrott** [comment]
Hi I just tried to reproduce but don't seem to get the problem (also with Intel 16.0.3):

Code:
```C++
#include<Kokkos_Core.hpp>

int main() {
  Kokkos::initialize();
  int level = 0;
  int mem_size = 512;
  // set schedule type 
  typedef Kokkos::Schedule< Kokkos::Dynamic > schedule;

  // team policy (takes a scheduling parameter)
  typedef Kokkos::TeamPolicy<schedule> team_policy;

  typedef team_policy::member_type member_type;
  int ns = 100;
  //  const team_policy policy(ns, AUTO);
  const team_policy policy(ns, 2); // test intra-team parallelization

  Kokkos::parallel_for (policy.set_scratch_size(level, Kokkos::PerTeam(mem_size)),
  KOKKOS_LAMBDA (const member_type & team)
  {
    Kokkos::single (Kokkos::PerTeam(team), [&] ()
    {
      printf("League Rank: %i Team Rank: %i \n",
                  team.league_rank(), team.team_rank());
    });
  });
  Kokkos::finalize();
}
```
Compilation:
```
make KOKKOS_DEVICES=OpenMP KOKKOS_ARCH=HSW CXX=icpc -j 8 KOKKOS_USE_TPLS=hwloc HWLOC_PATH=${SEMS_HWLOC_ROOT}
```
Output:
```
[crtrott@apollo BugTeamMultiplePrints]$ ./main.host | awk '{print $3 " " $6}' | sort --numeric
0 0
1 0
2 0
3 0
....
98 0
99 0
```

**Comment by dholladay00** [comment]
Yeah, I do not recall if the above was before or after I updated Kokkos to the latest release. I am not seeing that issue anymore, but I am seeing another issue, but it is probably due to user error. I will close this issue as I can no longer reproduce it. But please save that code as I will have something for you to add to it.

**Comment by crtrott** [comment]
Sure thing :-)
