### ISSUE TITLE
exp() for Kokkos::Complex

### ISSUE THREAD

**Issue by bathmatt** [kokkos/kokkos#546]
exp is a very common feature when one does complex math, it comes in the greens function of a lot of applicaionts.  Do you mind if we add it.

Just FYI, since I just figured it out
e^(x+iy) =e^x * e^iy =  e^x*(cos(y)+isin(y))

**Comment by mhoemmen** [comment]
@bathmatt I don't mind in this case, but in general I'm not keen on Kokkos or Trilinos getting into the business of correct implementation of transcendental functions.

We may even want to think about making Kokkos::complex just a wrapper for the compiler's native complex type.  For CUDA, that would be cuDoubleComplex.  Otherwise, prefer `double _Complex` without CUDA, if the compiler supports it (Visual Studio 2015 isn't quite C99-compilant, so I'm guessing it doesn't), else `std::complex<double>`.  With the right conversion operators, that would let the standard library functions "just work."  We could perhaps also get this effect by adding conversion operators to the existing Kokkos::complex implementation.

**Comment by bathmatt** [comment]
That is what I'm trying to go, basically just being able to swap between the std::Complex and Kokkos::complex shouldn't be too, (sorry) complex :)...  
I've added a local version of the function so I can do what I need.

**Comment by mhoemmen** [comment]
@bathmatt Kokkos::complex<T> already has a (host-only) conversions to (line 98 of kokkos/core/src/Kokkos_Complex.hpp) and from (line 89 of the same file) std::complex<T>.  This should make it possible to use the standard C++ functions on host.

For CUDA, we would need to add a few things:
  1. `#include <cuComplex.h>` in Kokkos_Complex.h
  2. Add a traits class to map from Kokkos::complex<T> to get the right CUDA native type (cuFloatComplex or cuDoubleComplex)
  3. Add a typedef to Kokkos::complex<T> to get the right CUDA native type
  4. Add conversion operators (__host__ __device__ I think)

**Comment by mhoemmen** [comment]
Also, if you do decide to add this for Kokkos::complex, please make it a free function and not an instance method.  Thanks Matt! :-D

**Comment by bathmatt** [comment]
@mhoemmen I guess wrapping would fix the issue with std::complex, but not on cuda since they don't seem to have a complex exp.  I can add the exp, but I don't see what wrapping will do for the cuda issue.  We would still need to do the exp unrolling.

**Comment by mhoemmen** [comment]
@bathmatt argh, then, guess we have to roll our own exp ;-P  would still prefer to defer to the standard library function if CUDA is not enabled, though.

**Comment by ndellingwood** [comment]
@crtrott implemented this nearly a year ago, only unit testing was needed. I added that and an `exp` overload (for host side only) that accepts a `std::complex` argument in PR #1569
