### ISSUE TITLE
HIP Link issue

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#5489]
Using: 

Configure with ROCM 5.2.0:
```
cmake -DKokkos_ENABLE_HIP=ON -DKokkos_ARCH_VEGA908=ON -DKokkos_ENABLE_TESTS=ON ../
```

```
ld.lld: error: undefined symbol: __truncdfhf2
>>> referenced by amd_hip_fp16.h:101 (/home/projects/ROCm/rocm-5.2.0/include/hip/amd_detail/amd_hip_fp16.h:101)
>>>               CMakeFiles/KokkosCore_UnitTest_Default.dir/default/TestDefaultDeviceType.cpp.o:(Test::Functor_TestHalfOperators<Kokkos::View<double*, Kokkos::HostSpace>, Kokkos::Experimental::Impl::floating_point_wrapper<__half> >::operator()(int) const)
>>> referenced by amd_hip_fp16.h:101 (/home/projects/ROCm/rocm-5.2.0/include/hip/amd_detail/amd_hip_fp16.h:101)
>>>               CMakeFiles/KokkosCore_UnitTest_Default.dir/default/TestDefaultDeviceType.cpp.o:(Test::Functor_TestHalfOperators<Kokkos::View<double*, Kokkos::HostSpace>, Kokkos::Experimental::Impl::floating_point_wrapper<__half> >::operator()(int) const)
>>> referenced by amd_hip_fp16.h:101 (/home/projects/ROCm/rocm-5.2.0/include/hip/amd_detail/amd_hip_fp16.h:101)
>>>               CMakeFiles/KokkosCore_UnitTest_Default.dir/default/TestDefaultDeviceType.cpp.o:(Test::Functor_TestHalfOperators<Kokkos::View<double*, Kokkos::HostSpace>, Kokkos::Experimental::Impl::floating_point_wrapper<__half> >::operator()(int) const)
>>> referenced 1 more times
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by crtrott** [comment]
This is also noted in the crusher known issues section:

https://docs.olcf.ornl.gov/systems/crusher_quick_start_guide.html#olcfdev-1167-kokkos-build-failures-with-prgenv-amd

**Comment by crtrott** [comment]
@Rombur

**Comment by Rombur** [comment]
Yeah, I know. It's on my TODO list.

**Comment by jjellio** [comment]
I've been hitting this for a while, and assumed this issue was related to a more general defect with ROCM that broke ROCM linking it's builtins. 

This seems like a defect in ROCm - and the PR that "fixes" it, feels like a workaround - and AMD needs to fix this.

That said, has AMD provided any justification for why you need to explicitly link against the builtins? (I've always viewed compiler internal libraries to be something only the compiler should touch - assuming things are working correctly).

I've opened a bug report under the CORAL2 contract for this, but I'd enjoy any feedback here (or through Email jjellio at sandia.gov). It seems you shouldn't have to do what's in the PR here.

**Comment by Rombur** [comment]
> has AMD provided any justification for why you need to explicitly link against the builtins?

No they didn't. We asked them if they would fix this and the answer was 'probably not`. The plan is to fix this through HIP support in CMake.

**Comment by jjellio** [comment]
Thanks for the info.  We had a discussion about this at the CORAL2 quarterly. I think the real question is whether AMDClang should default to using LLVM's builtins or the underlying GCC's builtins.

I'll keep you in the loop.

**Comment by jjellio** [comment]
FYI - as of ROCM 5.5, AMD clang is now handling their builtins without the need for a workaround (no more explicit linking) - you may want to see if you can revert your PR so keep that cruft out of Kokkos.
