### ISSUE TITLE
Fences from Kokkos Tools are undesirable in certain cases

### ISSUE THREAD

**Issue by vlkale** [kokkos/kokkos#5548]
**Describe the bug**
Please provide a concise, clear description of the bug, as well as any available error logs. 

When using profiling tools of Kokkos to profile a Kokkos application, Kokkos invokes memory fences that are unneeded. This is particularly the case when a memory fence in a Kokkos application code is itself being profiled. These unneeded memory fences used by the tool are not desirable because they slow down execution of the application when the Kokkos tools are being used and do not reflect the actual performance of the application code. If this problem is not fixed, then users of profiling tools will not obtain an accurate performance profile of the application's execution. Changing the Kokkos tools libraries by removing, or filtering out, the memory fences under particular context where they are not needed will not impact the correctness of the application code. A solution is to filter out the unneeded fences under particular contexts. 

** Details of the problem ** 

This problem is applicable to Kokkos v. 3.7.0 on any platform. More information and example code for reproducing this problem will be added soon by Vivek.

**Any additional info** 

Discussed with @crtrott on Oct. 11th, and discussed in end of Kokkos team meeting on October 12 by Damien and @crtrott. More details on problem and reproducing the error to be added by Vivek  in the next few days. @crtrott has a reproducer already.

**Comment by crtrott** [comment]
Yeah this should go into the Kokkos Tools repo: A bit more clarification - there are actual two orthogonal issues:

1. Some tools need to turn off fencing of tool callbacks, depending on how the tool is used. These tools (like the space-time-stack and simple kernel timer) need to be able to read an environment variable which sets the ON/OFF behavior for the tool setting callback. Specifically: spaceTimeStack and the vendor tools need that.

2. If tool callback fencing is on AND the tool implements the callback for fencing, we want to filter out fences which are solely due to callback fencing. Note these are different things: a callback for "begin parallel for" invokes a Kokkos global fence if callback fencing is on [i.e. calls Kokkos::fence()], but a global fence ALSO invokes the tools callback for "begin fence" and "end fence"). 

To illustrate: with tools fencing ON:
```c++
Kokkos::fence();

Kokkos::parallel_for(...);
```
expands conceptually into:
```c++
// Kokkos::fence();
beginFence();
fence_impl();
endFence();

// Kokkos::parallel_for();
beginFence();
fence_impl();
endFence();
beginParallelFor();
parallel_for_impl();
beginFence();
fence_impl();
endFence();
endParallelFor();
```

With tools fencing off it expands into:
```c++
// Kokkos::fence();
beginFence();
fence_impl();
endFence();

// Kokkos::parallel_for();
beginParallelFor();
parallel_for_impl();
endParallelFor();
```

These fences invoked by beginParallelFor and endParallelFor have specific string labels attached, so we should be able to filter them out inside the tool.

Any tool which currently implements the fence callback probably should do this filtering.

**Comment by vlkale** [comment]
@ajpowelsnl This is a tools issue, so yes. (And thanks @crtrott for the reply.) I will move it to the Kokkos-tools repo now. 


@crtrott :  I will update the GitHub issue with these clarifications below

**Comment by vlkale** [comment]
@ajpowelsnl  cc. @dalg24  This github Issue is migrated to: https://github.com/kokkos/kokkos-tools/issues/147

**Comment by ajpowelsnl** [comment]
Please see the `kokkos-tools` issue:  https://github.com/kokkos/kokkos-tools/issues/147
