### ISSUE TITLE
Kokkos and C++ standards

### ISSUE THREAD

**Issue by dutkalex** [kokkos/kokkos#5597]
Hi! I was wondering what is Kokkos' policy regarding C++ standards. Basically, I would like to be able to use some C++20 features in non-Kokkos parts of my code (which is currently in C++17), but I don't know if I can pull this off since NVCC doesn't support it yet. Is it possible to compile host code in C++20 mode while device code remains in C++17 mode to stay portable accross architectures? I could not find a definitive answer in the documentation or in the other issues, but does Kokkos allows this or is it required to compile with a uniform standard accross all the code?

**Comment by PhilMiller** [comment]
Kokkos as such wouldn't have reason to object, but I don't think you can expect this to work in general. Besides lagging compiler support that you mentioned, mixing different language version settings can lead to ABI differences that will break the code:
https://github.com/abseil/abseil-cpp/blob/master/FAQ.md#what-is-abi-and-why-dont-you-recommend-using-a-pre-compiled-version-of-abseil

Host and device code need common ABI because there are structures copied byte-wise between them, including the closures containing captured variables of lambdas.

**Comment by ajpowelsnl** [comment]
Hi @dutkalex - did our response address the question about host / device code and C++ Standards?

**Comment by dutkalex** [comment]
Hi! Yes absolutely @ajpowelsnl. Thanks for the answer, I hadn't thought of these ABI concerns and I guess we'll just have to wait for NVCC to support C++20. I think you can consider this issue closed.
