### ISSUE TITLE
Evaluate use of 'volatile' in reductions

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#561]
The following articles were noted regarding the use of `volatile` qualifier:

https://www.kernel.org/doc/Documentation/volatile-considered-harmful.txt

https://lwn.net/Articles/233482/

Evaluate Kokkos' use of `volatile` and memory fences to be sure `volatile` is necessary and, if so, document why.

**Comment by ndellingwood** [comment]
@hcedwar The links did not come through, could you repost?

**Comment by hcedwar** [comment]
Is this possibly a CUDA-only thing?

http://developer.download.nvidia.com/assets/cuda/files/reduction.pdf - slide #22

https://books.google.com/books?id=q3DvBQAAQBAJ&pg=PA117&lpg=PA117&dq=cuda+reduction+volatile&source=bl&ots=KgtY2ktFK7&sig=ya7w0kpMeASFNXaoMkYEH_DylSw&hl=en&sa=X&ved=0ahUKEwjpvo_k3N3QAhUNxmMKHeCJCWMQ6AEIWjAJ#v=onepage&q=cuda%20reduction%20volatile&f=false

http://stackoverflow.com/questions/21205471/cuda-in-warp-reduction-and-volatile-keyword

**Comment by crtrott** [comment]
No its not just a Cuda only thing. As the original document said the main point of volatile is to prevent the compiler of optimizing the load away. I believe we have actual legitimate places where we need that (for example implementing our own spinloops).  As the article said there are other things which can serve as a compiler barrier, but we have cases where we don't have those other things in the code. That said there are probably a couple of places where a volatile might be unnecessary. For example the team_broadcast in OpenMP probably doesn't need it, since the second load could only be optimized away for the master thread of the team which already got the correct value.

**Comment by mhoemmen** [comment]
I'm with @crtrott .  "volatile" has nothing to do with the memory model.  It just keeps the compiler from putting that variable in a register.  On the other hand, it's sure annoying to require volatile overloads in a class that I want to use as a reduction type ;-)
