### ISSUE TITLE
-rdc=true question

### ISSUE THREAD

**Issue by ambrad** [kokkos/kokkos#580]
Are there plans to allow -rdc=true? Right now I see
```
nvlink error   : Multiple definition of 'kokkos_impl_cuda_constant_memory_buffer' in 'tu1.o', first defined in 'main.o'
nvlink error   : Multiple definition of 'kokkos_impl_cuda_lock_arrays' in 'tu1.o', first defined in 'main.o'
```
when I try to link a device function in one translation unit (main.o) to another in another translation unit (tu1.o). This isn't a feature request but rather simply a question of whether supporting relocatable code is an eventual goal. (Or maybe I just messed something up in my test, of course, and it already works...)

**Comment by ambrad** [comment]
Woot, got it, I think. I ran generate_makefile.sh with
```
--with-cuda-options="rdc"
```
Then I built and installed Kokkos. Finally, to build my test app, I modified nvcc_wrapper to have
```
 cuda_args="-rdc=true"
```
The app builds and runs.

So, let me modify this questions to two user questions:

1. Did I do the standalone Kokkos version correctly? Or what's the intended usage?

2. What should I in the Trilinos cmake config to get rdc in the Kokkos inside of Trilinos?

**Comment by ambrad** [comment]
OK, modifying cuda_args is not necessary; instead, pass
```--relocatable-device-code=true```
to nvcc_wrapper. Great. Next I'm going to see if I can figure out Trilinos.

**Comment by crtrott** [comment]
Technically if you build against an installed Kokkos and you use the installed Makefile.kokkos as an include the option should come in via the KOKKOS_CXXFLAGS if they don't that would be a bug. For cmake you need to add all the cxx flags manually to CXXFLAGS and you need to add the internal Kokkos define as well (i.e. the one which is inside of KokkosCore_config.h of the installed kokkos). We did not add this option yet to cmake since it is somewhat experimental and has a number of site-effects. But it is required to do tasking on GPUs.

**Comment by crtrott** [comment]
Btw. it also reduces kernel launch time in Kokkos by something like 25-40%, because it allows us to copy certain things to the gpu at initialize instead of before every kernel launch.

**Comment by ambrad** [comment]
Awesome! Thanks. So, bottom line is that rdc in Trilinos is planned for the near future? I just need that as a design point.
