### ISSUE TITLE
CMake deduplication issue with `hip::device`

### ISSUE THREAD

**Issue by etiennemlb** [kokkos/kokkos#5898]
Does Kokkos support the following, that is, using the ROCm HIP package and Kokkos simultaneously:
```
add_library(mylib STATIC)
find_package(hip)
find_package(Kokkos)
target_link_library(mylib hip::device Kokkos::kokkos)
```
If this is a use case Kokkos wishes to support, I must report that explicitly switching `-x hip` on Clang based compilers like it is done in `cmake/kokkos_arch.cmake` seems flawed. Indeed, linking with `hip::device` has the side effect of adding the `-x hip` flag which Kokkos does too. For a reason I ignore, CMake's parameter deduplication will remove the `hip` of the `-x hip` provided by Kokkos leaving the `-x` dangling. In my reproducer, this produces the string `-x --rocm-patch` which Clang surely complains about.

The issue shows up in the client code, not when compiling Kokkos.
	
A solution could be to add the [SHELL:](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/1841) prefix like so: `GLOBAL_APPEND(KOKKOS_AMDGPU_OPTIONS "SHELL:-x hip")` (line ~216 in `cmake/kokkos_arch.cmake`). I fear side effects but it did work flawlessly in my case.

If the lack of `SHELL:` is indeed a bug, there might be more places in Kokkos where the same remark as the one in this issue should be applied.

Here is a representation of the issue using ninja (same issue with make).

When linking with Kokkos only:
```
DEFINES = -DKOKKOS_DEPENDENCE -D__HIP_ROCclr__
DEP_FILE = CMakeFiles/mylib.dir/sources/internal/configuration.cpp.o.d
FLAGS = -O3 -DNDEBUG -Wall -Wextra -Wpedantic -O3 -fopenmp -march=znver3 -mtune=znver3 -fno-gpu-rdc -x hip --rocm-path=/opt/rocm-5.2.3 --offload-arch=gfx90a -std=gnu++17
```

When linking with Kokkos and `hip::device`. Note that the `-x hip` becomes `-x --rocm-path`.
```
DEFINES = -DKOKKOS_DEPENDENCE -D__HIP_PLATFORM_AMD__=1 -D__HIP_PLATFORM_HCC__=1 -D__HIP_ROCclr__
DEP_FILE = CMakeFiles/mylib.dir/sources/internal/configuration.cpp.o.d
FLAGS = -O3 -DNDEBUG -mllvm -amdgpu-early-inline-all=true -mllvm -amdgpu-function-calls=false -Wall -Wextra -Wpedantic -O3 -x hip --offload-arch=gfx90a -fopenmp -march=znver3 -mtune=znver3 -fno-gpu-rdc -x --rocm-path=/opt/rocm-5.2.3 --offload-arch=gfx90a -std=gnu++17
```

CMake version 3.20.2 (note that I tried the 3.25). It does not look like a CMake issue.
Kokkos version (3.7.01).
ROCm, 5.2.3 (but would happen with version starting at least from 4.5).

Reproducer:
```
cmake_minimum_required(VERSION 3.16)
project("AnExampleProject"
        LANGUAGES CXX)
set(Kokkos_ENABLE_HIP ON CACHE BOOL "")
set(Kokkos_ARCH_VEGA90A ON CACHE BOOL "")
add_subdirectory(kokkos)
set(GPU_TARGETS "gfx90a" CACHE STRING "" FORCE)
find_package(hip REQUIRED)
add_library(mylib configuration.cc) # configuration.cc is only: int main() {}
target_link_libraries(mylib Kokkos::kokkos hip::device)
```

Compile command:
`cmake -DCMAKE_CXX_COMPILER=CC -DCMAKE_CXX_STANDARD=17 -G Ninja ..  && ninja`

Modules:
```
Currently Loaded Modules:
  1) craype-x86-trento    3) craype-network-ofi       5) cce/15.0.0      7) cray-dsmml/0.2.2    9) cray-libsci/22.11.1.2  11) amd-mixed/5.2.3
  2) libfabric/1.15.2.0   4) perftools-base/22.09.0   6) craype/2.7.19   8) cray-mpich/8.1.21  10) PrgEnv-cray/8.3.3      12) craype-accel-amd-gfx90a
```

You could change `amd-mixed` for a rocm.

CMake configuration and compilation output:
```
-- The CXX compiler identification is Clang 15.0.2
-- Cray Programming Environment 2.7.19 CXX
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/cray/pe/craype/2.7.19/bin/CC - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting default Kokkos CXX standard to 17
-- The project name is: Kokkos
-- Compiler Version: 15.0.0
-- SERIAL backend is being turned on to ensure there is at least one Host space. To change this, you must enable another host execution space and configure with -DKokkos_ENABLE_SERIAL=OFF or change CMakeCache.txt
-- Using -std=gnu++17 for C++17 extensions as feature
-- Built-in Execution Spaces:
--     Device Parallel: Kokkos::Experimental::HIP
--     Host Parallel: NoTypeDefined
--       Host Serial: SERIAL
-- 
-- Architectures:
--  VEGA90A
-- Found TPLLIBDL: /usr/include  
-- Found TPLROCM: /opt/rocm-5.2.3/hip/lib/libamdhip64.so  
-- Using internal desul_atomics copy
-- Kokkos Devices: SERIAL;HIP, Kokkos Backends: SERIAL;HIP
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- hip::amdhip64 is SHARED_LIBRARY
-- Performing Test HIP_CLANG_SUPPORTS_PARALLEL_JOBS
-- Performing Test HIP_CLANG_SUPPORTS_PARALLEL_JOBS - Failed
-- Configuring done
-- Generating done
-- Build files have been written to: /lus/home/BCINES/dci/malaboeuf/repos/kokkos_tests/build
[1/31] Building CXX object CMakeFiles/mylib.dir/configuration.cc.o
FAILED: CMakeFiles/mylib.dir/configuration.cc.o 
/opt/cray/pe/craype/2.7.19/bin/CC -DKOKKOS_DEPENDENCE -D__HIP_PLATFORM_AMD__=1 -D__HIP_PLATFORM_HCC__=1 -D__HIP_ROCclr__ -Ikokkos -Ikokkos/core/src -I../kokkos/core/src -I../kokkos/core/src/../../tpls/desul/include -Ikokkos/containers/src -I../kokkos/containers/src -Ikokkos/algorithms/src -I../kokkos/algorithms/src -Ikokkos/simd/src -I../kokkos/simd/src -isystem /opt/rocm-5.2.3/hip/include -isystem /opt/rocm-5.2.3/llvm/lib/clang/14.0.0/include/.. -isystem /opt/rocm-5.2.3/include -fno-gpu-rdc -x hip --rocm-path=/opt/rocm-5.2.3 --offload-arch=gfx90a -x --offload-arch=gfx90a -std=gnu++17 -MD -MT CMakeFiles/mylib.dir/configuration.cc.o -MF CMakeFiles/mylib.dir/configuration.cc.o.d -o CMakeFiles/mylib.dir/configuration.cc.o -c ../configuration.cc
clang-15: error: language not recognized: '--offload-arch=gfx90a'
clang-15: warning: ../configuration.cc: 'linker' input unused [-Wunused-command-line-argument]
[27/31] Building CXX object kokkos/core/src/CMakeFiles/kokkoscore.dir/impl/Kokkos_Core.cpp.o
ninja: build stopped: subcommand failed.
```

**Comment by lucbv** [comment]
@masterleinad @dalg24 
You guys would probably know what Kokkos Core is supporting in this case?
In general do we have documentation and policies around what is supported by the library?

**Comment by Rombur** [comment]
Why do you want to use `find_package(hip)`? Last I heard, the CMake support for ROCm using `find_package(hip)` was terrible... That's why we don't use it and we link to the ROCm libraries ourselves.

**Comment by crtrott** [comment]
No matter whether its terrible we need to resolve this issue. Same could happen via other paths, when linking different libs.

**Comment by etiennemlb** [comment]
> Why do you want to use `find_package(hip)`? Last I heard, the CMake support for ROCm using `find_package(hip)` was terrible... That's why we don't use it and we link to the ROCm libraries ourselves.

I'm willing to use an alternative, what do you propose ?

**Comment by jjellio** [comment]
Using `hipcc` triggers other issues (forced runpath linking, odd ROCM_PATH handling, and slightly different link behavior from amdclang, not to mention the flags they add)

It feels like Kokkos (and downstream) will have to decide if they want to go down the path of Language HIP. Or kokkos will need to support both paths. As using language HIP, I believe, will "find" ROCM - and hence do the `-x` business for you.  But it's a mess, because downstream needs to stay on that same page, otherwise they are going to have to handle HIP flags.

CMake's ROCM support has been flaky, but it's also been getting alot of testing lately.... and it's also absorbing some of the "fixes" that Kokkos (and others) have had to add. Like adding the clang builtins to the link line. (I disagree that CMake is the correct way to fix that - I think if AMD should wire their compiler to default to clang's builtins NOT GNUs - and force the  user to enabler the latter, rather than the other way around...)

Downstream people, like ... Trilinos/Kokkos Kernels would be directly impacted by all of this...  Maybe the best thing would be for kokkos to make it explicit, `-DKokkos_USE_CMAKE_LANGUAGE_HIP:BOOL=False|True` (with the current code being the default, and the path that will find/use CMake for HIP as a language being the second...  downstream could then look for that Variable and decide what they have to do... but I still think it all stinks.  A better solution would be to pressure KItware to improve how it handles languages so this stuff can cascade downstream w/out all the hoops and ladders

**Comment by crtrott** [comment]
Don't we already support the HIP as CMake language stuff? So you can totally to that if you like, in which case we don't add -x hip manually. Just add `-DKokkos_ENABLE_COMPILE_AS_CMAKE_LANGUAGE=ON`. As James said, that means you have to add the property on each of your source files, since language is not inherited via target properties. But that should work.

**Comment by crtrott** [comment]
Note the patch release is only for 4.0.1 not 3.7.02 (we are not fixing HIP issues in the 3.7 long term support releases).

**Comment by crtrott** [comment]
Hm just looking at this. Are we appending `-xhip` and `-x cuda` even when building with CMake as language?

**Comment by crtrott** [comment]
Just confirmed that for CUDA and CLang++ as CUDA compiler. We do append -x cuda always. Same for -x hip.

**Comment by etiennemlb** [comment]
Should we close this issue ?

**Comment by ajpowelsnl** [comment]
@etiennemlb, @jjellio, @crtrott -- are there `TODO` on the Kokkos side to address this issue?
