### ISSUE TITLE
Figuring out how to get Tpetra solves and assembly to thread-scale using OpenMP

### ISSUE THREAD

**Issue by kongm** [kokkos/kokkos#601]
Hi,

I have a code that uses Teuchos::MPI, and I've attempted to add shared-memory parallelism via kokkos and its parallel_for. However, regardless of the number of threads, the performance almost doesn't change. 

I'm using Trilinos 12.2.1. I've checked previous Kokkos issues and there are some that sound related (#149 and #377), but I doubt are the same. FYI, I'm using Intel MPI. 

Thanks,

**Comment by nmhamster** [comment]
@kongm can you please send us the MPI run line and `OMP_` environment variables you are using? We would like to check these first.

**Comment by mhoemmen** [comment]
@kongm The short answer: "It depends."

Not all of the code is thread parallel yet; this is ongoing work for us.  Not all algorithms can benefit from thread parallelism.  You need enough data for thread parallelism to pay off.  You may have to change algorithms in some cases, or set nondefault settings.  We don't enable some thread-parallel algorithms by default, because adding threads will change the order of operations and thus introduce different rounding errors.

Our general experience is that, unless you have an Intel Xeon Phi or an NVIDIA GPU, threads like won't give you a huge benefit over an MPI-only approach.  This is not just a Trilinos thing; this seems to be true for many applications.  So, please don't have unrealistic expectations.  Threads are not a magic "go faster" button.

**Comment by kongm** [comment]
I'm only using OMP_NUM_THREADS, and this is the same number I'm passing to
kokkos::initialize.
My running command is: mpirun -n ${NTHREADS} ./binary

In addition, I've tried some of Intel's MPI environment variables:
export I_MPI_PIN=1
export I_MPI_PIN_DOMAIN=sock

**Comment by kongm** [comment]
So the application I have spends almost equal amount of time assembling
matrices and vectors as on Belos' linear solver.
I've only been working a few months with Trilinos. So I'm wondering if
something inside Tpetra or Belos (or IfPack2 or Teuchos MPI) could be
changing the number of threads internally. The code scales reasonably well
using only MPI, however even when using a single process and any number of
threads, the performance doesn't change.

Thanks,

**Comment by mhoemmen** [comment]
> So the application I have spends almost equal amount of time assembling matrices and vectors as on Belos' linear solver.

Is the application doing this in a thread-parallel way?  Tpetra gives you ways to create graphs and matrices in a thread-parallel way, but you (the application) must parallelize that.

> So I'm wondering if something inside Tpetra or Belos (or IfPack2 or Teuchos MPI) could be changing the number of threads internally.

Nothing in Tpetra, Belos, Ifpack2, or Teuchos' MPI wrappers (those are really just thin wrappers over MPI functions) changes the number of threads internally.

What preconditioner(s) are you using?

**Comment by kongm** [comment]
Currently the assembly is done in parallel with MPI, with a rowise partition for the matrices. I'm using Tpetra::CrsMatrix, but the elements are computed somewhat redundantly due to the partitioning used. Hence, I want to use kokkos::OpenMP, mainly in the hopes of minimizing some communication of imports/exports.

The preconditioner I'm using is Gauss-Seidel.

**Comment by mhoemmen** [comment]
> The preconditioner I'm using is Gauss-Seidel.

If you switch to the latest Trilinos (develop branch of repository here), you can experiment with our new multithreaded Gauss-Seidel.  If you're interested in that, please let me know and I'll show you how to enable that option.  As a preliminary experiment to judge thread scaling, you could use Jacobi instead of Gauss-Seidel.

> Currently the assembly is done in parallel with MPI, with a rowise partition for the matrices.

Threaded assembly means _you_ do the threading, over rows of the matrix.  You have to write the thread-parallel loop using OpenMP, Kokkos, etc., and call Tpetra functions in the body of that loop.  This only works with Tpetra::CrsMatrix::{replace, sumInto}*Values, for owned rows only, and only for a StaticProfile CrsMatrix.  We recommend making the CrsMatrix with a fill-complete CrsGraph for best performance.  See Tpetra Lesson 04:

https://trilinos.org/docs/dev/packages/tpetra/doc/html/index.html

**Comment by kongm** [comment]
The Jacobi preconditioner in Trilinos 12.2.1 doesn't scale with the number of threads in my application, but it does with the number of processes. I wouldn't mind trying the new Gauss-Seidel.

And yes, I'm performing the threaded assembly with kokkos::parallel_for, and I do call fillComplete as in the lesson. Nonetheless, the threaded assembly doesn't give any benefit with any number of processes or threads.

**Comment by mhoemmen** [comment]
> The Jacobi preconditioner in Trilinos 12.2.1 doesn't scale with the number of threads in my application, but it does with the number of processes.

You'll have to use a newer version of Trilinos.  I recommend trying the develop branch from the repo.  Otherwise, you won't get the new version of Gauss-Seidel yet.

> Nonetheless, the threaded assembly doesn't give any benefit with any number of processes or threads.

We have performance results that show comparable results between threaded assembly with P/T MPI processes and T threads, and P MPI processes with no threads. 

It's likely you'll need to figure out how to make MPI processes stay within NUMA regions, and that sort of thing.

**Comment by crtrott** [comment]
Jus threaded assembly is something which should work reasonably well. There is some overhead due to things like atomic operations compared to compiling for serial execution, but generally thread scalability should be great. So checking for affinity settings might be worthwhile. For example some MPI implementations by default bind a process to a single core. If you now launch multiple threads on the single core you don't gain anything (ignoring hyper threads for now). In fact if you keep adding threads it should just get slower and slower because all the CPUs cycles are eaten up by context switching between different threads.

**Comment by nmhamster** [comment]
Hi @kongm you shouldn't be running: ` mpirun -n ${NTHREADS} ./binary`. Can you try something like the following:

1. `mpirun -n 2 -env OMP_NUM_THREADS=16 -env OMP_PLACES=cores -env OMP_PROC_BIND=true -binding domain=socket ./binary`
2. `mpirun -n 32 -env OMP_NUM_THREADS=1 -env OMP_PLACES=cores -env OMP_PROC_BIND=true -binding domain=core ./binary`

Version (1) will run a threaded algorithm with appropriate OpenMP thread binding and (2) will run an MPI-only equivalent.

**Comment by mhoemmen** [comment]
Actually, Jacobi in 12.2 should be threaded just fine.  See my colleagues' comments above.

**Comment by MDBrothers** [comment]
@kongm as a fellow user, I'm very interested in your results from following @nmhamster 's instructions.

**Comment by mhoemmen** [comment]
Our experience is that Tpetra + Belos solves with recent Trilinos versions thread-scale well.  Thus, I'm closing this issue.  Please feel free to reopen or to post more information if you need to.
