### ISSUE TITLE
Passing `nullptr` to unmanaged views

### ISSUE THREAD

**Issue by etiennemlb** [kokkos/kokkos#6034]
I would like to know if the following code has defined behavior:
```
Kokkos::View<Float*, Kokkos::MemoryTraits<Kokkos::Unmanaged>> v{nullptr, 0};
```
The documentation defines that the user given pointer points `to a user provided memory allocation. Must provide storage of size View::required_allocation_size(n0,...,nR)`.

The expected semantic of the code directly above is an empty view much like:
```
Kokkos::View<Float*> v{};
```
The code directly above is defined as:
`Default Constructor. No allocations are made, no reference counting happens. All extents are zero and its data pointer is NULL.`

The dilemma lies in what is a memory allocation. Is `nullptr` representing a memory allocation of size 0 ?

See: https://kokkos.github.io/kokkos-core-wiki/API/core/view/view.html

**Comment by masterleinad** [comment]
This originated from https://kokkosteam.slack.com/archives/C5BGU5NDQ/p1680684987174709.

**Comment by nliber** [comment]
My opinion is that we should make it valid if it isn't, but I don't know that it is valid right now.  It actually hinges on whether or not the pointer value is ever passed to things like `memcpy`, as you aren't allowed to pass a null pointer to it.

From the latest C draft (N3096):

> If an argument to a function has an invalid value (such as a value outside the domain of the
> function, or a pointer outside the address space of the program, or a null pointer, or a pointer
> to non-modifiable storage when the corresponding parameter is not const-qualified) or a type
> (after default argument promotion) not expected by a function with a variable number of
> arguments, the behavior is undefined.

**Comment by dalg24** [comment]
Both
```C++
View<T*>                          u{nullptr, 0};  // runtime unmanaged
View<T*, MemoryTraits<Unmanaged>> v{nullptr, 0};  // compile-time unmanaged
```
are legal and will essentially do the right thing with the current implementation if you hand them to `deep_copy()`.

If instead of a null pointer you construct with some other valid pointer, the current implementation can lead to undefined behavior.  It is not urgent but we need to fix this.

I tend to think that we should also make this
```C++
View<T*> w{(T*)0xDEADBEEF, 0};
```
yield a valid view.

**Comment by PhilMiller** [comment]
If 
```c++
View<T*> w{(T*)0xDEADBEEF, 0};
```
Ever leads to doing arithmetic on the data pointer, then it's UB, because the pointer isn't valid. I would be really hesitant to endorse the validity of a View constructed with an invalid pointer just because its extents are all 0.

**Comment by PhilMiller** [comment]
In terms of what we ought to do, I think explicit unmanaged construction with a `nullptr` argument should yield a View in the same state as if it were default constructed. That avoids us having to think about any deeper special cases that we haven't handled.

**Comment by dalg24** [comment]
> If
> 
> ```c++
> View<T*> w{(T*)0xDEADBEEF, 0};
> ```
> 
> Ever leads to doing arithmetic on the data pointer, then it's UB, because the pointer isn't valid. I would be really hesitant to endorse the validity of a View constructed with an invalid pointer just because its extents are all 0.

Pointer arithmetic on nullptr also leads to UB.  I consider that our current `deep_copy` implementation is buggy, it just happen to work for null pointers.
There is not much involved in making it work on our end, just making sure that `View::extents()` returns `0` when appropriate.   From there, it is rather straightforward to not get into trouble,  it comes down to not violating preconditions.  Same rule for our internals as for our users.

**Comment by dalg24** [comment]
To be clear ,there is nothing special about that silly invalid pointer in the code snippet.  Consider
```C++
View<int*> w(buffer+offset(i), offset(i+1)-offset(i));
```
where buffer is some valid pointer and assume there is some `i`  for which `offset(i+1)-offset(i)` is `0`.
Here, one would be rightfully upset if Kokkos constructs some toxic view that will explode and catch fire when handing it to algorithms.

**Comment by ajpowelsnl** [comment]
Hi @nliber - any noteworthy progress on this issue?

**Comment by nliber** [comment]
In [basic.compound]p3 we have:

[…]
Every value of pointer type is one of the following:
— a pointer to an object or function (the pointer is said to point to the object or function), or
— a pointer past the end of an object, or
— the null pointer value for that type, or
— an invalid pointer value.


In [basic.stc.general]p4 we have:

[…]
Indirection through an
invalid pointer value and passing an invalid pointer value to a deallocation function have undefined behavior.
Any other use of an invalid pointer value has implementation-defined behavior.

With footnote 25:

Some implementations might define that copying an invalid pointer value causes a system-generated runtime fault.
========
The mere act of reading an invalid pointer value triggers the above implementation-defined behavior (and there is nothing we can do about that).

I agree that there is nothing special about:

`View<int*> w(buffer+offset(i), offset(i+1)-offset(i));`

If `buffer+offset(i)` is an invalid pointer value, it triggers implementation-defined behavior.

With

`View<T*> w{p, 0};`

We could just store a null pointer value (and I think it might work in all cases if we pass a const reference to p to the View constructor, since we would not have to read the pointer value itself).   This has the negative effect of breaking the following expectation:

`assert(View<T*>{p, 0}.data() == p);`

Note:  I’m not a fan of this.  Besides the assertion, it sure seems like we are doing a lot of behind the scenes heroics to make this work, in a corner of the language that could very well change should CWG find a reason to do so (for instance, prior to C++14 it was always UB to read an invalid pointer value; I think this changed so it would work under constexpr).

Also, when talking about this issue, please distinguish between passing `nullptr` (whose type is `std::nullptr_t`, which is detectable at compile time) and passing a null pointer value (whose type is `T*` and is only detectable at run time, assuming the user never passes in an invalid pointer value).
=======
The path I’m taking in PR #6273 is to not pass zero-length ranges to memcpy, etc.
