### ISSUE TITLE
Kokkos usage of Cuda __constant__ memory

### ISSUE THREAD

**Issue by j8asic** [kokkos/kokkos#606]
Hi,
I see that functors data are fully copied in constant or shared/local device memory before the kernel execution, so I have some questions/comments:

1) How is the threshold whether to use constant or shared memory for a functor chosen? Why the 512 bytes threshold as Kokkos_CudaExec.hpp defines: `ConstantMemoryUseThreshold = 0x000200 /* 512 bytes */` ?

2) Inside `CudaParallelLaunch`, `cudaFuncSetCacheConfig` sets options for the constant memory, before `cudaMemcpyToSymbol` is called. I don't know how the Cuda specs treat this, but maybe it would be logical to firstly copy data to device, and then set its cache config.

3) Always uploading to device constant memory before the kernel execution surely comes at some cost. Are there plans that functor `operator()` could have additional parameters, by making use of templated parameter placeholders? (Sometimes constant memory cache ruins performance, and registers could come in handy) 

4) Kokkos reserves half of total constant memory for the functors `ConstantMemoryUsage = 0x008000 /* 32k bytes */`. Can we make use of the rest of the space for our program constants? Is there some kind of `ConstantsView<data_type, space>` that has statically defined `__constant__ data_type` member that can be used in any functor without its frequent copying?

Best regards,
Josip

**Comment by crtrott** [comment]
1) This is based on extensive benchmark experience for what gives best performance.
2) SetCacheConfig changes the shared memory behaviour not the constant cache.
3) We do not currently have this planned. If the functor is in shared memory, than almost all the accesses to it would come from shared memory. Putting it into registers would only work for very small functors, and in the majority of cases it hurts performance (I looked at this).
4) There are no plans for that, mostly because of the limitations of how constant cache works as an object level global symbol. What you can do is put static sized arrays into the functor, and those will than be accessed through constant cache.

**Comment by j8asic** [comment]
Thanks for the infos
