### ISSUE TITLE
View: lack of conxtexpr constructor(s) makes (non-static) constexpr methods pointless?

### ISSUE THREAD

**Issue by bartgol** [kokkos/kokkos#641]
I was trying to compute the size of some views, and I needed it at compile time for some metaprogramming (the views had all static dimensions), but I couldn't do it, because the size method is not static (that's fine), and calling it on a temporary was not good either because there's no constexpr constructor. Now, I know that I can compute the size of a view myself, by multiplying all dimensions, but since View has already a method (and it is marked constexpr) I wanted to leverage it.

This got me to wonder what's the point of all the non-static constexpr methods in Kokkos::View. If the underlying object is not constexpr, they can't be used to initialize a constexpr variable, and in order for a view to be constexpr, it must be created with a constexpr constructor (right?). In other words, these lines generate compiler errors:
```
constexpr Kokkos::View<double[2][3]> view("name"); // error: constructor is not constexpr (any constructor, really)
constexpr int size = Kokkos::View<double[2][3]>().size(); // error: enclosing class is not a literal type
```

While I would expect it to work. I understand that this would require a cascade of constexpr constructors for the members of View, and it may even be impossible now that I think about it, since some members cannot have a trivial destructor. But then I wonder what's the point of the constexpr methods of View... If they are indeed never usable as constexpr methods, then I believe the constexpr qualifier should be removed, since it is misleading (at best).

**Comment by hcedwar** [comment]
For the size you can use `View<...>::required_allocation_size(...)` which is static constexpr.

The constexpr qualification on the non-static methods is to _prod_ the compiler to do a better job of inlining and optimizing through those methods.

**Comment by bartgol** [comment]
Yes, I tought about calling that (and dividing by sizeof(double)). But if that is allowed as static, why isn't size() also static?

About the compiler, wouldn't KOKKOS_FORCEINLINE_FUNCTION do the same job (while being more clear)? Or does constexpr force more optimizations? If the latter is true, wouldn't a macro (womething lik KOKKOS_REQUEST_OPTIMIZATION or some other better wording, but still resolving to "constexpr") make the intention more clear when reading the class

**Comment by ibaned** [comment]
I'm not really a Kokkos dev but I'll attempt answers:

1. The most common use of `View`s is with runtime dimensions, so in that case `size()` needs to be non-static. Even if some kind of specialization were attempted to make `size()` static only when there are no runtime dimensions, that would mean there couldn't be a non-static `size()`, which would probably break a bunch of code that expects the non-static `size()` to always exist. Thats probably part of the reason why `required_allocation_size` has a different name, it is in effect the static `size()`.

2. Normally `constexpr` is distinct from other inline/optimization attributes in that it can go so far as to allow compile-time execution. In the specific case of non-static `size()` that happens to not be achievable in practice for the reasons you point out, but just because there aren't `constexpr` constructors now doesn't seem like a great reason to demote `size()` from `constexpr` to some kind of `inline`. `size()` is still properly `constexpr` in some cases (hopefully), it just hasn't had a chance to fulfill that potential yet.

**Comment by bartgol** [comment]
I just think that "constexpr" in front of a method conveys the message that that function can (in some circumstances, depending on the inputs) be evaluated at compile time. The fact that it has some extra optimization effects is a plus, and, if one wants to use constexpr just to exploit this plus (and there's no reason why one shouldn't), he/she should probably make it clear to the user. My two cents.
