### ISSUE TITLE
Memory management Kokkos/Cuda UVM

### ISSUE THREAD

**Issue by bathmatt** [kokkos/kokkos#646]
Question on memory management as I start to design algorithms for kokkos on Sierra.  From what I understand Sierra will have about 1/4 of the memory available to me on the GPU, and about 3/4 of the available memory will be traditional.  

My current problem of interest is a large dense matrix solve, where I will want to fill up all the memory, if I can, with the matrix, preconditioner and vectors.  I've got a few questions with the following assumptions.
GPU memory is G, traditional memory is M and G << M.  My problem fits in M, but not in G.

So, my questions are:

1. Will I be able to run my problem at all using UVM?
1. Will I be able to make a single kokkos view of size 90% of M using UVM and run my problem on the GPU assuming all the threads on the GPU will only use a subset of G at one time?
1. Will this be really horrible in performance?
1. How should I look at spooling memory to the device assuming the answer to the previous question is yes?
1. Will kokkos provide tools to make this simpler?  Thinking something like a dual_view where I can mark for soon computation, finished computation (it can be flushed), ...

Thanks
Matt

**Comment by mhoemmen** [comment]
@bathmatt Regarding (1), if I remember right, there were some talks either last week or recently that addressed this issue.  UVM can work like "cache mode," but there's a performance hit if your problem doesn't fit in GPU memory.  Regarding (3), the resulting performance was not great but not ridiculously awful.

I'm curious if known strategies for TLB optimization on CPUs would help here.  Avoiding large strides matters a lot.

**Comment by mhoemmen** [comment]
> Thinking something like a dual_view where I can mark for soon computation, finished computation (it can be flushed), ...

Do we have enough information to do a better job than the UVM system?  If we find ourselves implementing an LRU cache, then probably not.  If you can get clever with overlap, say, pipelining asynch copies to device with kernels, then probably yes, but that's a little bit more of an imperative programming style than the declarative style you've proposed (e.g., marking it as "I might need this soon," vs. just getting it).

**Comment by mhoemmen** [comment]
> My current problem of interest is a large dense matrix solve, where I will want to fill up all the memory, if I can, with the matrix, preconditioner and vectors.

We do have a collaboration with the MAGMA team at UTK.  They might have thought about how to attack the "offload to GPU where problem is too big to fit" issue.

You're doing an iterative solve, so this won't pay if your preconditioner doesn't do a lot of computation.

**Comment by crtrott** [comment]
1) Yes, you can do that today on our Power8/Pascal/NVLINK testbeds. 
2) Same as 1)
3) Depends, here is a presentation showing some of the stuff: 
  https://cfwebprod.sandia.gov/cfdocs/CompResearch/docs/NVIDIA-P100-EarlyExperience.pdf
  basically, no reuse just streaming gives you only about 4GB/s due to page fault resolution time. 
  If you have tons and tons of reuse than it should be ok again (like 100x+). 
4) if its really a dense solve using blas calls, we should just use CuBLAS which does this buffering on its own (i.e. it can do MatrixMatrix multiplications really efficient). If your algorithm basically just consists of Matrix Vector products, vector additions and dot products, the best you can do is pin the matrix in the DDR memory (CudaHostPinnedSpace) and put just the vectors in HBM memory. That will give you 45GB/s per GPU for the matrix streaming and 500GB/s for the vector access. 
5) Need to talk about what you think this should look like.

**Comment by bathmatt** [comment]
Thanks for the input.  I'll look over the talks and such.  Does CuBLAS do MPI related stuff?  I've never looked at it at all.  I think that the pinned memory is where I'm going to look at first.  As my design gets closer then I would love to have you two look it over an throw rocks at it.

**Comment by mhoemmen** [comment]
Sorry @crtrott !  I forget which talk that figure was in.  Slide 8 shows the overhead of UVM when exceeding GPU memory capacity, compared with using host pinned memory.

This reminds me to ask whether I could use host pinned memory to let the GPU write to an MPI_Win...

@bathmatt wrote:
> Does CuBLAS do MPI related stuff?

No.  You may want to talk to Victor Brunini about the MPI aspects of this kernel.

**Comment by dalg24** [comment]
> https://cfwebprod.sandia.gov/cfdocs/CompResearch/docs/NVIDIA-P100-EarlyExperience.pdf

@crtrott is this document available for non Sandia folks?
