### ISSUE TITLE
MD_Range Test with UVM

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#649]
Bus error on K80 if not setting CUDA_LAUNCH_BLOCKING and CUDA_MANAGED_FORCE_DEVICE_ALLOC

**Comment by ndellingwood** [comment]
@crtrott 
I just generated a makefile and tried to build/test with uvm (but using a K40) and saw the bus error, but it occurred before the mdrange tests began:

generated makefile command:
`../../generate_makefile.bash --with-cuda --with-serial --prefix=`pwd` --with-cuda-options=force_uvm,enable_lambda make-j=8`

runtime error output snippet:
```
[ RUN      ] cuda.view_subview_layoutright_to_layoutright
[       OK ] cuda.view_subview_layoutright_to_layoutright (3 ms)
[ RUN      ] cuda.view_subview_auto_1d_left
make[2]: *** [test-cuda] Bus error (core dumped)
make[2]: Leaving directory `/home/ndellin/kokkos/testing/CudaUVMTesting/core/unit_test'
make[1]: *** [test] Error 2
make[1]: Leaving directory `/home/ndellin/kokkos/testing/CudaUVMTesting/core/unit_test'
make: *** [unit-tests-only] Error 2
```

Is this possibly due to some of the other recent changes but exposed at different points in tests depending on architecture?

**Comment by hcedwar** [comment]
Bug was elsewhere and has been resolved.
