### ISSUE TITLE
power of two functions

### ISSUE THREAD

**Issue by hcedwar** [kokkos/kokkos#656]
Power of two functions are being used.  Should define them as public free functions conforming to anticipated future C++ standard.

http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0556r0.html

```
  template <class T>
    constexpr bool ispow2(T x) noexcept;
  template <class T>
    constexpr T ceilpow2(T x);
  template <class T>
    constexpr T floorpow2(T x) noexcept;
  template <class T>
    constexpr T log2(T x);
```

**Comment by mhoemmen** [comment]
KokkosKernels has some of these; consider bring in from there.

**Comment by ibaned** [comment]
The one that was clear is done in #1601.
Besides that one, the others behave slightly differently in the standard versus in Kokkos (the standard ones return `2^n`, while the Kokkos ones return `n`).

**Comment by dalg24** [comment]
> done in #1601

@ibaned The `Kokkos::log2` function was not declared as `constexpr`.  That said,  I am not sure how that would work with compiler intrinsic and builtin functions.

**Comment by ibaned** [comment]
@dalg24 yea, I'm unsure about that as well... especially since the current implementations have fallbacks for when intrinsics are not available, and those fallbacks involve loops etc. which can't be `constexpr` in C++11. I think we might need to wait for proper `std::log2` support to have a guarantee of `constexpr`.
