### ISSUE TITLE
Question: change label

### ISSUE THREAD

**Issue by Adrian-Diaz** [kokkos/kokkos#6654]
Greetings,

Is there a way to change the label of a managed view after it's been constructed? In this case the views weren't given labels.

Sincerely,
Adrian Diaz

**Comment by dalg24** [comment]
There is not.

**Comment by dalg24** [comment]
Given the shared ownership nature of Kokkos views, I am not convinced that it would be a good idea to allow it.

**Comment by dalg24** [comment]
You could do
```C++
  std::vector<int> v(10);
  auto w = Kokkos::create_mirror_view_and_copy(
    Kokkos::view_alloc(Kokkos::DefaultExecutionSpace::memory_space(), "label"),
    Kokkos::View<int*, Kokkos::HostSpace>(v.data(), v.size()));
  std::cout << w.label() << '\n';
```
If the device default memory space is not accessible from the host then it will use the label argument when allocating for the device view, otherwise the label will be an empty string.

If you want to provide a label regardless of whether a device backend is actually enabled or not, you need to create a mirror (allocation will always occur).

**Comment by Adrian-Diaz** [comment]
Seems to work, thank!
