### ISSUE TITLE
MSVC / GCC Extensions Issue

### ISSUE THREAD

**Issue by csiefer2** [kokkos/kokkos#671]
We still have SFINAE issues building Kokkos w/ VS2017, but here is something that can be fixed.

Kokkos_Macros.hpp defaults to using GCC extensions :
```
#if ! defined(KOKKOS_ALIGN)
#define KOKKOS_ALIGN(size) __attribute__((aligned(size)))
#endif

#if ! defined(KOKKOS_ALIGN_PTR)
#define KOKKOS_ALIGN_PTR(size) __attribute__((aligned(size)))
#endif

```
For MSVC we really want this:
```
if ! defined(KOKKOS_ALIGN)
#define KOKKOS_ALIGN(size) __declspec(align(size))
#endif

#if ! defined(KOKKOS_ALIGN_PTR)
#define KOKKOS_ALIGN_PTR(size) __declspec(align(size))
#endif
```

Using this also necessitates changes to Kokkos_ViewMapping.hpp, namely
`typedef typename Traits::value_type * KOKKOS_RESTRICT KOKKOS_ALIGN_PTR(KOKKOS_ALIGN_SIZE) handle_type ;`

and this:

`typedef typename Traits::value_type * KOKKOS_ALIGN_PTR(KOKKOS_ALIGN_SIZE) handle_type ;`

Needs to turn into:

` typedef KOKKOS_RESTRICT KOKKOS_ALIGN_PTR(KOKKOS_ALIGN_SIZE) typename Traits::value_type *  handle_type ;`

and this:

`typedef KOKKOS_ALIGN_PTR(KOKKOS_ALIGN_SIZE) typename Traits::value_type * handle_type ;`

**Comment by mhoemmen** [comment]
@csiefer2 Are you able to test those changes?  Just curious.  If so, please submit a PR :-)

**Comment by xiangfan-ms** [comment]
Hi, we (Microsoft) investigated the issues seen during compiling the library using MSVC. Here is the summary.

We found three long standing compiler bugs (I will describe them in a separate reply).

We also found several source issues.
1. The issue mentioned in this thread.
In 'core\src\Kokkos_Macros.hpp', you can use the standard conformant way: alignas(size)
2. Incorrect return type
In 'core\src\impl\Kokkos_Atomic_Windows.hpp', atomic_increment and atomic_decrement should return void.
3. Incompatible types.
atomic_fetch_add and atomic_fetch_sub implemented in Kokkos_Atomic_Windows.hpp require the two arguments to have the same type. So several calls in 'core\src\Kokkos_MemoryPool.hpp' need to use 'uint32_t(1)'. Or you can change the implementation to match the ones in 'core\src\impl\Kokkos_Atomic_Fetch_Sub.hpp'.
volatile_store has the same issue.
4. gettimeofday.c is missing. See 'core\src\Kokkos_Timer.hpp'. If I use 'ctime' instead, APIs like 'clock_gettime' are not found in time.h.

**Comment by xiangfan-ms** [comment]
Compiler issue 1:
This is seen in 'core\src\impl\Kokkos_TaskQueue_impl.hpp'.

VC incorrectly requires you to add 'typename' before 'S<T>::type'. This is because VC doesn't handle current specialization in this case.

template<typename T>
struct S {
  	using type = int;
  
  	void f(type);
};

template<typename T>
void S<T>::f(S<T>::type) {}

There are two workarounds,
1. Use 'typename S<T>::type', or
2. Use 'type' directly.

**Comment by csiefer2** [comment]
@mhoemmen Kokkos_Macros.hpp doesn't have a stub for a MSVC code path (like it does for all other compilers).  I'm loathe to make one without a consult from a Kokkos developer because I have no idea how you want this guy organized.

@xiangfan-ms Welcome to the party!

**Comment by crtrott** [comment]
Thanks for the info. I will try and see if I can make the required changes.

**Comment by xiangfan-ms** [comment]
Compiler issue 2:
This is related to how the compiler processes enumerator in the primary template. Both 'e1' and 'e2' are treated as a dummy expression with value '0' when we parse the primary template, so the two overloads are considered the same.

error C2535: 'void S2<T>::f(S1<> *)': member function already defined or declared:
 
template<bool> struct S1 {};
template<typename T>
struct S2 {
                enum {
                                e1 = 0,
                                e2 = 1,
                };
 
                void f(S1<e1> *) {}
                void f(S1<e2> *) {}
};

One possible workaround is to change the second one to '+e2' or '!!e2' based on the context.
The related code is in 'core\src\Kokkos_View.hpp'. There are 4 overloaded 'operator()'. Change the last two to use '!!is_layout_right' can workaround the re-definition error.

**Comment by xiangfan-ms** [comment]
Compiler issue 3:
This is related to lookup for nested name. The compiler incorrectly looks into the primary template (this is not allowed by the standard). Because the corresponding type in the primary template is defined as 'std::false', the dependent value will become 'false' instead.

error C2061: syntax error: identifier 'type'

#include <utility>

template <class, typename = void>
struct S1 {
	using type = std::false_type;
};

template<typename T>
struct S2 {
	using type = typename std::enable_if<S1<T, void>::type::value>::type;
};

One possible workaround is to reduce the nested level from 2 to 1. In the latter case, the compiler will not do the incorrect lookup.
Another possible workaround is to remove 'using type = std::false_type;
' in the primary template.

The related code is in 'core\src\impl\Kokkos_ViewMapping.hpp':

template<typename Traits>
struct ViewMappingHelper {
	static const bool value = ViewOffset< typename Traits::dimension, typename Traits::array_layout, void >::is_mapping_plugin::value;
};

//----------------------------------------------------------------------------
/** \brief  View mapping for non-specialized data type and standard layout */
template< class Traits >
class ViewMapping< Traits ,
  typename std::enable_if<(
    std::is_same< typename Traits::specialize , void >::value
    &&
#ifdef _MSC_VER
    ViewMappingHelper<Traits>::value
#else
    ViewOffset< typename Traits::dimension
              , typename Traits::array_layout
              , void >::is_mapping_plugin::value
#endif
  )>::type >

**Comment by xiangfan-ms** [comment]
I can build all the projects after the changes mentioned above (for source issue 4, I just comment out the logic related to gettimeofday).

Let me know if you have other blocker.

Regarding these compiler bugs, although two of them are exposed by your SFINAE logic, they are more or less non-conformance in our logic to handle dependent value / type (as you can see in the repro cases, they will fail in other scenarios). We are still evaluating the impact of changing them to be conformant. Unfortunately, many existing codebases sometimes rely on these non-conformant behavior and we need to make sure the migration experience is good with our existing customers. Or we may consider move the change under /permissive-.

**Comment by mhoemmen** [comment]
@csiefer2 Sorry for being out of band for a while.  I'll be in band soon :-)

@xiangfan-ms We welcome your diagnosis and contributions! :-D

**Comment by xiangfan-ms** [comment]
Update on 'Compiler issue 2'. A fix for it has been checked in to our development branch. So far we don't find any failures in our real world testing which implies that no one depends on our old behavior :-).
