### ISSUE TITLE
Cuda: architecture flag not added to link line

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#688]
This is only an issue when compiling with relocatable device code.

**Comment by gmackey** [comment]
The CMake fix will be in develop when it is eventually pulled in from my branch.

**Comment by gmackey** [comment]
It meaning all the changes to make the pure CMake version work.

**Comment by crtrott** [comment]
Note that I had to fix the cuda-clang one added -x cuda to the link line.

**Comment by gmackey** [comment]
I had already made the change you just made in the CMake build because of how CMake was handling spaces in a string.  It was wanting to quote it which caused the compile to fail.

Based on what I see now in Makefile.kokkos, it appears that '-x cuda' is added when CUDA is enabled and Clang is the compiler regardless of whether an architecture flag is passed.  Is this correct?

Right now '-x cuda' is only passed to CXX flags and not LD flags.  Is this correct?

**Comment by crtrott** [comment]
Yeah both of those are correct. -x cuda tells the compiler to interpret all input files as cuda containing source code. Without it only .cu files could have cuda code. Unfortunately that also means you can't use this flag on a link line or a combined compilation/link line.
