### ISSUE TITLE
DynamicView must have only POD, not structs

### ISSUE THREAD

**Issue by bathmatt** [kokkos/kokkos#690]
I have a class which is basically double[3] with constructors and the such.  However, when I try to use DynamicView I get an error 

/home/mbetten/installs/install-for-panzer/gcc-DEBUG/include/Kokkos_DynamicView.hpp: In instantiation of ‘class Kokkos::Experimental::DynamicView<ConstLenVector<double, 3u>*>’:
/home/mbetten/Trilinos/mini-PIC/src/PIC/ParticleContainer.hpp:167:46:   required from here
/home/mbetten/installs/install-for-panzer/gcc-DEBUG/include/Kokkos_DynamicView.hpp:74:3: error: static assertion failed: DynamicView must have trivial data type
   static_assert( std::is_trivial< typename traits::value_type >::value &&

Why is this, it is just a struct of POD, 
Can we get this restriction lifted?

**Comment by crtrott** [comment]
We probably could get that lifted. But you are going down a road which leads drastically away from performance. The dynamic view itself already is quite a hit, adding this will make grows absolutely horrendous slow.

Here is the main issue from what I see right away: when you grow you get a new piece of memory added to the list of things the view owns. This can basically be done with some atomic swaps. For what you want the thread which got that view must also initialize the new view elements, because otherwise it would be not assignable. Assignment calls destructor on the thing you assign to. But that destructor may not be legal callable on unitialized memory. 

So in order to do the right thing you basically need to get a lock around grow, so that the thread which initiated grow can do all the initialization.

**Comment by bathmatt** [comment]
I guess I don't understand why this is an issue for non-pod?  
Can we get grow without initialize?

**Comment by crtrott** [comment]
The issue is that non-pod must be initialized, because non-pod are not guaranteed to be assignable if you reinterpret uninitialized memory as one of those things.

**Comment by bathmatt** [comment]
Can you require an assignment operator?

How do you think we should move forward.  Having only POD is not suitable.
struct { double a,b;}; structs of POD should be allowed.

**Comment by crtrott** [comment]
Assignment operator is not enough. Consider for example the following (stupid) example:
```c++
struct A {
  int* m;
  A() {m = new int[2];}
  void operator= (const A& rhs) {
     delete [] m;
     m = rhs.m;
  }
}; 

void foo(A rhs) {
  void* ptr = malloc(sizeof(A));
  A* a_ptr = (A*) ptr;
  *a_ptr = rhs;
}
```
The assignment now may segfault because m was never initialized and thus the deallocation is invalid. POD types can't do this. That is why one always has to call the constructor on non-pod type memory.

**Comment by ibaned** [comment]
A struct of built-in types is still technically POD. According to [this](http://en.cppreference.com/w/cpp/concept/PODType), [this](http://en.cppreference.com/w/cpp/concept/TrivialType), and [this](http://en.cppreference.com/w/cpp/language/default_constructor#Trivial_default_constructor), what is making it non-POD (more specifically, non-trivial) is the presence of user-defined default constructor, copy constructor, or destructor. @crtrott 's example illustrates why these are the critical methods. The types @bathmatt  mentions don't seem to need those user-defined members. @bathmatt could you post the full declaration of your struct and maybe the definitions of those constructors/destructors if any ?

I ran into something similar but for possibly different reasons. I tried to create a `struct { double x[3];}` equivalent which could be used as a reduction value type, and C++ has bad support for `volatile` operators, so I had to supply user-defined `volatile` copy constructors, assignment, etc. Due to more C++ limitations, that means C++ would no longer define default non-volatile versions of those constructors. So, I had to supply user-defined default and copy constructors, which had trivial implementations but nevertheless had to be user-defined. I don't think this is necessarily @bathmatt 's issue, but I'd just like to point out that `volatile` can force us to create things that look non-POD but are for all intensive purposes POD.

**Comment by bathmatt** [comment]
It looks just like your example., well almost.

There is no volatile in this.  attacheched
[clv.txt](https://github.com/kokkos/kokkos/files/891046/clv.txt)

**Comment by etphipp** [comment]
Can you just use a traits class inside of the implementation to determine whether initialization is necessary?  But as @ibaned points out, you can't use the standard type traits (like is_pod<>) because the presence of volatile overloads for copy/assignment will make them false, even though the type is functionally equivalent to POD.  I've run into the same issue with POD-ness with Sacado/Stokhos scalar types that are really POD.

**Comment by bathmatt** [comment]
Eric, 
can you point to an example where this is done?  Sorry, I don't know C++ as well as I need to in order to do simple things.

**Comment by ibaned** [comment]
@bathmatt looking at your code, I think you can just remove the user-specified default constructor,  assignment operator (you can keep the `std::vector` one), and a copy constructor if there is one. Removing those should convince `std::is_trivial` your strut is okay. Setting them `= default;` should also work. You don't seem to have volatile methods so you shouldn't run into that issue. In short, you do have a POS you just need to make it look like one.

**Comment by etphipp** [comment]
Matt, The traits I was referring to would need to be inside the implementation of DynamicView, not your code.

**Comment by hcedwar** [comment]
Would ```std::is_trivially_copyable``` work for your type?  It is more relaxed than POD.

**Comment by ibaned** [comment]
@hcedwar I think that would still fail due to a user-provided copy assignment operator, but again it can be removed as its no different from the default.

**Comment by bathmatt** [comment]
OK, this compiles, I assume that all the default ones will work in kokkos functors?  i.e, when I say things like

mystruct() = default;
I can call that in a functor, Do I need a kokkos inline functino?

**Comment by ibaned** [comment]
If you don't provide them, I think the compiler-provided ones work in the case of the CUDA compiler. I'm not sure about `= default;`, I think it may interpret that as a `__host__` only function unless you give it `KOKKOS_INLINE_FUNCTION`. I haven't tried that myself.

**Comment by hcedwar** [comment]
C++11 : 
```KOKKOS_INLINE_FUNCTION ctor() = default ;```
```KOKKOS_INLINE_FUNCTION ctor( const ctor & ) = default ;```
```KOKKOS_INLINE_FUNCTION ctor & operator = ( const ctor & ) = default```

**Comment by hcedwar** [comment]
Because if you provide a non-default constructor and don't provide a default constructor then the compiler is supposed to omit the default constructor.

**Comment by bathmatt** [comment]
Thanks, looks like I'm set, still testing. Will reopen if I have an issue
