### ISSUE TITLE
Request for adding virginia.edu as login domain for Slack.

### ISSUE THREAD

**Issue by parantapa** [kokkos/kokkos#7033]
Hello

We are trying out Kokkos for some ongoing projects at the Biocomplexity Institue at UVA.
It would be helpful if we could access kokkos slack workspace using virginia.edu domain.

Thanks

**Comment by dalg24** [comment]
Please see the entry about how to join us on Slack in the [FAQ](https://kokkos.org/kokkos-core-wiki/faq.html) from our documentation.
Unfortunately we are currently not able to whitelist more domains.  You can either get an invite from anyone you might know who is already a member or you can send an email to me or Christian otherwise.

**Comment by ajpowelsnl** [comment]
Hello @parantapa - I would suggest interested parties sign up for our [Slack Channel](https://kokkos.org/kokkos-core-wiki/quick_start.html).  See the bottom of the page for Slack info.  We are just starting to work on biology codes using Kokkos.
