### ISSUE TITLE
team scratch reuse

### ISSUE THREAD

**Issue by bathmatt** [kokkos/kokkos#730]
can one reuse team scratch?  i.e, create some team scratch and then 

for (int i=0;i<10;++i)
   View<double> v(team_scratch(1));

So when v goes out of scope, the memory of team_scratch does or does not get returned.

**Comment by bartgol** [comment]
I asked the same question a while ago. I found out that each of those views will hold a pointer to a different area of the scratch memory. To avoid asking for a 10x larger scratch memory when you only need one view, you can manually take the scratch memory, and then feed it to the views by hand. Something like this.

```
double* ptr = reintepret_cast<double*>(exec_space.team_scratch(0).get_shmem(1));
for (int i=0; i<10; ++i)
{
  View v1 (ptr);
  /* do stuff with v1 */
}
```

The reason is that every call to get_shmem moves an internal memory offset used to keep track of how much memory has been asked for, so that the next call to get_shmem will use a different part of the memory. The scratch memory has no way to know if a pointer provided with a previous call to get_shmem is no longer used, so it must provide a different pointer every time. So instead of relying on the View constructor to get the shared memory from the team_scratch, you take that pointer yourself once and for all, then you manually feed it to the view constructor every time you need it. Just make sure your view has MemoryUnmanaged as memory traits.

**Comment by bathmatt** [comment]
Ok, Thanks, that is what I thought...

**Comment by crtrott** [comment]
Perfect explanation :-)

**Comment by bartgol** [comment]
After months of head banging on the wall, "something" is starting to sink in... =)
