### ISSUE TITLE
Kokkos CUDA failes to compile with OMPI_CXX and MPICH_CXX wrappers

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#776]
LAMMPS uses the `OMPI_CXX` and `MPICH_CXX` wrappers, see below. However, this functionality was broken due to recent changes in `Makefile.kokkos`.

<pre>
export OMPI_CXX = $(KOKKOS_PATH)/config/nvcc_wrapper
CC =            mpicxx
</pre>

See PR #775 for a fix.

**Comment by stanmoore1** [comment]
The issue is that when using `OMPI_CXX` the nvcc compiler isn't found, and I get errors like:

<pre>
g++: error: =sm_35: No such file or directory
</pre>

**Comment by stanmoore1** [comment]
This was broken by b586204589bf1a2936a3ec16b4c40506be2af74f.

**Comment by crtrott** [comment]
We triaged the problem. There is a real issue with the root cause being that you can't seem to be able to set environment variables for commands run in the shell inside of Make. This means if you try to set OMPI_CXX inside of the Makefile it will be honored for the actual compilation, but some of our "What compiler I am using" logic doesn't see that setting. The associated pull request works around the issue in a sane way for now, but we need to be aware that it doesn't fix the root issue.

**Comment by nmhamster** [comment]
@dsunder - I found this on the GNU make documentation. I think it may be useful for you: https://www.gnu.org/software/make/manual/make.html#Execution
