### ISSUE TITLE
kokkos complex function overloading problem

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#807]
Hi, 

When my variable is one among "double, std::complex<double>, Kokkos::complex<double>" and I would like to use a "abs" function, it has some ambiguity. 

case  ``std::abs``, this does not work with Kokkos::complex<double>.
case ``Kokkos::abs`` this does not work with double (there is no proper function overload for built in type).
case ``fabs`` definitely this does not work with complex types. 
case ``abs`` this only takes integer variable. 

How can I use abs function properly when my variable is given from template ?

**Comment by etphipp** [comment]
In the code/function you want to call abs() in, try adding

using std::abs;

and then don't specify a namespace when calling abs().  When your type is double, it will call std::abs because of the using statement.  For any other type, it should find the proper overload from argument dependent lookup (assuming the overloads are put in the same namespace as the type).  This is what I recommend for users of Sacado.

**Comment by kyungjoo-kim** [comment]
Oh.... it is nice~

**Comment by mhoemmen** [comment]
@kyungjoo-kim you could also use Kokkos::ArithTraits.
