### ISSUE TITLE
runtime error with declaration of a 2 dimensional View of Kokkos::complex<double> data type

### ISSUE THREAD

**Issue by rahulgayatri23** [kokkos/kokkos#851]
I am getting the following error: 

"terminate called after throwing an instance of 'std::runtime_error'   
what():  Kokkos::OpenMP parallel_for ERROR: not initialized 

Traceback functionality not available "

when I try to declare a 2-dim view of Kokkos::complex<double> in this way 
Kokkos::View<Kokkos::complex<double>** > foo ("foo", n1, n2);

I have initialized the Kokkos library and I am not sure what other initializations I am missing.

**Comment by mhoemmen** [comment]
`Kokkos::initialize` initializes the default Kokkos execution space, and its host mirror's execution space (currently only relevant for `Kokkos::Cuda`).  If some other execution space is the default, then `Kokkos::OpenMP` might not be initialized.  Try first checking `Kokkos::OpenMP::is_initialized()`.

**Comment by rahulgayatri23** [comment]
The Kokkos::OpenMP::is_initialized() returns true, i.e., the OpenMP is initialized, but still the error continues. 
I thought that KOKKOS_DEVICES=OpenMP/Cuda initializes the respective execution spaces. 

The error occurs, even when I try to compile for Cuda
Kokkos::Cuda::Cuda instance constructor : ERROR device not initialized
Kokkos::Cuda::Cuda instance constructor : ERROR device not initialized

**Comment by rahulgayatri23** [comment]
Found the issue, was missing the braces between Kokkos::initialize and Kokkos::finalize.

**Comment by crtrott** [comment]
Just as an explanation: Kokkos::complex<> is not a full POD type since it has custom constructors. Due to that we need to placement new construct and later destruct the elements of the view in a parallel region. As a consequence we actually run a kernel, when the view goes out of scope. In your case that happened after finalize, and thus gave the observed error. With POD type views we do not need to run the kernel so it can go out of scope after finalize.
