### ISSUE TITLE
Add view label to `View bounds error` message for CUDA backend

### ISSUE THREAD

**Issue by stanmoore1** [kokkos/kokkos#870]
It would be *really* helpful for debugging if the the view label was added to a `View bounds error` on the device with the CUDA backend. Right now, all I get is:

<pre>
:0: : block: [0,0,0], thread: [0,26,0] Assertion `View bounds error` failed.
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaDeviceSynchronize() error( cudaErrorAssert): device-side assert triggered ../../lib/kokkos/core/src/Cuda/Kokkos_Cuda_Impl.cpp:122
Traceback functionality not available
</pre>

**Comment by ibaned** [comment]
Hmmm... one problem would be that `View::label()` returns a `std::string` right now, which is a no-go inside GPU code. The second problem being that even simple string appending without `std::string` or even `strcpy` becomes a real chore on the GPU. There may be ways around those obstacles, just noting that this is non-trivial to do.

**Comment by stanmoore1** [comment]
Well, trying to find out which view is out of bounds without any hints from Kokkos is also non-trivial :)

**Comment by ibaned** [comment]
yep, yep. I'll try to figure it out, its not impossible yet.

**Comment by stanmoore1** [comment]
This would be a non-issue if `gdb` or `cuda-gdb` could give me the line number in my functor where it is crashing, but the last line in my code that the stack trace shows is where I call the parallel_for and then the stack trace goes into `Kokkos_Parallel.hpp`, which isn't helpful at all.

**Comment by stanmoore1** [comment]
Using `cuda-gdb` only gives a single frame strack trace of `Kokkos_Cuda_abort.hpp:75`.

**Comment by stanmoore1** [comment]
The view label is stored as a `char array`, not as `std::string`, so why not just copy that up to device memory and `printf` it out as a `C-string`? Seems pretty trivial to me...

**Comment by ibaned** [comment]
It is actually already in device memory, _for some views_. Much of what I've been doing for the past day is looking for the cases of views that don't have a label, this includes `Memory::Unmanaged` and views that don't have `Memory::Unmanaged` but were constructed by being given a pointer. I _think_ that I can detect all these edge cases safely inside GPU code...

Although `printf` technically works on device, we are right now calling the CUDA assertion fail handler. Its not clear to me whether the `printf` call is guaranteed to get its output to the user if it is immediately followed by an assertion fail. This is definitely something that is not guaranteed with regular `printf` on CPUs. What we know works is to build up a C-string in a buffer and pass that to the assertion failure handler; that is guaranteed to get you the output.

Getting to that `char` array without the aid of any of the pointers currently stored in structures in host memory requires walking backwards from the start of the user-writable portion of a shared allocation to access the hidden header. This is right now handled by code that can only be run on the host, so I need to add the equivalent code as a GPU-callable function. In addition, I had to confirm that all views have a pointer to the true start of the shared allocation. I was worried this wouldn't be the case for sub-views, but I think it is okay now.

So yes I've been thinking about this, yes I think it can be done safely in 90% of the cases, but no it really isn't trivial, in part because there is a whole zoo of different species of `Kokkos::View`, including user-defined ones that Kokkos doesn't even know about ahead of time.

**Comment by stanmoore1** [comment]
I'm totally fine if this isn't 100% general and gives the old behavior (no label) for difficult edge cases.

**Comment by ibaned** [comment]
yea, it has to do that (some views just don't have a label), but that still requires correctly detecting such edge cases. I basically can't let the behavior get worse for any of the special cases.

**Comment by ibaned** [comment]
okay, I think I have a decent implementation as #882
