### ISSUE TITLE
Iterator support?

### ISSUE THREAD

**Issue by ryanmrichard** [kokkos/kokkos#880]
Hi all,

I am a postdoc working on the NWChemEx project and looking to possibly use Kokkos for the on node parallelism aspect; however, the target code to be parallelized is written in terms of iterators (technically input iterators, the important point being it is not a random access iterator).  I looked through the tutorials and source, but could not seem to find any suggestions that Kokkos could support iterators.  Did I overlook this?  If not is it possible to add this feature?

Thank you in advance.

**Comment by ibaned** [comment]
Hi @ryanmrichard ,

The main issue is see with this is that a non-random-access iterator by definition can only be incremented one at a time, so the iteration is by definition a serial (non-parallel) operation. That already puts a huge damper on how much parallelism you can get out of it. I would recommend trying to add random-access support to the existing code.

Kokkos is based on, at a simple level, integer indices, but more generally it is based on Policies. We haven't used iterators to date, because the existing codes that fund Kokkos are already based on integer indices. This is in some sense more convenient, because it doesn't tie you to a specific container that you're iterating over. You can easily simulate iterator-based support (with random-access iterators!) by setting `iterator = begin + i`. It is likely technically possible to create some kind of IteratorPolicy for convenience, but we likely don't have funding to undertake that at the moment.

**Comment by ryanmrichard** [comment]
Thank you.  I totally understand designing libraries in line with funding situations.  

Unfortunately, I have a very C++ code (STL containers, range-based for loops, input iterators, *etc.*).  These situations do not easily lend themselves to index based approaches (or do so only with much hassle).  The particular situation I am looking at is a loop over pairs of objects; however, some of those pairs will be screened out.  Therefore I do not know ahead of time what the i-th object will be.  Thus to use Kokkos I will have to restart the iterator each time and burn off i iterations to determine what I am supposed to do.  I can easily code that up, but only wanted to do that if there was no other way.

Again thanks for the reply.

**Comment by hcedwar** [comment]
For clarity:  Your algorithm iterates and inserts/erases members within the container while iterating?  I've seen this pattern and it has inherent challenges for parallelization with any programming model.

**Comment by ibaned** [comment]
I interpreted it as something simpler, where only certain members would do serious work while others are a no-op after being identified. In this case you can for starters just do a `Kokkos::parallel_for` over all pairs and just do the check and operation or no-op on all pairs. This may give decent speedup out of the box. All you have to do is implement random access into the original container.

As for inserting and erasing, I tend to implement those algorithms by first identifying large batches of needed inserts or deletes and then applying them in batch fashion. This can be done efficiently by leveraging `Kokkos::parallel_scan`. This is more involved, but we can answer further posted questions about it.

**Comment by ryanmrichard** [comment]
Your interpretation is correct aside from the fact that there is no actual container.  Members are generated on the fly.  Generating an arbitrary member of the sequence is only doable by starting over every time in a very long sequence.  That said, if members are only requested in increasing order, *i.e.* if a thread will only ever be responsible for say doing iterations 1,5,9, *etc.*, but never say 5,1,9,*etc.*, then iterations can be burned off until the desired iteration is found.  My understanding is Kokkos makes no such guarantees though.

Your batch idea may be a possible workaround. Burn the first, say 100 iterations off into a random access container; parallelize that.  Repeat.

**Comment by ibaned** [comment]
> Burn the first, say 100 iterations off into a random access container; parallelize that. Repeat.

Assuming that this "burn off" takes considerably less time than the actions you perform on the members themselves (see [Amdahl's Law](https://en.wikipedia.org/wiki/Amdahl's_law)), this sounds a good approach worth trying. In general, larger batch sizes will should improve performance while consuming more memory. This becomes a tuning parameter.
