### ISSUE TITLE
Can we expose kokkos_impl_yield ?

### ISSUE THREAD

**Issue by kyungjoo-kim** [kokkos/kokkos#953]
In Kokkos_Spinwait.cpp, it uses portable yield routine (with some smart timer). Can we get this api exposed ?

**Comment by crtrott** [comment]
First: insert here a 20 line tirade about how you shouldn't write stuff which needs yield since its not portable, a really low level feature which will prevent future optimization yadayadayada

Second: since I know you still want to use it: use the one from the impl namespace and be prepared to fix your code when we happen to change the API. This is not something I would like to put in the public API because people would think its a good idea to use that.

**Comment by kyungjoo-kim** [comment]
yes. impl space is fine (i do not personally expect it to be public either) but the code is not included in the header but included in cpp. the yield routine is not included in the impl space either.
